### ISSUE TITLE
Issues and Suggestions 

### ISSUE THREAD

**Issue by Holly-Chan** [JasonStein/Notepads#1]
Hi, just downloaded the app and I loved it. Here are some suggestions and issues I had while using it:

Issues:

1. Word Wrapping not retaining: If the user select the option it will only be active on that file, so you need to select the option again if you open another.
 
2. Word Wrapping is working differently compared to notepad on .ini: When you use word wrapping on .ini files, everything after the "=" is pushed to another line instead of only pushing the last character. 
![ini](https://user-images.githubusercontent.com/9482398/59313047-b95e1300-8c85-11e9-939f-198d65d271f2.png)
Here is when I change the "=" to an s
![ini2](https://user-images.githubusercontent.com/9482398/59313083-e9a5b180-8c85-11e9-93f0-3f028d0600e5.jpg)

Suggestions:

1. Allow me to choose the color of the active tab and the color of the floppy disk. 
![color](https://user-images.githubusercontent.com/9482398/59312890-26bd7400-8c85-11e9-9db6-ff2869bb48df.jpg)
 
2. Allow me to change the default font and its color.
3. Allow me to change the background transparency opacity.
4. Support for .ini, .cfg, .log 

Overall great work on the app,I'm very pleased with it, very fast and simple like it should be imho

**Comment by JasonStein** [comment]
Word wrap option that I added to the right click context menu is per Tab based and it is intended. For global word wrapping option, I will add it to the settings panel once I finished that part. 

For that .ini wrapping issue, I need to take a look.

And all of your suggestions are in my plan. I will be available once I release the beta version.

**Comment by JasonStein** [comment]
Hi @Holly-Chan , I have implemented most features you mentioned. I am closing this issue for now.
