### ISSUE TITLE
[Bug] Notepads is broken after trying to paste huge text

### ISSUE THREAD

**Issue by andretaranto** [JasonStein/Notepads#1010]
**The bug**
- Notepads doesn't work anymore.

**What happened**

- I copied a huge text and pasted inside Notepads;
- The app froze. I waited for several minutes, nothing happened;
- I decided to close the app on Task Manager;
- I tried to open Notepads again;
- The app window opens, but it's empty. Tabs from last session have disappeared;
- App is unresponsive, althought you can see it on Task Manager consuming more than 30% of CPU resources.

**To reproduce**
- Try copying a huge text and pasting on Notepads.

**Expected behavior**
- I expected Notepads worked again after being reopened.
- Is there a way to **recover** last session tabs? Some of those tabs had not been saved, since I activated session snapshot and therefore the user should not worry about saving tabs.
- Where are the app "temp" files located? Is it possible to tweak them in order to have the app working again?

**Desktop**
 - OS: Windows 10 Pro 21H2 19044.1415
 - Notepads v1.3.7.0

**Comment by JasonStein** [comment]
The app is actually loading the text from your last session but since there are too much text to render, it feels slow and unresponsive. This is a problem with the WinRT's RichEdit control used in this app and I cannot fix it.

**Comment by andretaranto** [comment]
@JasonStein, thanks for your reply.
Is there a way to delete (or edit manually) last session file(s), so I can reset Notepads?

**Comment by JasonStein** [comment]
> @JasonStein, thanks for your reply. Is there a way to delete (or edit manually) last session file(s), so I can reset Notepads?

If you don't care about your last session at all, you could just go to Settings->Apps->Apps & features ->Notepads->Reset

So simply right click on Notepads icon and click "App Settings".
