### ISSUE TITLE
Keyboard shortcuts not working

### ISSUE THREAD

**Issue by AFTheoForay** [JasonStein/Notepads#102]
**Description**
Keybord shortcuts not working. So I can't get the preview for .md files or the side-by-side comparison between version for other files. 

**Desktop**
 - Windows 10 1903 18362.267

**Comment by JasonStein** [comment]
You are using v0.9.6.0 right? DiffViewer and Markdown are first added in v0.9.6.0.

**Comment by AFTheoForay** [comment]
Yes I use :
![image](https://user-images.githubusercontent.com/52745535/62425191-9de91480-b6d8-11e9-9ca6-6338f7f12e0f.png)

**Comment by AFTheoForay** [comment]
Okay my bad, I just got the update actually, I see it now...
By curiosity, what tool do you use for the MD preview ?

**Comment by JasonStein** [comment]
This is the control I use to render Markdown: https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/markdowntextblock
