### ISSUE TITLE
[Feature request]Install to folder location what won't change on every update

### ISSUE THREAD

**Issue by bacevs** [JasonStein/Notepads#1023]
**Is your feature request related to a problem? Please describe.**
I am currently using a registry hack to replace Windows Notepad with Notepads, this registry hack relies on the installation folder to remain "static".  
Example: "C:\Program Files\WindowsApps\19282JackieLiu.Notepads-Beta_1.4.6.0_x64__echhpq9pdbte8\Notepads.exe"

**Describe the solution you'd like**
Would it be possible to have a installation folder remain in the same folder or name even after an update or perhaps have an option baked into the app to replace windows notepad. 

Currently the installation folder is `C:\Program Files\WindowsApps\19282JackieLiu.Notepads-Beta_1.4.6.0_x64__echhpq9pdbte8`
However it would seem that a future notepads update will change to a different folder name hence breaking my registry hack to replace notepad.

**Describe alternatives you've considered**
I've tried looking for a non Microsoft store installer that installs in the usual "C:\Program Files" folder but haven't found one. 

**Additional context**
The reg hack I'm using is the one outlined here [http://code.kliu.org/misc/notepad2/](http://code.kliu.org/misc/notepad2/) under the "Replacing Windows Notepad with Notepad2" sub heading.

**Comment by gmfuster** [comment]
si,a ver que tal va el dia hoy
    On Thursday, January 13, 2022, 11:00:23 PM EST, Bobi Acevski ***@***.***> wrote:  
 
 


Is your feature request related to a problem? Please describe.
I am currently using a registry hack to replace Windows Notepad with Notepads, this registry hack relies on the installation folder to remain "static".
Example: "C:\Program Files\WindowsApps\19282JackieLiu.Notepads-Beta_1.4.6.0_x64__echhpq9pdbte8\Notepads.exe"

Describe the solution you'd like
Would it be possible to have a installation folder remain in the same folder or name even after an update or perhaps have an option baked into the app to replace windows notepad.

Currently the installation folder is C:\Program Files\WindowsApps\19282JackieLiu.Notepads-Beta_1.4.6.0_x64__echhpq9pdbte8
However it would seem that a future notepads update will change to a different folder name hence breaking my registry hack to replace notepad.

Describe alternatives you've considered
I've tried looking for a non Microsoft store installer that installs in the usual "C:\Program Files" folder but haven't found one.

Additional context
The reg hack I'm using is the one outlined here  under the "Replacing Windows Notepad with Notepad2" sub heading.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JasonStein** [comment]
The folder location is decided by the OS/MS Store. It is not something that I can configured with.

**Comment by bzzrak** [comment]
c:\users\yourname\appdata\local\Microsoft\Windowsapps\notepads.exe
