### ISSUE TITLE
[Feature request] Allow actually white background

### ISSUE THREAD

**Issue by neubland** [JasonStein/Notepads#103]
**Is your feature request related to a problem? Please describe.**
I like Notepads as a replacement for notepad.exe. Also, I use light mode, as I am not a fan of dark mode everywhere. In notepad.exe the background is actually white. In Notepads, the background has transparency that can't be fully disabled and is more grey than white. I don't like light grey backgrounds.

**Describe the solution you'd like**
* Make it an option to disable transparency completely.
* Make it an option for the background to be actually white. Maybe this would be a "custom color" background

**Describe alternatives you've considered**
If transparency is disabled the dark mode becomes very very dark. Often it is more pleasing to the eye for the dark mode to be dark but the contrast not being too high.
Alternative solution: Have pre-defined transparency-free modes that are not too harsh.

**Comment by JasonStein** [comment]
This is in my plan and I should be working on it pretty soon.

**Comment by JasonStein** [comment]
I have made some changes to make sure when background tint opacity sets to 100%, app uses solid color instead of acrylic texture. It will be available in v0.9.7.0. I will tweak the color schema for Dark and Light (when opacity sets to 100%) later.
