### ISSUE TITLE
[Feature request] Add Shortcuts to Text Editor

### ISSUE THREAD

**Issue by baynaj** [JasonStein/Notepads#1030]
Looking to be able to add more shortcuts in order to lessen the amount of clicking. 

I would like to see the addition of a Word Wrap and Bold Text toggle shortcut

The Windows Text editor, does not allow to highlight sections and edit the font of those selected areas. This application could use that functionality. Specifically, highlighting a set of words and set their font size, weight, color. 

@JasonStein I have a prototype and will be submitting a PR shortly for you to review.

**Comment by JasonStein** [comment]
Bold Text? Notepads is not a rich text editor.
