### ISSUE TITLE
[Feature request] Real/efficient single line selection

### ISSUE THREAD

**Issue by jducaud** [JasonStein/Notepads#1033]
**Is your feature request related to a problem? Please describe.**
I was frustrated when I wanted to select a single line (or a part of it, including its last visible character) and ended up selecting the `newline` character at the end of the line (making my selection a multi-line one, instead of a single one).
Now that I'm aware of this Notepads behaviour, frustration comes from the extra time spent on avoiding the `newline` character each time I select a single line (or a part of it, including its last visible character).

**Describe the solution you'd like**
I'd like Notepads to select the `newline` character only when I make a real multi-line selection (that is: starting the selection on a line and ending it on another).

**Describe alternatives you've considered**
I can't see any alternatives for now...

**Additional context**
I had mixed feeling about creating a [Feature request] or a [Bug] for that issue.
Anyway, Notepads is a great software and I love it.

**Comment by JasonStein** [comment]
![image](https://user-images.githubusercontent.com/1166162/152286924-c5f6c4b0-11e6-4506-aefd-09dd95b663e0.png)

**Comment by jducaud** [comment]
OMG... That was so simple. I'm so embarrassed I didn't try that option (which I was aware of) before posting here.

Anyway, thank you @JasonStein for taking the time to show me this.
