### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by karimk123** [JasonStein/Notepads#1036]
**Describe the bug**
letter f takes less space than other letters
**To Reproduce**
type "f" in lower case and see that it takes less space than other lower case letters.

**Expected behavior**
it should take the same space as other letters 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 1809
 - Version v0.9.3.0

**Additional context**

**Comment by JasonStein** [comment]
Are you using mono font or not?

**Comment by karimk123** [comment]
Yea sorry i just realized i was using Arial Rounded MT so it's not mono.
