### ISSUE TITLE
希望可以优化启动时间

### ISSUE THREAD

**Issue by natui132** [JasonStein/Notepads#1041]
相比于windows原版记事本的启动速度还有有一定差距，尤其在性能不好的机器上运行，会有明显的差异，并且再打开同一文件的情况下内存占用是原版记事本的十倍之多，希望在启动速度是可以得到优化

**Comment by JasonStein** [comment]
UWP app相对于win32 app的话有很多dependency需要加载，所以在机械硬盘上的启动速度会明显比win32应用慢。这个没办法，特别是机械硬盘在读取大量小文件时候的时间开销是比固态慢很多很多倍的。
