### ISSUE TITLE
Program for everyone

### ISSUE THREAD

**Issue by NeilRiver** [JasonStein/Notepads#1042]
Hello, Mr. Developer, please consider the proposal, in third-party methods for installing your software.
Because:
Microsoft Store removed in all organizations
the installation package is limited in all organizations
All organizations have a powershell block

and it turns out that ordinary people cannot use your program because of the bad reputation of Bill Gates, although it seems that he is not a Jew and not a lizard to glorify himself like that.

I ask you to distribute the installation of the program via .exe and Chocolatey to your github

p.s. I tried to install your program through powershell, 2 errors popped up in missing modules.

**Comment by JasonStein** [comment]
All UWP apps requires the presence of MS Store and I have no control over it. Please send this message to Microsoft. But I guess, until I rewrite the whole app using WinApp SDK, you won't see a standalone installer version of this app.

**Comment by survivor303** [comment]
so how about winapp sdk? :) we need this to chocolatey, winget isnt ready and store is full of crap. so please :)
