### ISSUE TITLE
[Feature request] Autosave session

### ISSUE THREAD

**Issue by bearoxo** [JasonStein/Notepads#1044]
**Is your feature request related to a problem? Please describe.**

- Sometimes PC or program crashes. Notepad contents are not saved.

**Describe the solution you'd like**

- Autosaves every time there's any changes made (like in Notepad++), where if anything is closed or crashed, reopening the app will just restore the last session.

**Describe alternatives you've considered**

- Just installed the app, first time trying to use it. This is the first feature that I checked. Looks promising but without this feature, guess I'll just continue using the good old Notepad++.

**Comment by AlvinLIQ** [comment]
I tried add SaveContentToFile in TextChanged event, but seems like it needs a new save function for it, can't just rewrite everything when changes made.

**Comment by bearoxo** [comment]
My bad. I didn't notice the "Session Snapshot Settings".

![image](https://user-images.githubusercontent.com/53261024/154835988-d1504bf6-71fd-4ecf-8649-7bc9c334509e.png)
