### ISSUE TITLE
[Bug]Cant change bg opacity

### ISSUE THREAD

**Issue by SpandyBoss** [JasonStein/Notepads#1045]
**The bug**
I can change the background tint opacity

**To Reproduce**
Steps to reproduce the behavior.

https://user-images.githubusercontent.com/77114710/155479835-773e3092-abd2-4d71-8508-2a48ef4976c6.mp4

**Expected behavior**
The bg opacity should change to make the notepads app bg blur and provide a good loo

**Desktop:**
 - OS:  Windows 10 
 - 21H2

**Additional context**
Notepads version : 1.4.6
Downloaded from :- Microsoft Store

**Comment by loftyyyy** [comment]
Encountered the same thing, have you found any solution?

**Comment by JasonStein** [comment]
There is a system level transparency setting you need to turn on before you can change the opcacity on a per-app basis.
<img width="545" alt="Screen Shot 2022-02-24 at 1 42 48 PM" src="https://user-images.githubusercontent.com/1166162/155612623-30366d39-dedb-4cbf-96a8-dc755f077b55.png">

**Comment by loftyyyy** [comment]
Thanks a lot. It would be nice if you can put that in the README.md, anyways you've made a great app and it's  free, so thank you for that again.

**Comment by SpandyBoss** [comment]
Thanks for answering
