### ISSUE TITLE
[Feature request] Join Lines for Separate Lines

### ISSUE THREAD

**Issue by AaronB2019** [JasonStein/Notepads#1052]
**Is your feature request related to a problem? Please describe.**
I have to note down certain things referring to the numbering beside it. Then, once I'm done, I need to remove all of the spaces to get it into a whole line so I can copy it into Excel. Or else, excel will simply put all into multiple cells which is terrible.

**Describe the solution you'd like**
Just like Notepad++. Highlight all the lines, then Ctrl + J to join the lines together.

**Describe alternatives you've considered**
Right now, I would write down everything in Notepads. Then, open up Notepad++ to perform the lines joining.

Thank you for your time.

**Comment by AaronB2019** [comment]
Edit: Regular expression can be used **\s*** but shortcut would be easier

**Comment by JasonStein** [comment]
Seems like VSCode also has this feature built-in. I will add this feature in the next release. Btw, a space is needed to separate each line after the joining right?

aaa
bbb
ccc

->

aaa bbb ccc

**Comment by AaronB2019** [comment]
yes that's correct! Thank you so much!

**Comment by JasonStein** [comment]
> yes that's correct! Thank you so much! Also, do you have a date for the next release?

This coming week.

**Comment by JasonStein** [comment]
> yes that's correct! Thank you so much! Also, do you have a date for the next release?

It is on the store now, just update your app and give it a try.
