### ISSUE TITLE
Loading large files

### ISSUE THREAD

**Issue by jiannakwnna** [JasonStein/Notepads#1054]
It was translated from Chinese by translation software.
I found Notepads to be very slow for very long files,
This is important when modifying some config files and data files.
It occurs over 2,000 lines and becomes very severe over 4,000 lines.
Why not have "Notepads" load different areas of the file separately?

**Comment by JasonStein** [comment]
Notepads用的是微软第一方内置的文本框，这个winrt的文本框对大文本的支持本来就不好，所以我这边暂时也没什么办法，除非微软改进或者替换第三方文本框 ，比如notepad++用的[scintilla](https://www.scintilla.org/) 不然确实没啥办法，我也很无语。
