### ISSUE TITLE
[Bug] Selected text is hard to tell apart from selected line

### ISSUE THREAD

**Issue by DeusAres** [JasonStein/Notepads#1055]
**Describe the bug**
Using the dark colors, with or without background opacity:
When clicking on a line and selecting text, the visibility of what's selected is hard to tell because of the background color behind the text is too similar to the one of the selected line

**To Reproduce**
Click a line and select some text

**Expected behavior**
A different contrasting color between selected text and selected line

**Screenshots**
![image](https://user-images.githubusercontent.com/60852205/157765792-559b45a2-3315-4e45-838a-f1205dc07f6c.png)

**Desktop (please complete the following information):**
 - OS Windows 10 20H2 19042.1348
 - Version 1.4.6.0

**Additional context**

**Comment by JasonStein** [comment]
Don't use your windows accent color and pick one instead:
![image](https://user-images.githubusercontent.com/1166162/157790584-e1f4b6ba-a048-4b54-a839-d14e438f0d84.png)
