### ISSUE TITLE
[Bug] SOS snapshot won't restore

### ISSUE THREAD

**Issue by theweeeknd** [JasonStein/Notepads#1061]
Describe the bug
**卡在如图这里，1min后自动退出**

Additional context
**我承认自己过于沉迷snapshot，落下了几十个tab unsaved的恶习，但事已至此，怎样可以恢复数据？救救孩子~** 

Screenshots
![屏幕截图 2022-03-19 210619](https://user-images.githubusercontent.com/84619641/159122299-54624a88-894e-487c-8ea2-fa408bb23756.png)

Desktop (please complete the following information):
 - OS: [Windows 11 21H2 22000.556]
 - Version [1.4.7.0]

**Comment by JasonStein** [comment]
所有临时文件都在这个文件夹里，没有后缀，但是可以用记事本或者其他软件直接打开：
C:\Users\<你的用户名>\AppData\Local\Packages\19282JackieLiu.Notepads-Beta_echhpq9pdbte8\LocalState\BackupFiles

**Comment by theweeeknd** [comment]
> 所有临时文件都在这个文件夹里，没有后缀，但是可以用记事本或者其他软件直接打开： C:\Users <你的用户名>\AppData\Local\Packages\19282JackieLiu.Notepads-Beta_echhpq9pdbte8\LocalState\BackupFiles

大大好棒！many thx
