### ISSUE TITLE
Insert texts mark copy insert[Bug]

### ISSUE THREAD

**Issue by Zig12** [JasonStein/Notepads#107]
Hello again, Jason,
I found something else there.
![Jason_I](https://user-images.githubusercontent.com/35289434/62343409-2904b780-b4eb-11e9-9fc1-6bce3198e6d0.jpg)
![Jason_II](https://user-images.githubusercontent.com/35289434/62343498-36ba3d00-b4eb-11e9-9657-070b29f85312.jpg)
Compare with the Windows Notepad. Since the behavior is not so.

e / An idea still -> can delete marked text via context menu

Greetings Zig

**Comment by JasonStein** [comment]
This is intended since you are selecting the "line ending" character as well ("\r"). So if you want to replace current line, you should select all visible characters but not with the ending. By default, double click should select the whole line excluding the ending.
