### ISSUE TITLE
[Bug] Pressing "ctrl+home" and "ctrl+end" does not change current position

### ISSUE THREAD

**Issue by FTurnhill** [JasonStein/Notepads#1078]
**Describe the bug**
The normal behavior of pressing Ctrl+Home or Ctrl+End in other Windows apps is change the current position and view to the start of the page/document/window or the end, respectively. In Notepads, pressing Ctrl+Home or Ctrl+End brings the cursor to the beginning/end of the document but doesn't change the view. You're forced to press "up arrow" or "down arrow" to change the view, and those still change view normally.

**To Reproduce**
With a document open that is large enough that there is a scrollbar, press Ctrl+Home or Ctrl+End.

**Expected behavior**
The cursor and current view of the document should change.

**Screenshots**
Not necessary.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 
 - Version 10.0.22000 Build 22000

**Additional context**
N/A

**Comment by JasonStein** [comment]
There is a known issue regarding to this. The current workaround is to press "Ctrl+Home" or "Ctrl+End" twice (first press will set the cursor to the right position, second press will bring the view to the start/end based on shortcut).
