### ISSUE TITLE
Dont Close Saved / Unsaved Tabs on Exiting App [Feature request]

### ISSUE THREAD

**Issue by aka-0x4C3DD** [JasonStein/Notepads#1080]
**Is your feature request related to a problem? Please describe.**
There might be situations that which Windows crashes or the user accidentally closes the app. 

**Describe the solution you'd like**
Pretty much the title. Moreover, there could be features to distinguish between saved and not saved files.

**Describe alternatives you've considered**

**Additional context**
apps like sublime text & notepad++ has this.

**Comment by JasonStein** [comment]
![](https://user-images.githubusercontent.com/1166162/159564031-7daca575-912a-435d-b3ef-bfa8beaae7d0.png)
