### ISSUE TITLE
影子窗口是什么意思？

### ISSUE THREAD

**Issue by Yang-Kyle** [JasonStein/Notepads#1086]
- 总是在不知情的情况下误开了影子窗口 是不是我快捷键按得太多了？？
- 但我并不知道这个功能是干嘛的 以及如何开启和关闭

**Comment by JasonStein** [comment]
notepads支持多窗口，凡不是第一个窗口的窗口都叫影子窗口，影子窗口里不能更改设置也不会保存状态，只有第一个会。
