### ISSUE TITLE
[Bug] This app icon is not showing in the Taskbar, kindly fix it.

### ISSUE THREAD

**Issue by cilmng** [JasonStein/Notepads#1087]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1809 17763.593]
 - Version [e.g. v0.9.3.0]

**Additional context**

**Comment by JasonStein** [comment]
Looks like a system glitch to me. I have seen that happening in Windows 11 as well. Try this:
![image](https://user-images.githubusercontent.com/1166162/161814226-092b938e-9fa1-40fa-9f60-4366ea07790e.png)

**Comment by cilmng** [comment]
The icon was showing everywhere else but only not in the "Taskbar" after opened the app.
I also performed as per your instruction, but still not showing in the task bar.

**Comment by cilmng** [comment]
Hello Mr. Liu,

I did what you told me, but it still does not show on the taskbar.

By the way the icon was showing everywhere else in the desktop and file 
explorer.

See if you can work it out.

Regards,
Michael..

------------------------------------------------------------------------

**Comment by cilmng** [comment]
I am using Windows 11 with StartAllBack installed setting the taskbar to "small".
I think this might be the cause for the icon not shown in the taskbar..

**Comment by cilmng** [comment]
because the size of the icon image is too big which is overlapping the taskbar height..

**Comment by cilmng** [comment]
MY issue is now fixed, it is because I put a shortcut (Notepads.ink) under the "C:\ProgramData\Microsoft\Windows\Start Menu\Programs".
After removed the said shortcut, the icon comes back to the taskbar.
Sorry for all the inconvenience caused to you..

**Comment by Deokishisu** [comment]
This is happening to me as well. I have rebuilt the icon cache as well as tried several other solutions to try to get the icon to show when pinned to the taskbar, to no avail. The icon appears everywhere else except for the taskbar.

![image](https://user-images.githubusercontent.com/6993375/176880706-6b914b0e-b514-4262-9740-ace0f857d7b7.png)
