### ISSUE TITLE
[Feature request] Change icon "T" for "N"

### ISSUE THREAD

**Issue by allanveloso** [JasonStein/Notepads#109]
Maybe it's better for branding and to avoid confusion with **T**erminal app to change the icon "T" (which I suppose represent the word text) for a "N" representing the app's name Notepads.

**Comment by JasonStein** [comment]
T stands for text and it is a well known symbol represent texts. N is ok but it makes little sense as well. To me "N" is not better or worse than "T" so I will just keep T for now unless I have better idea.

**Comment by JasonStein** [comment]
I am going to close this issue for now unless someone have better idea. Feel free to reopen it if you have better idea.
