### ISSUE TITLE
[Feature request]何时支持大文件？

### ISSUE THREAD

**Issue by bai12123** [JasonStein/Notepads#1092]
何时支持大文件？uwp平台限制解除了吗？winui3好像出来了？

**Comment by JasonStein** [comment]
除非用WinUI3.1/3.2+[scintilla](https://www.scintilla.org/)重构（基本上就是重写了），不然短期还是支持不了。没办法，Windows App 开发已经是夕阳产业了，就连WinUI开发进度都不容乐观。。。

**Comment by bai12123** [comment]
那为什么不做一个非uwp版本（.exe?）,开个分支。。
