### ISSUE TITLE
Doesn't work with Polish characters

### ISSUE THREAD

**Issue by jaromczyk** [JasonStein/Notepads#11]
Changed the encoding to UTF-16 BE and LE, without any success.
Not able to write characters such ą, ę, ć, ś, ż, ź or ó (ALT+o opens the document).

**Comment by BernhardWebstudio** [comment]
Possibly related to #4 – do you need altGr or ctrl or a similar key on your keyboard to type the listed characters?

**Comment by jaromczyk** [comment]
Yes, in Polish it is ALT + (a, c, e, o, s, z, x)

**Comment by JasonStein** [comment]
Two PRs merged to fix the issue:

- https://github.com/JasonStein/Notepads/commit/c0eddcab0ca2ee63f18326f71e46e2f8a50e0367

- https://github.com/JasonStein/Notepads/pull/5

Please wait for few days before the store version gets updated. It will be fixed in v0.9.3.0

**Comment by JasonStein** [comment]
Close this one since it has been fixed in v0.9.3.0 and it is available in Microsoft Store as well.

**Comment by konradkalemba** [comment]
In the newest version `v9.5.0` from Windows Store the problem partially returns. It is unable to place `ś` character -- it opens a save file dialog instead. The character utilizes `ALT+S` keys combination and so does the dialog which causes the bug.

**Comment by JasonStein** [comment]
@konradkalemba That is because I changed save as shortcut from ctrl+shift+s to ctrl+alt+s which caused the problem here. I have already reverted this change and it will be available in v0.9.6.0
