### ISSUE TITLE
[Bug] Pressing shift-enter to make new lines results in repeat line numbering

### ISSUE THREAD

**Issue by PkChris** [JasonStein/Notepads#113]
Pressing shift-enter creates a vertical tab that acts as a line break and Notepads shows all new lines created in this manor as being the same line.

I created a new text document inside a folder through the Windows context menu. I opened the document in Notepads and typed the following:

`012`
`014`

Notepads inserts a vertical tab to act as a line break when pressing shift-enter. You can see the break next to `012`. The break pushes `014` down to a new line but Notepads shows any new lines using this break as being the same line. Here is a link to the text file I created: https://www.dropbox.com/s/zrat14nqt7gwlmy/Missing%20Videos.txt?dl=1

**Comment by JasonStein** [comment]
Thanks for catching it! It is unwanted behavior and I fixed it here: https://github.com/JasonStein/Notepads/commit/6807ec0ed58a0c23b97fd7f1ee2931d9ebc66409

**Comment by JasonStein** [comment]
Closing this ticket since it has been shipped.
