### ISSUE TITLE
[Feature request] Increase default line height

### ISSUE THREAD

**Issue by neubland** [JasonStein/Notepads#117]
**Is your feature request related to a problem? Please describe.**
notepad.exe has a slightly higher line-height resulting in slightly more readable text.

This might seem nitpicky, but for readability of text files line-height actually matters a lot, even slight changes.

Example:  
https://i.imgur.com/KkLHQk2.png

**Describe the solution you'd like**
1. Increase the default line height so that Notepads becomes more of a notepad.exe drop-in
2. Make it an option to change the default line-height but with granular controls (!) and not only in big steps

**Describe alternatives you've considered**
Just don't care about it

**Additional context**
I would prefer really fine-tunable font and formating options.

**Comment by JasonStein** [comment]
For 1.Increase the default line height so that Notepads becomes more of a notepad.exe drop-in
I will do it, but I might not digging too much for adding the options for line spacing. Remember Notepads is not here to replace VS Code, Word or any advanced code editor or text processor.

**Comment by JasonStein** [comment]
Tweaked here: https://github.com/JasonStein/Notepads/commit/7e7702e7b5917926fd9e235d8fe3e87d09ba1790

Before and after: 
![image](https://user-images.githubusercontent.com/1166162/62743826-c171cf00-b9f8-11e9-8aa7-fe73064bd185.png)

**Comment by JasonStein** [comment]
I have also made adjustments to DiffViewer as well to use similar line height.

**Comment by JasonStein** [comment]
This has been shipped with v0.9.8.0, closing the request for now.
