### ISSUE TITLE
Doesn't give warning when closing unsaved file

### ISSUE THREAD

**Issue by SVSurve** [JasonStein/Notepads#12]
Notepads exits without even showing a warning option whether to save or not. This may lead to losing important data

**Comment by JasonStein** [comment]
It is there in Github release version. Reason this is not in store version is because it requires approval from Microsoft since it uses restricted API. I am working on the second store release and it will have the save reminder on app close. Cheers!

**Comment by HaydnDias** [comment]
On this, would it be possible to have it remember unsaved files, it's really the main killer feature for me is that unsaved documents are still "saved"

**Comment by JasonStein** [comment]
You mean reopen unsaved files right? It is in my plan. No ETA tho.

**Comment by JasonStein** [comment]
@HaydnDias You mean reopen unsaved files on next startup right? It is in my plan but no ETA for now.

**Comment by HaydnDias** [comment]
Yes, that's what I meant, I'll look out for it! Loving the app so far.

**Comment by entdark** [comment]
How about to reopen all saved and unsaved files on next startup?
Basically open cached unsaved files and real saved files.
So the whole state after closing the app is restored on the next startup.

**Comment by JasonStein** [comment]
Yes, it is in my plan, I will start as soon as I have all immediate issues fixed.

**Comment by JasonStein** [comment]
Session snapshot has been implemented in v0.9.9.0
