### ISSUE TITLE
[Feature request] Save as... shortcut by clicking tab title

### ISSUE THREAD

**Issue by ghost** [JasonStein/Notepads#1202]
**Is your feature request related to a problem? Please describe.**
Currently, you need to use the entry under the hamburger menu for the `Save As` option. 
A `Save As` entry should be added to the tab title right-click menu. This may be a faster and more practical method.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

<details>
 <summary>screenshot</summary>

![resim](https://user-images.githubusercontent.com/110184059/220722163-7e120d77-6f18-42bb-b49e-fd0fdea25889.png)

</details>

**Comment by 0x7c13** [comment]
You can already do it by using a shortcut: ctrl+shift+s
