### ISSUE TITLE
[Bug]Extra space between listed fonts

### ISSUE THREAD

**Issue by ghost** [JasonStein/Notepads#1209]
**Describe the bug**

I don't know if this is a bug or not.
There seems to be extra space between some titles.
Please see the attached screenshots.

**To Reproduce**

**Expected behavior**

**Screenshots**

<details>
 <summary>Screenshot</summary>

![fntntp](https://user-images.githubusercontent.com/110184059/223038345-82702f6c-feb4-4948-befc-546e7b55f640.png)
![note2](https://user-images.githubusercontent.com/110184059/223037834-70a2cb75-9d11-4b08-982e-2b01cc7ac55a.png)
![note3](https://user-images.githubusercontent.com/110184059/223037844-53e0e268-265c-4786-8246-005959f5823c.png)
![note4](https://user-images.githubusercontent.com/110184059/223037849-7e2d5567-e7ea-4913-a42c-71b93145db5b.png)
![note5](https://user-images.githubusercontent.com/110184059/223037854-dbe7c4ca-368e-46d0-b972-13d323ce5d3b.png)

</details>

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Version v1.4.9.0

**Additional context**

**Comment by 0x7c13** [comment]
The alignment for each font name in that dropdown list is already set to "center". I believe it is just that some of the fonts are not designed the same way with others.
