### ISSUE TITLE
[Feature request] Multi-Encoding Support

### ISSUE THREAD

**Issue by Sinofine** [JasonStein/Notepads#123]
**Is your feature request related to a problem? Please describe.**

As is a legacy problem, There are a large quantity of files stored in local encodings such as GBK and Shift_JIS. Text Editors should have the ability to load & save with those encodings. 

**Describe the solution you'd like**

I think we should have a dropdown menu like the pattern below containing several encodings.

![image](https://user-images.githubusercontent.com/47494321/62821445-8366dd80-bba7-11e9-9fb2-23b441a9d726.png)

**Describe alternatives you've considered**

It should absolutely be in a modern text editor!

**Additional context**

The screenshot is captured in [Visual Studio Code](https://code.visualstudio.com/)

**Comment by JasonStein** [comment]
Please help me understand the scenario better:

1. Why you have so many files with varies kind of legacy encodings? (Out of curious)
2. Why can't you convert all legacy text to unicode encodings so you do not have to deal with it next time? 
3. Are they used by legacy software or what is the blocker here?

**Comment by Losses** [comment]
@JasonStein Multi encoding support is very important. Some encoding like GB2312 and JIS is still widely used.
Another thing is, if I need to edit a file with Notepads, I have to convert the encoding with another tool like Notepad++, why don't people use Notepad++ directly?
I think multi-encoding is a very very important feature, even in 2019.

**Comment by JasonStein** [comment]
I know it is important. I just want to understand the use case scenario better. To be honest, 95% of the users who use Notepads use default settings and only 2-3% of the user base use ANSI as fallback encoding. I am just curious why ANSI support is not good enough here and in what cases you need to deal with varies kind of encodings? And why you do not want to convert them into Unicode and save your time in the future? (Basically my three questions above)

**Comment by Losses** [comment]
@JasonStein Because there are a bunch of legacy tools and domain specific tools will create/read non UTF8 encoded text file, we have to use it on daily life. Because it will read and write these files, so we can't simply convert it to UTF8, once converted, these software will no longer work. 
I have seen a lot of software produce non ANSI/UTF8 text files (not only GB2312, JIS), it's really annoying, we both hate that but it indeed exists, we have to work with them.

**Comment by JasonStein** [comment]
OK, makes senses, however, I will put it in my backlog for now since I do not have time to work on this right away and the target audience is limited. Let's keep it open for now.

**Comment by JasonStein** [comment]
![image](https://user-images.githubusercontent.com/1166162/76267526-57d4d000-6228-11ea-8f1a-1ae94d22505a.png)

**Comment by JasonStein** [comment]
Closing this thread since v1.1.4.0 is released with "Auto Guess Encoding" feature.
