### ISSUE TITLE
[Bug] Inconsistent background acrylic effect when app window isn't focused

### ISSUE THREAD

**Issue by Jnss98b** [JasonStein/Notepads#126]
**Describe the bug**
Background acrylic effect shows when app window isn't focused only in dark mode

**Expected behavior**
Background acrylic effect shows when app window isn't focused regardless of theme.

**Desktop**
 - OS: Windows 10 1809 18362.267
 - Version v0.9.8.0 Beta

**Comment by JasonStein** [comment]
It is only enabled for Dark theme because the custom brush I use from another library supports dark color well. The overall experience for light theme is somewhat too grayish. I have asked author to provide a better brush for light colors, if he does not have time to do it, I will do it eventually.

**Comment by Jnss98b** [comment]
That sounds great! Thanks for your consideration

**Comment by JasonStein** [comment]
It is now implemented for light theme as well. Closing the thread for now.
