### ISSUE TITLE
[Bug] Saving document

### ISSUE THREAD

**Issue by ArtexJay** [JasonStein/Notepads#129]
**Describe the bug**
When saving a text document the notepad app will jump all the way back up to the very  first line for some reason. Needing me to scroll back down. I'm running Notepads 0.9.8.0

**To Reproduce**
I just save the text document and it shoots back up.

**Expected behavior**
What I'm expecting to see so that the text cursor stays where it is and there is no jumping up to the first line.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 1903 build 18362
 - Version [e.g. v0.9.8.0]

**Comment by JasonStein** [comment]
Fixed: https://github.com/JasonStein/Notepads/commit/369e3cf4e758b3091e609e59f2e635603a41d015
