### ISSUE TITLE
Opening same file multiple times creating multiple tab instances in the app

### ISSUE THREAD

**Issue by PhanindraNath** [JasonStein/Notepads#13]
**Repro:**
1. Open any text file using the app.
2. Repeat the step-1 for multiple times.
3. Add some different text/data in each tab instance.
4. Save each instance.
5. Close all instances, and open the file afresh.
6. Hurray, you find only last saved data. Other savings have gone :(

**Expected:** 
Opening the same file multiple times should redirect to the same instance in the app.

**Comment by JasonStein** [comment]
This is definitely something I forgot to do. I will do it today and make it a available in v0.9.3.0

**Comment by JasonStein** [comment]
Fixed:
https://github.com/JasonStein/Notepads/commit/8835f34f3d219c23622470b695c198f1cedb5e21
It will be available in v0.9.3.0

**Comment by JasonStein** [comment]
Close this one since it has been fixed in v0.9.3.0 and it is available in Microsoft Store as well.
