### ISSUE TITLE
Record window position and restore previous window position[Feature request]

### ISSUE THREAD

**Issue by lymansix** [JasonStein/Notepads#130]
Can you add features to record the window position and restore the previous window position ？

**Comment by yaichenbaum** [comment]
Doesn't it already to this?

**Comment by JasonStein** [comment]
This should be enabled by default and I did not touch this part, can you try again? Maybe a windows glitch.

**Comment by JasonStein** [comment]
can you re-pro it and record a short video if possible? Or screenshots?

**Comment by lymansix** [comment]
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by lymansix** [comment]
Close notepads after the left split screen and reopen the location of the last window that could not be recorded.
![image](https://user-images.githubusercontent.com/6296190/62860334-788c8400-bd32-11e9-9532-eac022789d35.png)
![image](https://user-images.githubusercontent.com/6296190/62860380-9bb73380-bd32-11e9-9129-27ff94a38414.png)

**Comment by JasonStein** [comment]
This is "default" behavior for all UWP apps. Split view is a special scenario/use case .

**Comment by lymansix** [comment]
Okay, I see. Thank you for your answer. 
By the way, is there any other way to do it?

**Comment by JasonStein** [comment]
You mean to remember last window position for split view? No I do not think so.

**Comment by UweKeim** [comment]
Just installed your (nice) app, and stumbled upon this "feature" behaviour.

Had to uninstall again, because if an app does not start pixel-perfect how I exited it last time, it is rather unusable to me 😢

**Comment by JasonStein** [comment]
@UweKeim This is true not only for Notepads but also for all other UWP apps including Windows 10 Email app, Calculator and even the Settings app. There is nothing I can do about it.

**Comment by yaichenbaum** [comment]
By default, UWP applications remember the size and location. This occurs when you close the app manually, this is done in Notepads because it overrides the default close method of the application to ask the user if they want to save their work. I had a workaround I used in Quick Pad, I will see if I can find what it is.

**Comment by UweKeim** [comment]
Thanks for your feedback.

**Comment by JasonStein** [comment]
> I tested Notepads and it definitely opens up with the same size and in the same location it was before closing.

Yes, that's true but not for the case that @lymansix shared. (Split screen scenario)
