### ISSUE TITLE
Markdown Syntax Highlightning 

### ISSUE THREAD

**Issue by DennstedtB** [JasonStein/Notepads#137]
Hi, 

I am not really firm with markdown parsing / rendering but is it somehow possible to add new languages to the markdown syntax Highlightning? Or maybe overwrite it? ( you mention something similar in screenshot 2 ) 

My documentations are mostly written down in markdown files and I'd love to see in the preview my syntax. Similar to the GitHub Syntax Highlightning. FYI - I am mostly developing in ABAP ( so I would need this.. )

**Comment by JasonStein** [comment]
1. https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/markdowntextblock
![image](https://user-images.githubusercontent.com/1166162/62903570-fdb66f80-bd17-11e9-8ec7-9192b624b00f.png)
2. https://blogs.sap.com/2017/02/20/abap-syntax-highlighter-and-code-folding-in-notepad/

**Comment by DennstedtB** [comment]
Thanks, I'll have a look over this and collect some ideas how to implement this quite easy.
