### ISSUE TITLE
[Feature request] Get to previous result when searching

### ISSUE THREAD

**Issue by TailyFair** [JasonStein/Notepads#139]
**Is your feature request related to a problem? Please describe.**
There is no way to get back to previous search result.

**Describe the solution you'd like**
While you can go forward to next search result using F3, you can't go back to previous result.

**Describe alternatives you've considered**
Maybe it would be possible to add additional shortcut that goes to previous result.

Also it would be convenient to add UI arrows in Search bar to navigate forwards and backwards.

**Comment by JasonStein** [comment]
I implemented the current Find and Replace solution in only a few hours a while back and have not pay much attention to it since then. I will come back later for this but yes, improvements are coming.

**Comment by JasonStein** [comment]
This has been implemented. Closing the thread for now.
