### ISSUE TITLE
[Feature Request]: Add option to enable line numbers on the left margin

### ISSUE THREAD

**Issue by 8times9** [JasonStein/Notepads#14]

**Comment by JasonStein** [comment]
I do agree that this feature is useful even for plain text editor. However, it is not easy to do with my current approach (implementation related). I will revisit this later.

**Comment by Duronsoft** [comment]
Adding line number to the RichEditBox is a problem, it seems can not set a fixed line height, but you can use TextRange.GetPoint() to get the position of a line.

This is my old editor, and it also uses RichEditBox,
it supports line number && code highlight
[https://github.com/Duronsoft/Just_Editor_UWP_Old](url)
You can also check this new one, it uses my custom input controls
[https://github.com/Duronsoft/Just_Editor_UWP](url)

**Comment by JasonStein** [comment]
@Duronsoft  thx for the tip, I was trying the similar way but ends up with misaligned line number and line content. It starts to getting off a little bit after few thousand lines so I completely gave up.

**Comment by Duronsoft** [comment]
@JasonStein 

![Annotation 2019-12-30 190839](https://user-images.githubusercontent.com/24861245/71579703-c155a580-2b38-11ea-845a-5aafdd7ab7ca.png)
I found a new solution to get line height, it needs Direct2D API, I guess win2d also provides something similar, maybe you could try that.

**Comment by beerisgood** [comment]
Any news? line numbers would be awesome

**Comment by Duronsoft** [comment]
@beerisgood I guess the best solution is to create a custom control, it means a lot of changes to this app, but it could get better performance.

**Comment by abersheeran** [comment]
同志，有关于行号显示的进展如何？

**Comment by JasonStein** [comment]
> 同志，有关于行号显示的进展如何？

![ezgif com-video-to-gif (4)](https://user-images.githubusercontent.com/1166162/80609405-e118af80-89ec-11ea-8838-38855306a5d1.gif)

**Comment by JasonStein** [comment]
WIP:
![ezgif com-video-to-gif-2](https://user-images.githubusercontent.com/1166162/80779266-00642980-8b20-11ea-87a1-1d97f0019a03.gif)

**Comment by JasonStein** [comment]
This feature has been implemented in Notepads v1.3.0.0.
Closing this thread for now.
