### ISSUE TITLE
[Feature request] Add spell checker

### ISSUE THREAD

**Issue by MarcAnt01** [JasonStein/Notepads#149]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to notice when I misspell a word 

**Describe the solution you'd like**
Add the native spell checker for uwp

**Describe alternatives you've considered**
Add an option, someone might not like it

**Additional context**

**Comment by JasonStein** [comment]
Will do.

**Comment by MarcAnt01** [comment]
> Will do.

If you need I have a commit from a similar Notepad uwp app

**Comment by JasonStein** [comment]
No, I am good. The only thing that kept me from enabling spell checker is that I have not figured out a best way for people to enable it. Put it in settings will make it very unaccessible. But I do not like the idea to put it in right click context menu as well.

**Comment by MarcAnt01** [comment]
You could add just the mark for misspelled words, even if it won't be the same thing

**Comment by JasonStein** [comment]
Point is I do not want to enable it by default. The system built-in marker is ugly.. And this is notepad. So it should only be turned on if user wanted.

**Comment by MarcAnt01** [comment]
So, you intend to add as an option, don't you?

**Comment by JasonStein** [comment]
Yes, there should be a button to turn it on/off for current document but I do not know where I should put it in. (Still thinking)

**Comment by motion-x86** [comment]
Hi @JasonStein is there any updates on this feature? If I understand correctly you already have it implemented just trying to figure out how to present it, may I ask if there is a way to enable it manually for now until you make your final decision on how to present the toggle?

**Comment by JasonStein** [comment]
@motion-x86  Done: https://github.com/JasonStein/Notepads/commit/c46364b75f270bf7129607b388d5ca259f79f6c0
