### ISSUE TITLE
[FEATURE REQUEST] Open Recent files from File menu

### ISSUE THREAD

**Issue by kamilmirza** [JasonStein/Notepads#15]
as per title

**Comment by JasonStein** [comment]
Will do.

**Comment by AshishMBakshi** [comment]
If you do include this, be sure to also include a "clear history" option.

**Comment by JasonStein** [comment]
@AshishMBakshi Yes, I will add on/off recent files feature in setting as well and set it to off by default (I consider open recent files to be a feature nice to have but not mandatory) . And I will provide a button to clear history in settings panel.

**Comment by JasonStein** [comment]
I will probably not going to implement this, since Win 10 has this feature by default:
![image](https://user-images.githubusercontent.com/1166162/62680438-187d9280-b96c-11e9-8b1e-74e6e190c7dc.png)

![image](https://user-images.githubusercontent.com/1166162/62680446-1d424680-b96c-11e9-8d60-f938003d7e3b.png)

**Comment by kamilmirza** [comment]
IMO majority of people does not use this recent menu of Windows 
would be fine if Recent files are added within the app

**Comment by bgiesing** [comment]
I would still like to see this in the app proper cause if you open a file directly in the app, it doesn't get added to the Windows 10 Jump List or maybe you could have the app modify that to add those (since apps can make custom Jump List items)

**Comment by JasonStein** [comment]
OK, I will do it (I mean in app recent file list feature)

**Comment by JasonStein** [comment]
This feature has been implemented in this PR: https://github.com/JasonStein/Notepads/commit/b01d43c5885f4f3fd8f160d0b08d023878ce16a6
It will be available in Notepads v1.1.0.0
