### ISSUE TITLE
Python Code Highlighting doesn't work.

### ISSUE THREAD

**Issue by saulojoab** [JasonStein/Notepads#151]
Python code highlighting doesn't work. Also, some other keywords (ex: `console.log()` JS) from other languages don't highlight.

**To Reproduce**
See screnshots.

**Expected behavior**
The keywords should be colored. They're all white.
I also tried `python` instead of `py`. Didn't work as well.

**Screenshots**
![image](https://user-images.githubusercontent.com/37988252/63203792-3469ee00-c068-11e9-8a6e-a4fedcfbddc4.png)

**Desktop**
 - OS: Windows 10 1809 17763.615

**Comment by JasonStein** [comment]
MarkdownTextBlock is the implementation I used to rendering Markdown and it uses ColorCode behind scenes for rendering Code blocks and here is the list of languages it supports out of box:

Language Support
ColorCode supports the following languages:

XML
Java
JavaScript
SQL
C#
VB.NET
ASPX (C#)
ASPX (VB.NET)
C++
PHP
PowerShell
Typescript
FSharp
