### ISSUE TITLE
Accent Color toggle text inconsistent

### ISSUE THREAD

**Issue by AshishMBakshi** [JasonStein/Notepads#16]
By default, the "accent color" toggle says "Use my Windows accent color" and is in the "off" position. That suggests the app is not using the system accent color, but it also does not allow the user to create a custom color, which is confusing.

When the toggle is moved to the "on" position, it then reads "Use a custom accent color," which makes sense but is inconsistent with user expectations for the behavior of a toggle in Windows apps.

A clearer alternative would be to just have the toggle always read "Use my Windows accent color" and simply have it be "on" by default.

**Comment by JasonStein** [comment]
I agree,
here is the fix: https://github.com/JasonStein/Notepads/commit/e8dbc5ad95a99b7efbffd43c1fb59b5ab5a655fb
And it will be available in v0.9.3.0

**Comment by JasonStein** [comment]
Close this one since it has been fixed in v0.9.3.0 and it is available in Microsoft Store as well.
