### ISSUE TITLE
Custom accent color lost when toggle switched

### ISSUE THREAD

**Issue by AshishMBakshi** [JasonStein/Notepads#17]
When the user switches the accent color option to the "Use my Windows accent color," the app changes the color picker value to the Windows accent color. But when the user switches the toggle back to a custom color, the app does not restore the custom color they had selected.

Saving / restoring the value of the custom color would allow the user to, for example, compare how a custom color looks vs. the Windows accent color.

**Comment by JasonStein** [comment]
It is nice to have but I am not buying into it yet and it is not one line fix. I will revisit later.

**Comment by soumyamahunt** [comment]
@JasonStein this is fixed in latest release and can be closed.
