### ISSUE TITLE
[Feature request] Column Selection

### ISSUE THREAD

**Issue by Frogperson** [JasonStein/Notepads#170]
**Describe the solution you'd like**
I would love the ability to highlight text in columns rather than just rows. Basically a system that works exactly like how Sublime Text handles it. 
![Gif](https://user-images.githubusercontent.com/28209992/26884862-174f2562-4ba1-11e7-8da7-c0f56baeea4b.gif)
https://www.sublimetext.com/docs/2/column_selection.html

**Additional context**
This is one of my favorite features of Sublime Text, and one of the main things (along with multiple windows/instances) that's holding me back from switching over completely.

**Comment by JasonStein** [comment]
I am actively working on multi-instances and session snapshot. It will be ready very soon.

For column selection, it is very hard to implement or maybe not even possible by working on current underline editing component (UWP RichEdit) that I am using in the app. So, I am sorry for that. Once RichEdit has this feature, it will be available in Notepads as well but there is no ETA.

**Comment by JasonStein** [comment]
Closing this thread since it is hard to implement base on current text control used by Notepads.
