### ISSUE TITLE
[Bug] Cannot execute CTRL+P or CTRL+(SHIFT)+TAB

### ISSUE THREAD

**Issue by slavdok** [JasonStein/Notepads#176]
**Describe the bug**
I cannot get CTRL+P (Markdown preview), nor CTRL+TAB (switch tabs) to work

**To Reproduce**
- Open  file
- Type some markdown text
- Press CTRL+P to show markdown preview
- Open second tab
- Press CTRL+TAB to switch tabs

**Expected behavior**
- Markdown preview opens
- Tabs are switched

**Desktop (please complete the following information):**
 - OS: [Windows 10 1903 18362.295]
 - Version [v0.9.8.0 Beta]

**Additional context**
Downloaded from Microsoft Store

**Comment by JasonStein** [comment]
What kind of file did you opened, is it .md file?

**Comment by slavdok** [comment]
Didn't realize markdown only worked in .md file.
