### ISSUE TITLE
[Feature Request] Autosave + restore unsaved text

### ISSUE THREAD

**Issue by AshishMBakshi** [JasonStein/Notepads#18]
Autosaving and restoring unsaved text (even if not it's not in a file yet) would be great.

This would be a nice improvement over Notepad where the app is used as a scratchpad for text that is temporary (and thus not saved to a file) but would still be good not to lose.

**Comment by JasonStein** [comment]
It is in my plan and I will work on it as soon as I fixed all immediate bugs, issues.

**Comment by rudrakshkarpe** [comment]
Is this feature available in recent release?
