### ISSUE TITLE
Text & Editor 

### ISSUE THREAD

**Issue by Clocker79** [JasonStein/Notepads#181]
The text settings are there in settings, but there isn't much to choose from. 

Ideally I would like to be able to freely adjust text by highlighting what sections I want to change, right click, and have an option to bold, italicize, resize, etc. This would keep the minimal aesthetic of the program and keep it simple. 
 
An alternative would be to add bold, italicize, resize to the Text & Editor settings or a toolbar of sorts. A shortcut could even be added to hide or reveal the text edit toolbar if the right clicking idea isn't possible.

I would prefer the ability to highlight selected text, right click, then be able to edit the highlighted section of text and not the whole document.

**Comment by JasonStein** [comment]
Closing this thread since I want to keep notepads as a pure plain text editor at this moment.
