### ISSUE TITLE
[Feature request] Removal Of Colored Headings

### ISSUE THREAD

**Issue by vasanthdeveloper** [JasonStein/Notepads#194]
**Is your feature request related to a problem? Please describe.**
Headings are invisible or ugly when a Dark color is set as Windows primary color.
![Annotation](https://user-images.githubusercontent.com/24322511/65128220-ae4e1800-da16-11e9-8b22-7f6bb4e0e5b0.png)

**Describe the solution you'd like**
Headings should always be white-colored just like paragraphs and other elements.

**Comment by JasonStein** [comment]
If you agree (or not agree) with @vasanthdeveloper, please give him a vote.

**Comment by JasonStein** [comment]
Closing the thread since there is no demand here by other users.
