### ISSUE TITLE
[Bug] Cannot open any file on Powershell with Notepads

### ISSUE THREAD

**Issue by validatedev** [JasonStein/Notepads#198]
**Describe the bug**
Tried to open random text files with Notepads using the usage like "notepads C:\path\to\the\file\file.txt" but instead of opening "file.txt", it greets me with the initial Untitled.txt screen.

**To Reproduce**
Try to open file with Notepads on Powershell.

**Expected behavior**
"file.txt" should be opened.

**Desktop (please complete the following information):**
 - OS: Windows 10 1903 18362.356
 - Version v0.10.2.0

**Comment by JasonStein** [comment]
I only tested with windows Command-line this time and forgot to test PowerShell..... yes, I will fix it in the next version. Thanks for catching it!

**Comment by validatedev** [comment]
Will try to open a file with cmd and give feedback about it cuz didn’t try on cmd. 

I also tried the tutorial that is wrote to configure “Open with Notepad” thing on context menu (https://www.howtogeek.com/howto/windows-vista/add-open-with-notepad-to-the-context-menu-for-all-files/) but the same behaviour with the Powershell.

**Comment by validatedev** [comment]
Yeah, I confirm that it works flawlessly with cmd, but no luck with Powershell (and with registry settings that I posted as a second comment).
