### ISSUE TITLE
Using Ctrl + Z after opening a file deletes all text inside

### ISSUE THREAD

**Issue by KrapK** [JasonStein/Notepads#2]
Opening a text file and then using Ctrl + Z erases all the content inside and can't be recovered unless you exit without saving.

**Comment by JasonStein** [comment]
Yes, you are right. Thanks for catch it. I will fix it in next release

**Comment by JasonStein** [comment]
I will add redo item in right click context menu as well as fixing "ctrl + shift + z" for this

**Comment by JasonStein** [comment]
Fixed in Preview v0.6.0.0

**Comment by JasonStein** [comment]
Reopen this one since ctrl+z should be disabled for newly opened file.

**Comment by JasonStein** [comment]
Thanks @AmionSky  for fixing this issue: https://github.com/JasonStein/Notepads/pull/46

Cheers 🎉
