### ISSUE TITLE
Unsaved icon is displayed after restoring file to original state

### ISSUE THREAD

**Issue by entdark** [JasonStein/Notepads#21]
If you edit an existing file then it displays the unsaved icon in a tab. But if you undo changes to the original state of the file then the unsaved icon is still displayed.

**Comment by yaichenbaum** [comment]
That is the current behavior found in win 32 version of notepad too.

**Comment by entdark** [comment]
> That is the current behavior found in win 32 version of notepad too.

There is not such a feature in original Notepad at all. You totally misunderstood the issue.

**Comment by JasonStein** [comment]
I do agree it is good to have but I did not implement it because it requires "compute" to check. It is some kind of waste of energy imho. I will think about it later tho.

**Comment by JasonStein** [comment]
@entdark The notepad.exe in Windows 10 1903 actually has that feature:

![Screen Shot 2019-07-05 at 10 42 20 PM](https://user-images.githubusercontent.com/1166162/60752108-2ce9fc00-9f76-11e9-86f1-daf8e2467956.png)

![Screen Shot 2019-07-05 at 10 41 51 PM](https://user-images.githubusercontent.com/1166162/60752112-36736400-9f76-11e9-8d9e-5dc7697d4122.png)

![Screen Shot 2019-07-05 at 10 42 27 PM](https://user-images.githubusercontent.com/1166162/60752115-3a06eb00-9f76-11e9-9264-50f634c31919.png)

**Comment by entdark** [comment]
It's not a feature at all. It's a bug. Their undo is a single step only, you cannot undo more than 1 steps.
Anyways it's not what a user expects. and I was talking about existing files, not new ones - I said about that in the first post.
Also the star "*" character doesn't exist in Windows 10 1809 Notepad.

**Comment by JasonStein** [comment]
I can undo more than 1 steps. I am surprised that you can only undo 1 step in your case. I think I can fix it (Remove unsaved icon) when there is nothing to undo.

**Comment by entdark** [comment]
> I can undo more than 1 steps. I am surprised that you can only undo 1 step in your case. I think I can fix it (Remove unsaved icon) when there is nothing to undo.

I guess they improved original Notepad in 1903 version. Single undo and no star sign are in 1809 and that behavior was always like that in previous versions as well.

**Comment by JasonStein** [comment]
Closing this issue since it has been fixed and shipped.
