### ISSUE TITLE
[Bug] Error Message when Launching Notepads from Windows RUN

### ISSUE THREAD

**Issue by haranobuhardo** [JasonStein/Notepads#212]
Everytime i ran Notepads from Windows Run (WIN+R), the app launched well, but there's an error message than i need to confirm everytime i launch it. Here's the error msg:

`Sorry, file "C:\Users\haran\AppData\Local\Microsoft\WindowsApps\Notepad.exe" couldn't be opened: Unspecified Error (Exception from HRESULT: 0x80004005)`

Note: Error message doesn't show up if i launch it via command prompt

I'm using Windows 10

**Comment by JasonStein** [comment]
It has been fixed in v0.10.3.0 and you should have this update real soon.

**Comment by haranobuhardo** [comment]
> It has been fixed in v0.10.3.0 and you should have this update real soon.

Great! Thanks! Love this new "notepad" so far, gonna recommend this to my friends
