### ISSUE TITLE
[Bug] Top left menu has wrong width first time it is opened

### ISSUE THREAD

**Issue by cartermnelson** [JasonStein/Notepads#213]
**Describe the bug**
When you first open the app, then open the hamburger menu at the top left, the width is too thin. The second time you open the menu, it is fixed.

**To Reproduce**
Close then reopen the app, then open the hamburger menu at the top left.

**Expected behavior**
![image](https://user-images.githubusercontent.com/30162920/65912651-62d72a80-e383-11e9-9b7b-c0000c2e926f.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/30162920/65912288-cca30480-e382-11e9-84db-ed9a59966561.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1903 18362.356

**Comment by JasonStein** [comment]
I think this is system (SDK) bug... I have encountered few times, not sure what is the root cause yet.
