### ISSUE TITLE
Enable horizontal scrolling via Shift+Scroll

### ISSUE THREAD

**Issue by stamminator** [JasonStein/Notepads#214]
**Is your feature request related to a problem? Please describe.**
When viewing a document without word wrapping on, there is no way to scroll the window horizontally.

**Describe the solution you'd like**
While holding the `Shift` key, scrolling down with the mouse wheel should go to the right, and scrolling down with the mouse wheel should go left.

**Describe alternatives you've considered**
Keyboard users without a mouse _may_ want a way to scroll the window without having to move the caret through text, but (1) I may be wrong, (2) I can't think of other applications that allow this to occur while the focus is inside a text area, and (3) I can't think of an intuitive way to do such a thing.

**Additional context**
Though this is a pretty standard feature in web browsers and most IDEs/text editors, it was not present in notepad.exe, so if selected for implementation, it should probably be prioritized below any parity features.

**Comment by JasonStein** [comment]
100% agree. I Will do it and it should be part of next release.

**Comment by JasonStein** [comment]
Actually I am now having trouble implementing this feature... here is why:
![image](https://user-images.githubusercontent.com/1166162/66107011-16067600-e574-11e9-8633-3830bd9e45cf.png)

**Comment by ratatoeey** [comment]
today I learned that 'horizontal scrolling via Shift+Scroll' is a thing. 

my reaction is good to know, someone should store it somewhere. until I figure out when I might need it. 

as I just turn word wrap on, and the line numbers are enabled in editors, to keep it readable in weirdly formatted codebases. and just use mouse wheel to scroll vertically. forgot I use vscode. though nano, micro and notepad++ are also there.

---
 regards  ratatoeey

**Comment by JasonStein** [comment]
I have also added "mouse middle button + wheel" shortcut to do horizontal scrolling in addition to ctrl+shift+wheel: https://github.com/JasonStein/Notepads/commit/dcdb82537f0f716124bcf8cd4f21e4ff8fd37f60
It will be available in v1.1.8.0. Closing this thread for now.
