### ISSUE TITLE
[Feature request] cannot open link in app's about page

### ISSUE THREAD

**Issue by ghost** [JasonStein/Notepads#219]
**Is your feature request related to a problem? Please describe.**
Ex. I'm always frustrated when I can't copy the url from the app's about page or open them in a non-default browser.

**Describe the solution you'd like**
allowing the urls to be copied would be simplest solution. I guess.

**Describe alternatives you've considered**
Open with chrome or firefox  option that opens the page in the correct browser.

triggering a menu in the OS that ask user to select the browser. Assuming the OS can detect the browser

**Additional context**
None.

 - OS: Windows 10 1903
 - Version 0.10.3.0
 - Chrome - 77.0 32-bit installed by "scoop"

**to find the about page**
Open notepads app. Go to Menu, click Settings then, click on about page(the icon at the bottom with an i )

my user account is not admin, so can't change some settings. there is a admin account. and "transparency effects" are turned off.

**Comment by trip23app** [comment]
tags: ?

**Comment by trip23app** [comment]
connected to comment:  https://github.com/JasonStein/Notepads/issues/160#issuecomment-524105180

>added "Changelog" link in App settings

it would be nice if it could be copied.

**Comment by JasonStein** [comment]
I don't plan to add support for selecting text in about page since I feel it not necessary. About page is indented for read purposes and I think using default browser to open the link make sense for most of the cases and anyway this is just some information about Notepads at the end of the day.
