### ISSUE TITLE
no need to prompt save unsaved changes when the string is empty

### ISSUE THREAD

**Issue by Hanzalah-Adalan** [JasonStein/Notepads#22]
something user type in something and then they change their mind, they delete everything (the text), but when they wanna close the app, they still got the prompt when there's nothing actually to be saved

**Comment by JasonStein** [comment]
Duplicate: https://github.com/JasonStein/Notepads/issues/21

**Comment by Hanzalah-Adalan** [comment]
Owh I see,, sorry >.<
