### ISSUE TITLE
[Bug] markdown file is not recognized as markdown in some cases

### ISSUE THREAD

**Issue by ghost** [JasonStein/Notepads#221]
**Describe the bug**
opening `rat.markdown` works, but the markdown preview feature doesn't work.

usually files show up with a different icon in  'file explorer' when notepads is set to open them.
this doesn't work for markdown files that have extension `.md`.

**To Reproduce**
Steps to reproduce the behavior.

there is a markdown file rat.markdown

1. open it using notepads.
2. it opens successfully
3. but, markdown preview feature doesn't work.

**Expected behavior**
markdown preview feature works. as the file is valid markdown in other editors.

files with these extensions are recognized as markdown
```
mdown
markdown
md
```

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS:  Windows 10 1903
 - Version 0.10.3.0

**Additional context**

this answer revised my information about markdown file extensions  https://superuser.com/questions/249436/file-extension-for-markdown-files/285878#285878

its nice to support `.markdown` in addition to the already supported `.md` for markdown previews. unless notepads adopts at least the ones that github recognises.

`.md` is also the extension for https://gcc.gnu.org/onlinedocs/gcc-9.2.0/gccint/Machine-Desc.html
I haven't seen any such files in a long time, and could not find it on the first page on google results for .

vscode does support it so I kind of have a bunch of  markdown files that can't be previewed only in Notepads.

**Comment by trip23app** [comment]
<hr>

@

**Comment by JasonStein** [comment]
OK, I will add .markdown in addition to .md
