### ISSUE TITLE
[Feature request] Add the auto-save feature

### ISSUE THREAD

**Issue by itsusmanmirza** [JasonStein/Notepads#222]
Could you please add the auto-save feature like saving a file every few seconds I usually use CTRL+S to save it but still sometimes when in a hurry, I forget to save it.

**Comment by JasonStein** [comment]
You mean auto-save on top of session snapshot? I thought session snapshot is good enough and it is user's responsibility to save the file explicitly. It makes more sense, especially for the cases that your file has been modified outside.

**Comment by itsusmanmirza** [comment]
Not on top of session snapshot but as a separate feature like saving files every 5 seconds. The more options you provide the better flexibility is there for the user.

**Comment by ratatoeey** [comment]
> sometimes when in a hurry, I forget to save it.

sometimes when in a hurry, I forget to disable auto-save in vscode and chaos ensues. as i keep it disabled by default.

**Comment by AkazaRenn** [comment]
I would like auto save as well, for me it is not always a bit deal to keep the stored file modified since I can use ctrl+z to roll back my changes. I keep auto save on my VS Code on all the time and it will save after I stop typing for 100 ms. Would be glad to see that on Notepads.

**Comment by beerisgood** [comment]
Doesn't would this decrease the performance?

For me it would be enough if the program ask at closing the tab/ program if it should save the file when changes are detected

**Comment by JasonStein** [comment]
I don't plan to add this feature since:
1.  Notepads supports multiple tabs.
2.  Notepads supports session snapshot.

Implementing auto-save on top of above two will create confusion and I feel unnecessary.
