### ISSUE TITLE
RTL/LTR Button

### ISSUE THREAD

**Issue by movahhedi** [JasonStein/Notepads#224]
Hello!
I'm using [Notepads](https://github.com/JasonStein/Notepads) as my main notepad app since the past month.
I suggest that you put a RTL/LTR button in the app menu (like the button in the right-click context menu in Windows' Notepad).
Thanks for the great work @JasonStein !

**Comment by JasonStein** [comment]
I am thinking about the same (to add it in the right-click menu) but I only want to make it appear when user's locale is RTL. That is something I need to implement in the first place. But yes, I will do it.

**Comment by JasonStein** [comment]
This feature has been properly implemented: https://github.com/JasonStein/Notepads/commit/d1cf5706906ac8383f974110a4c80fa60c87b69e

![image](https://user-images.githubusercontent.com/1166162/77906090-33bf4a00-723c-11ea-90f1-71bd335de51e.png)
