### ISSUE TITLE
[Feature request] Use Latest WinUI Tab View 

### ISSUE THREAD

**Issue by BenConstable9** [JasonStein/Notepads#226]
User Interface request - is it possible to switch to the latest WinUI TabView for the tabs? The latest Windows Tabbed Apps such as Edge Beta and Terminal use a different style tabs to the ones within Notepads.

More details on TabView here: [https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/tab-view](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/tab-view)

**Comment by JasonStein** [comment]
It does not fit with current design, and the implementation is not flexible enough to switch to. I am sticking with my current approach and I will use it once it gets mature and once I change the design (to use rounded corner). But no ETA and no plan yet.

**Comment by ratatoeey** [comment]
when will I use notepads as a simple text editor
>  I will use it once it gets mature

and can equal notepad.exe in features. baby steps.
----

regards ratatoeey

**Comment by JasonStein** [comment]
I will use WinUI TabView once it gets reimplemented using ItemRepeater and only if it is looking better when what we already have. Closing this thread for now.
