### ISSUE TITLE
[Bug] Letters tremble when selecting some content.

### ISSUE THREAD

**Issue by zhaobenx** [JasonStein/Notepads#229]
**Describe the bug**
When selecting some content, some letters just changed to others. Too fast to see what they have been.

**To Reproduce**
Just open this file and select some content.
[example.txt](https://github.com/JasonStein/Notepads/files/3774391/example.txt)

**Screenshots**
As shown in this gif.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/23143530/67613617-87090a00-f77d-11e9-9904-020a5a06427f.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10 1903 18362.418
 - Version [v1.0.0.0]

**Comment by JasonStein** [comment]
I am not able to repro the bug you have seen on my machine. Let me try use another one which has Chinese language pack installed. It might has something to do with locale but I am not sure. So far, it looks like a system built-in rich edit bug.

**Comment by JasonStein** [comment]
I think this might related to system/windows graphics stack rendering issues. Closing this thread for now,
