### ISSUE TITLE
Problems with cyrillic

### ISSUE THREAD

**Issue by soundgarddden** [JasonStein/Notepads#23]
I like your work very much. Please teach her how to work with Russian characters. Thank!

![image](https://user-images.githubusercontent.com/52575611/60730499-fa2c0d80-9f4d-11e9-8806-c0fbc1dffc72.png)

**Comment by JasonStein** [comment]
Hi, can you make sure it opens correctly in original notepad.exe? And then you can send this file over to me, just mail it to NotepadsApp@outlook.com

**Comment by soundgarddden** [comment]
Hi, unfortunately, I have already deleted this file. While I do not observe problems with others. If there are still new examples, I'll send it to the post office. Thank!
