### ISSUE TITLE
[Bug] Editing and saving an existing file cause "save as" dialog on CTRL+S

### ISSUE THREAD

**Issue by worki2k1** [JasonStein/Notepads#230]
**Describe the bug**
If i open an existing text file by drag and drop it from Explorer into open Notepads App, i'll get an "save as" Dialog if i hit CTRL+S to save it.

**To Reproduce**
1. Create a new text file some where (for example in one drive)
2. Start Notepads App
3. Drag and drop the created file from Windows Explorer into the app to open the file.
4. Do some random changes
5. Press CTRL+S to save the file

**Expected behavior**
The file should be save without opening "save as" 

**Desktop:**
 - OS: Windows 10 1903 18362.418
 - Version v1.0.0.0

**Comment by JasonStein** [comment]
![image](https://user-images.githubusercontent.com/1166162/67732759-a55b4980-f9b9-11e9-8620-657d8519d737.png)

You can also take a look at here:
https://stackoverflow.com/questions/41846811/dragdrop-file-attribute-is-readonly

**Comment by worki2k1** [comment]
Ohh didn't read that. Thanks for your answer.
