### ISSUE TITLE
questions about 'How to Build and Run Notepads from source' section in CONTRIBUTING.md

### ISSUE THREAD

**Issue by ghost** [JasonStein/Notepads#231]
from https://github.com/JasonStein/Notepads/blob/master/CONTRIBUTING.md

>Make sure your machine is running on Windows 10 1903+.

what do you mean by 1903+?

----

regards ratatoeey

**Comment by ratatoeey** [comment]
>Make sure you have Visual Studio 2019 16.2+ installed.

sorry, can't do that. can it be done with smaller download size  and then adding other components?

>Make sure you have "Universal Windows Platform development" component installed for Visual Studio.

another issue that stumps me. can't find this as a separate download.


>Make sure you installed "Windows 10 SDK (10.0.17763.0 + 10.0.18362.0)" as well.

assuming this means both need to be installed. for old sdk https://developer.microsoft.com/windows/downloads/sdk-archive and for latest sdk https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk


---

best regards ratatoeey

**Comment by JasonStein** [comment]
10.0.18362.0 is good enough for now.

**Comment by JasonStein** [comment]
1903+ is the windows 10 version. You can get your current windows version by running "win+r" and type "winver" to get the version of your Windows 10.
