### ISSUE TITLE
[Feature request] Close app when when last tab is being closed

### ISSUE THREAD

**Issue by massijay** [JasonStein/Notepads#232]
**Is your feature request related to a problem? Please describe.**
It would be useful to close the app when the last tab is being closed, which is the default behavior of every web browser.

**Describe the solution you'd like**
Add a toggle in settings to enable this feature

**Comment by JasonStein** [comment]
It used to be like that, but I changed it since exiting the app programmatically is not recommended by Microsoft. On top of that, Windows will not remember the last opening window location and size if app exited programmatically without the user hitting on the exit button.

**Comment by ratatoeey** [comment]
also, that is more like a bug. always I get frustrated with web browsers closing when the last tab is closed. affected web browsers -> Edge (default in Windows 10), Firefox, Chrome, Chromium.

_I will write a 5000 word rant about it some day to break my previous record of 500 word rant on same topic._

----

regards ratatoeey
