### ISSUE TITLE
[Bug] Shift+Click to select a block of text doesn't always work

### ISSUE THREAD

**Issue by alejandro5042** [JasonStein/Notepads#233]
**Describe the bug**
When selecting text with Shift+Click, unless you click on the text, it doesn't select.

**To Reproduce**
Open a text file. Click on the beginning of a paragraph. Hold shift and click on a blank line somewhere else. Nothing will be selected.

**Expected behavior**
The range to be selected.

**Screenshots**
Not needed at this time.

**Desktop (please complete the following information):**
 - OS: Windows 10 19008.1

**Additional context**
N/A

**Comment by JasonStein** [comment]
This is only working if the end of the selection is not empty line or empty space so I would say this is a behavior inherited from RichEditBox. Closing this issue now since most of the cases it works.
