### ISSUE TITLE
[Bug] Shift-F3 should go to the previous search hit

### ISSUE THREAD

**Issue by alejandro5042** [JasonStein/Notepads#237]
**Describe the bug**
Right now Shift+F3 does some casing transformations. This is unusual and non-standard.

**To Reproduce**
Search some text and hit Shift+F3.

**Expected behavior**
Go to the previous hit.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
You can move the casing feature to another F-key. That's OK with me.

**Comment by JasonStein** [comment]
This has been implemented. Closing the thread for now.

**Comment by alejandro5042** [comment]
Awesome! thank you!
