### ISSUE TITLE
[Bug] Markdown preview does not ignore HTML comments

### ISSUE THREAD

**Issue by alejandro5042** [JasonStein/Notepads#238]
**Describe the bug**
HTML comments in markdown should not render.

**To Reproduce**
Add HTML comments in a markdown document and see that text in the previous.

**Expected behavior**
Text is hidden inside a comment.

**Screenshots**
N/A.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
N/A

**Comment by Fromax** [comment]
It's not only that. The problem is rather that Notepads MD preview doesn't parse HTML *at all*.
And according to the original Markdown spec, HTML is allowed in Markdown:  
> For any markup that is not covered by Markdown’s syntax, you simply use HTML itself. There’s no need to preface it or delimit it to indicate that you’re switching from Markdown to HTML; you just use the tags.  
>   &nbsp;
> If you want, you can even use HTML tags instead of Markdown formatting; e.g. if you’d prefer to use HTML `<a>` or `<img>` tags instead of Markdown’s link or image syntax, go right ahead.

**Comment by JasonStein** [comment]
Not supported by the underline framework/library I use (https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/markdowntextblock).
