### ISSUE TITLE
[Feature request] Highlight current line

### ISSUE THREAD

**Issue by swiatlyk** [JasonStein/Notepads#24]
Please add highlight current line. Maybe some grey color of the line.

**Comment by JasonStein** [comment]
It is nice to have but it is a low piority work item for now.

**Comment by swiatlyk** [comment]
Yes I understand that, but please keep it in mind.

**Comment by JasonStein** [comment]
@swiatlyk 
This feature has been implemented by @soumyamahunt in this PR: https://github.com/JasonStein/Notepads/commit/71f35c0e78e81770dc58dc66ecd4dffac6dcca81
It will be available in Notepads v1.1.0.0
