### ISSUE TITLE
[Feature request] Regex functionality for find and replace

### ISSUE THREAD

**Issue by ealap** [JasonStein/Notepads#240]
Regex functionality for find and replace, preferably PCRE2.

**Comment by ratatoeey** [comment]
is library for PCRE2 secure?

also, this isn't that kind of editor. its meant to be a notepad replacement but within the limits of the chosen platform. So, better than notepad and worse than notepad; in different areas.

----

regards ratatoeey

**Comment by JasonStein** [comment]
Regex search is implemented by @soumyamahunt in this PR: https://github.com/JasonStein/Notepads/commit/5b2c7ed88553f690089bb12b345b18ba5ea03566
It will be available in Notepads v1.1.0.0
