### ISSUE TITLE
[Feature request] Print feature

### ISSUE THREAD

**Issue by SpringsTS** [JasonStein/Notepads#245]
Hello,

At first thank you for your Notepads that would deserve to be the default integrated notepad in Windows - Simple, working, fluent interface!

For it to be perfect, I would suggest to add the last notepad.exe feature that's still missing in Notepads: _Print_ (and Print Preview).

I noticed I couldn't print my text without copying it in standard Notepad, I sometimes needs this feature at work.

Thank you in advance if you can look into this!

(Last point but totally out of topic: I noticed two problems with the French (France) translation, where can I report them? Thanks in advance).

**Comment by JasonStein** [comment]
Print feature is hard to do, I am still looking for the solution to use right away instead of re-inventing the wheel on my own.

**Comment by SpringsTS** [comment]
Thank you for the answer.

**Comment by JasonStein** [comment]
It has been implemented by @soumyamahunt  in this PR: https://github.com/JasonStein/Notepads/commit/c912af3d8235b435cdbbc9ce59e99155ed844a48
It will be available in Notepads v1.1.0.0
