### ISSUE TITLE
[Feature request] Add chocolatey package

### ISSUE THREAD

**Issue by Nisgrak** [JasonStein/Notepads#246]
**Describe the solution you'd like**
Can install and update Notepads with chocolatey features

**Additional context**
https://chocolatey.org/
https://chocolatey.org/docs/create-packages

**Comment by JasonStein** [comment]
Not in my plan. Windows(Microsoft) Store is good enough for now.

**Comment by ebdonato** [comment]
I don't know how (I'm too noob), but looks like it is possible to [automate Chocolaty Package Creation](https://www.dolthub.com/blog/2021-10-13-how-to-publish-winget-chocolatey-packages-with-github-actions/).

Notepads is the only app I am currently getting from Windows Store, the others, I am getting with Chocolatey,

**Comment by JamesDAdams** [comment]
up
