### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ayoubkhan558** [JasonStein/Notepads#247]
**Describe the bug**
I was unable to run the source code in visual studio. 
Please How to run Source code in visual studio. How to setup envoirment.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1809 17763.593]
 - Version [e.g. v0.9.3.0]

**Comment by JasonStein** [comment]
https://github.com/JasonStein/Notepads/blob/master/CONTRIBUTING.md
