### ISSUE TITLE
[Feature request] Reload editor when file has been modified elsewhere

### ISSUE THREAD

**Issue by frousselet** [JasonStein/Notepads#25]
**Is your feature request related to a problem? Please describe.**
When a file has been modified with another editor (or a program output), reload the text editor. It is very useful for log files.

**Describe the solution you'd like**
Add real time text editor refresh.

**Describe alternatives you've considered**
Add a prompt to reload the text editor as soon as it has been modified (Reload: Yes/No).

**Comment by JasonStein** [comment]
It is a little bit tricky on listening file events for UWP app, not saying it is not doable but I do need time to learn and see how it can be done nicely. I will come back later for this one.

**Comment by JasonStein** [comment]
This feature has been implemented: 

![image](https://user-images.githubusercontent.com/1166162/62680593-6d210d80-b96c-11e9-87c7-0c79e9da878b.png)
![image](https://user-images.githubusercontent.com/1166162/62680601-7316ee80-b96c-11e9-83aa-bf250c0b2ade.png)
![image](https://user-images.githubusercontent.com/1166162/62680625-80cc7400-b96c-11e9-9ce6-9ff48e42b935.png)
![image](https://user-images.githubusercontent.com/1166162/62680645-8d50cc80-b96c-11e9-892b-fbee7efe08b4.png)

**Comment by JasonStein** [comment]
Closing this issue since it has been deployed.
