### ISSUE TITLE
[Feature request] Bullet Points

### ISSUE THREAD

**Issue by unclephil69** [JasonStein/Notepads#251]
Notepad and Notepad++ can make bullet point by pressing Alt-7 (number pad). Be useful for Notepads to have the same capability.

**Comment by yaichenbaum** [comment]
Try Ctrl + Shift + L.

**Comment by unclephil69** [comment]
Thanks. Any other non-notepad combinations I should know? It might be nice to have Alt+7, Alt+9 too for parity.

 
 

Sent: Sunday, November 24, 2019 at 3:21 PM

**Comment by JasonStein** [comment]
Notepads is a plain text editor, please use markdown if you need formatted text.
