### ISSUE TITLE
[Bug] Clicking and dragging to select text while Notepads is inactive doesn't work

### ISSUE THREAD

**Issue by PkChris** [JasonStein/Notepads#257]
**Describe the bug**
Clicking and dragging to select text while Notepads is inactive doesn't work.

**To Reproduce**
Open Notepads and type something. Click outside the window. Click inside window and drag to select text.

**Expected behavior**
The text is selected.

**Screenshots**
https://share.vidyard.com/watch/8th3h9QKZYyaurU5i4Ayek

**Desktop (please complete the following information):**
OS: Windows 10 18363.476

**Comment by yaichenbaum** [comment]
There is actually an issue on the Win UI repository for this, https://github.com/microsoft/microsoft-ui-xaml/issues/1555.
