### ISSUE TITLE
Add more file icons

### ISSUE THREAD

**Issue by mah-qurashy** [JasonStein/Notepads#258]
now only txt files has customized icon, would be nice if it had custom icons for ini, xml, etc..
or at least having a generic file icon (white paper) for all text supported, instead of showing the app icon
![Annotation 2019-11-30 145626](https://user-images.githubusercontent.com/20822445/69900925-3f7c2c00-1382-11ea-9ae5-77f0371d16b8.png)

**Comment by United600** [comment]
Not entirely true, Markdown (.md) also possesses an icon ;)

**Comment by JasonStein** [comment]
I will change icons once I have it for all supported types. I do not have a designer now and do not have time and energy on icons yet.

**Comment by mah-qurashy** [comment]
@JasonStein I do design, I will give them a try

**Comment by JasonStein** [comment]
@mah-qurashy  Thanks for creating more icons. I am going t close this thread for now since we are good. They will be available in Notepads v1.1.0.0.
