### ISSUE TITLE
[Feature request] recent items | extension filters | close window with last tab (optional)

### ISSUE THREAD

**Issue by qwerty-1-2-3-4-5** [JasonStein/Notepads#259]
The app looks very promising but the first two features -mentioned in the title- are what break the deal for me. 
I have hundreds of notes, all opened in order and placed in different folders. At the moment I can't recreate my old list in the recent items section (taskbar) since there isn't one. Also having no extension filters in the browse window makes it even more time-consuming to look up specific types. 
The last feature could be toggled in the setting since many would prefer to disable it. Nonetheless, it's a time-saving feature.

**Comment by JasonStein** [comment]
"Recent items" is in my plan, it will come soon. I will consider your idea of making "last tab close to exit the app" as an option.

**Comment by qwerty-1-2-3-4-5** [comment]
> "Recent items" is in my plan, it will come soon. I will consider your idea of making "last tab close to exit the app" as an option.

I found a better app days after posted this. Anyway, nothing about extension filters (in the browse window)?

**Comment by JasonStein** [comment]
It will be added in v1.0.3.0:
https://github.com/JasonStein/Notepads/commit/f3eaf6110577c0a88fe30337e81d22da55d5c444
