### ISSUE TITLE
[Bug] Cannot go back with esc in a screen

### ISSUE THREAD

**Issue by MarcAnt01** [JasonStein/Notepads#260]
**Describe the bug**

I cannot go back in the section in the screenshot using esc

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/43090263/70549766-0ce9e480-1b75-11ea-83b1-93a9d2713328.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1809 17763.593]
 - Version [e.g. v0.9.3.0]
Windows 10 Home 1909

**Additional context**

**Comment by JasonStein** [comment]
Will do (esc to close settings panel).

**Comment by JasonStein** [comment]
Esc actually works for me, can you test?

**Comment by MarcAnt01** [comment]
@JasonStein it doesn't here with latest Store version

**Comment by MarcAnt01** [comment]
I have noticed that the bug seem to happen just the first time, so just open settings and try to go back without performing any other action

**Comment by MarcAnt01** [comment]
@JasonStein can you reopen this issue?

**Comment by JasonStein** [comment]
Fixed: https://github.com/JasonStein/Notepads/commit/ae7a508ca89d7085bd28b68cab48580120b37c8b

Should be fixed in with v1.2.1.0

**Comment by MarcAnt01** [comment]
> Fixed: https://github.com/JasonStein/Notepads/commit/ae7a508ca89d7085bd28b68cab48580120b37c8b
> 
> 
> 
> Should be fixed in with v1.2.1.0

Thanks, I have just got 1.2.0.0 update, will wait and let you know😁👍

**Comment by MarcAnt01** [comment]
I can confirm, it's fixed
