### ISSUE TITLE
CTRL+num should switch to specified tab

### ISSUE THREAD

**Issue by patrickmcbean** [JasonStein/Notepads#264]
When multiple tabs are open, it would be useful to be able to use keyboard shortcuts to navigate between different tabs. Many other programs use ctrl+num to navigate between them, so that might be the best idea

**Comment by JasonStein** [comment]
Sounds good to me, will add Ctrl + 0 - 9 as default.

**Comment by JasonStein** [comment]
It has been implemented in this commit: https://github.com/JasonStein/Notepads/commit/691e7bd3ddfa6da3f46d88c89fd47a4c3e903aa9
It will be available in Notepads v1.1.0.0
