### ISSUE TITLE
[Feature request] Allow directly launching multiple independent instances (particularly for multiple desktops)

### ISSUE THREAD

**Issue by patrickmcbean** [JasonStein/Notepads#269]
**Is your feature request related to a problem? Please describe.**
I often use multiple desktops, and if you click notepads it will switch desktop to the active one.

**Describe the solution you'd like**
If launching the exe, create a new instance (rather than switching to the current one)

**Describe alternatives you've considered**
It's possible to create a new (shadow) instance by creating a new tab and dragging it off the window.

**Comment by JasonStein** [comment]
It is already possible to create a new (shadow) instance by creating a "new" tab and dragging it off the window.

**Comment by patrickmcbean** [comment]
I'm aware of that, but when running multiple desktops, running the exe will just bring you back to the currently opened instance instead of launching a new one

**Comment by JasonStein** [comment]
Unfortunately, the underline app framework that I am using (UWP) cannot detect which monitor the app window is currently located. This is one of the limitations of UWP.

**Comment by patrickmcbean** [comment]
Ah ok that's a shame.

Is it possible to have a new window open whenever the exe is launched? It could even be an option in the settings in case people prefer new tabs.

**Comment by JasonStein** [comment]
https://github.com/JasonStein/Notepads/commit/bb0770f875248a0712883db345c4e66560dcd949
![image](https://user-images.githubusercontent.com/1166162/71808380-8369ed00-3022-11ea-8554-e680e4a24e90.png)

You should be able to see it in v1.0.3.0

**Comment by patrickmcbean** [comment]
That's fantastic! Thanks a million

Now ready to use this as my daily driver :)

**Comment by JasonStein** [comment]
available
