### ISSUE TITLE
[Feature request] Ask to save instead of discard changes

### ISSUE THREAD

**Issue by silencesys** [JasonStein/Notepads#27]
**Is your feature request related to a problem? Please describe.**
When you're about to close the editor and made some changes in the file. The editor will ask you if you want discard these changes. I think it might be confusing as usually are application asking you if you want to save the changes.

**Describe the solution you'd like**
Thus I propose, it would be much better if there would be a question to _save and close_ instead of _discard and close_.

**Comment by JasonStein** [comment]
I agree, I am working on "Save All" feature, once that is done I can simply add it as an additional button in app close dialog (Save reminder).

**Comment by JasonStein** [comment]
Implemented:
https://github.com/JasonStein/Notepads/commit/d4562e4e352a6759bd959dc7a82a91d7b6fcc3d4
