### ISSUE TITLE
"lightweight"

### ISSUE THREAD

**Issue by cup** [JasonStein/Notepads#270]
I see here:

https://github.com/JasonStein/Notepads

> A modern, lightweight text editor with a minimalist design.

however this is confusing, as if you go here:

https://github.com/JasonStein/Notepads/releases

the download is 115 MB. Compare with another project, which is 1 MB:

https://github.com/zufuliu/notepad2/releases

**Comment by JasonStein** [comment]
"lightweight" never mean file size is small... Btw, 115 MB contains three builds: x84, amd64 and arm32

**Comment by JasonStein** [comment]
This is the memory usage when Notepads is minimized:
![image](https://user-images.githubusercontent.com/1166162/71637891-1a8b0b00-2c05-11ea-8180-94985fd0a487.png)

**Comment by JasonStein** [comment]
![image](https://user-images.githubusercontent.com/1166162/71637898-53c37b00-2c05-11ea-8465-e400c2f93c5c.png)

**Comment by cup** [comment]
@JasonStein hm, that is impressive! You made me reconsider. However the ZIP size is still quite high. Would you consider breaking it into separate files for each architecture or similar?

**Comment by JasonStein** [comment]
> @JasonStein hm, that is impressive! You made me reconsider. However the ZIP size is still quite high. Would you consider breaking it into separate files for each architecture or similar?

You do not have to download and install from github, you can go grab here: https://www.microsoft.com/store/apps/9nhl4nsc67wm

**Comment by cup** [comment]
@JasonStein thanks, but Microsoft site does not allow anonymous download...

**Comment by JasonStein** [comment]
> @JasonStein thanks, but Microsoft site does not allow anonymous download...

I will separate the builds into three binary in the future release.

**Comment by cup** [comment]
I see the ZIP contains:

~~~
Notepads_1.0.2.0\Notepads_1.0.2.0_x86_x64_arm.msixbundle
~~~

which contains:

~~~
10198043 Notepads_1.0.2.0_x64.msix
~~~

So in reality its only 10 MB. I think it would be much better distributed in
this fashion or similar. Thanks for your comments!

**Comment by AkazaRenn** [comment]
> but Microsoft site does not allow anonymous download...

@cup AFAIK it does, every time I want to download an app I just click install and choose not to login, it will still start downloading.

**Comment by JasonStein** [comment]
v1.0.3.0 is available.
