### ISSUE TITLE
[Bug] On dark mode the window stays transparent when it's not active anymore.

### ISSUE THREAD

**Issue by QubitTooLate** [JasonStein/Notepads#277]

**Comment by JasonStein** [comment]
This is intended for better visual experience.

**Comment by yaichenbaum** [comment]
Windows is actually designed so that acrylic turns off as soon as a Windows is not focused, the idea is that only one app has the affect at a time.

**Comment by JasonStein** [comment]
> Windows is actually designed so that acrylic turns off as soon as a Windows is not focused, the idea is that only one app has the affect at a time.

I assume they do it for energy saving purposes
.

**Comment by yaichenbaum** [comment]
@JasonStein I spoke to some engineers and it sounded more that it was for design purposes rather then energy, for example if it were just energy then desktop devices would probably have it enabled all the time.

**Comment by JasonStein** [comment]
Closing this thread since I do not have plan to change it back.
