### ISSUE TITLE
[Bug] Alt+Tab resets cursor position

### ISSUE THREAD

**Issue by entdark** [JasonStein/Notepads#279]
**Describe the bug**
Each time I switch window focus to Notepads by using Alt+Tab keys combination the cursor jumps to the beginning of text.

**Expected behavior**
Don't reset cursor position after switching to Notepads by using Alt+Tab keys combination.

**Desktop (please complete the following information):**
 - OS: Windows 10 1903
 - Version: the latest on this moment
(I will edit those if necessarily once I get home.)

**Additional context**
It's very annoying as is and is even more annoying when your document is scrolled to the end and then the scroll position gets reset to the beginning.

**Comment by JasonStein** [comment]
This annoys me as well... It is something out of my control and every time I assign focus to RichEditBox, it behaves like that....

**Comment by JasonStein** [comment]
I can actually try remember the scroll position and reset it after alt+tab. Not sure if it is possible. If it is I will do it.

**Comment by JasonStein** [comment]
I found a work around "hack" to fix this issue: https://github.com/JasonStein/Notepads/issues/279 +  https://github.com/JasonStein/Notepads/issues/280

It will be available in v1.1.6.0
