### ISSUE TITLE
[Feature request] Right to left view when region is set to Persian (Iran)

### ISSUE THREAD

**Issue by pourmand1376** [JasonStein/Notepads#28]
Hello. 
When I set region to Persian (Iran), Everything in the app is set RTL even English files. Is it possible to make it optional? 
It's a little bit hard to read english files in RTL mode.

Thanks

**Comment by JasonStein** [comment]
RTL supports will be added in next update. Basically you can use ctrl+L/R to switch between LTR or RTL. I disabled it in previous build and forgot to remove it.

**Comment by pourmand1376** [comment]
Thanks.

**Comment by JasonStein** [comment]
Enabled Ctrl+L/R flow direction shortcut: https://github.com/JasonStein/Notepads/commit/fa6ab39a73530e72bd23840922adb999980728fe

For LTR:
Basically, select all (ctrl+A) and then type (ctrl+L)

For RTL:
Basically, select all (ctrl+A) and then type (ctrl+R)

It will be available in v0.9.4.0
