### ISSUE TITLE
[Bug] White accent colour causes text selection to be solid white

### ISSUE THREAD

**Issue by DorsalAxe** [JasonStein/Notepads#280]
This one is pretty self-explanatory. Set the accent colour to white and try selecting text. The selection will be solid strip of white and completely unreadable. This occurs in both the Light and Dark themes.

The preferred behaviour would be to have the text become dark to contrast against the light background of the selection. This would probably also make some other light accent colour choices (e.g. pastels) more practical to use as well,

**Comment by JasonStein** [comment]
I would not consider it as a bug but rather a choice. Users have full control of what color they want to use and if you think the color you choose make your app experience bad, you should consider another one. To prevent users from picking similar color or close color is doable and easy but I do not think it is a necessary.
