### ISSUE TITLE
[Bug] Window size has a minimum

### ISSUE THREAD

**Issue by TheV360** [JasonStein/Notepads#281]
**Describe the bug**
Notepads does not allow resizing to a very small window.

**To Reproduce**
1. Try resizing the window so that it occupies less than 1/10th of the screen.

**Expected behavior**
Notepads to allow extremely small window sizes, like Windows Notepad allows.

**Screenshots**
![Notepads' minimum window size vs Windows Notepad](https://user-images.githubusercontent.com/25177071/72693697-f897f080-3aff-11ea-9f4c-e7b5be09baf2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1909 18363.535
 - Version: v1.0.3.0

**Comment by JasonStein** [comment]
https://stackoverflow.com/questions/43553264/min-window-size-in-uwp

**Comment by TheV360** [comment]
Whoops, never noticed the "Compact Overlay" option.
