### ISSUE TITLE
Arch Linux and Ohter gnu/linux distro 

### ISSUE THREAD

**Issue by APakrohk** [JasonStein/Notepads#288]
How can I install Manjaro and Arch?
https://wiki.archlinux.org/index.php/creating_packages

**Comment by JasonStein** [comment]
This is a Windows app and built on top of Windows UWP stack. It won't work on any linux distro.

**Comment by xdrie** [comment]
FWIW, this might be doable: https://platform.uno/docs/articles/howto-migrate-existing-code.html

**Comment by JasonStein** [comment]
> FWIW, this might be doable: [platform.uno/docs/articles/howto-migrate-existing-code.html](https://platform.uno/docs/articles/howto-migrate-existing-code.html)

AFAIK, the feature set of UNO is not sufficient at all to match the same feature level as Notepads as it is right now.

**Comment by xdrie** [comment]
Fair enough. Hopefully one day we'll be able to do a community port.

Off the top of your head, what's missing?

**Comment by JasonStein** [comment]
The rich edit (text) control UNO implements only has very few APIs to work with. Also, you will not have the Acrylic effect under Linux as well. Basically, everything is missing for a working port of notepads.
