### ISSUE TITLE
Respect exact file encoding

### ISSUE THREAD

**Issue by AmionSky** [JasonStein/Notepads#29]
Today I had a problem where I edited a config file of an application but after saving, that application failed to load the config file. After some investigation it turns out the problem was with encoding.

Originally the config file was in _UTF-8_ encoding but after editing it with Notepads it saved it in _UTF-8-BOM_.

It would be nice if Notepads would not change the encoding of an existing file.

**Comment by JasonStein** [comment]
This is something that I need to fix right away. I almost forget it, thanks for the reminder!

**Comment by JasonStein** [comment]
Fixed here: https://github.com/JasonStein/Notepads/commit/6ba9267 I have also changed naming for "UTF 16 LE and BE" to "UTF-16 LE BOM" and "UTF-16 BE BOM" since they are actually unicode with BOM implemented in Notepads. Cheers. Please test it in v0.9.4.0 and leave me your comments.

**Comment by AmionSky** [comment]
Works great!
