### ISSUE TITLE
Find and replace with mismatched case doesn't work 

### ISSUE THREAD

**Issue by johneusebio** [JasonStein/Notepads#3]
If I type "TEST" into Notepads and try to do a find and replace of "test" with "testing" with Match-Case disabled, it will fail if I hit the "replace" button.

However, it will succeed if I hit "Replace All"

**Comment by JasonStein** [comment]
"Replace All" checks through whole document and replace all matches. However,  for "Replace", it checks starting from your selection. If you move the input cursor before "TEST", it will find the match and replace. It is intended for now, what do you think?
