### ISSUE TITLE
[Bug] Notepads doesn't open through git bash

### ISSUE THREAD

**Issue by fuadnafiz98** [JasonStein/Notepads#300]
#### Input 

```sh
$ notepads
```

#### Output

```sh
 bash: /c/Users/USER/AppData/Local/Microsoft/WindowsApps/notepads: Permission denied
```

**Comment by JasonStein** [comment]
Is it official git command line? Can you try run under admin privilege?

**Comment by soumyamahunt** [comment]
> Is it official git command line? Can you try run under admin privilege?

git-cmd works fine, the issue is with git-bash.

**Comment by soumyamahunt** [comment]
> ### If I try to open notepads with git-bash command line, it shows the following error
> #### Input
> ```shell
> $ notepads
> ```
> 
> #### Output
> ```shell
>  bash: /c/Users/USER/AppData/Local/Microsoft/WindowsApps/notepads: Permission denied
> ```

Type `powershell.exe -c notepads` instead of `notepads `to fix it.
