### ISSUE TITLE
[Bug] Command line starts, cannot recognize space or Chinese path 

### ISSUE THREAD

**Issue by absir1949** [JasonStein/Notepads#302]
**Describe the bug**

when i start it from cmd on windows, if filepath has space or chinaese,it cannot work

> C:\>notepads G:\OneDrive - 我\INBOX\PKS\notable\notes\20200226.md

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909 18363]

**Comment by JasonStein** [comment]
C:>notepads G:\OneDrive - "我\INBOX\PKS\notable\notes\20200226.md"

兄弟，用引号。你的路径里有空格。
