### ISSUE TITLE
[Bug]Chinese content disturbance/中文的文本文件打开乱码，notepad与notepad++都正常

### ISSUE THREAD

**Issue by dunkeng** [JasonStein/Notepads#305]
[操作步骤.txt](https://github.com/JasonStein/Notepads/files/4269771/default.txt)
乱码

![QQ截图20200229092507](https://user-images.githubusercontent.com/22165870/75598268-6ce98a80-5ad5-11ea-8f4d-5059eebc5a45.png)

**Comment by lindexi** [comment]
应该是 GBK 问题

**Comment by JasonStein** [comment]
其实不管怎么做，都没法保证准确率，最好的办法就是先识别本机的语言和地区，然后用相应的识别库来对比。但是就算这样，也有可能用户打开的文件就只是utf-8。慢慢程序软件都转向utf-8了，这类问题就不会再出现了。

**Comment by lindexi** [comment]
@JasonStein 作者大大，要不要加个 SaveWithEncoding 和 以某个编码 读取的功能？

**Comment by JasonStein** [comment]
系统自带的save/open dialog不支持添加extension，所以save with encoding不好做。但是我有想加入 以某个编码重新打开当前文本的功能，就像 VSCode一样。

**Comment by lindexi** [comment]
@JasonStein 棒棒棒

其实好像改编码不需要改后缀名哇，还是以原文件保存，只是保存的时候就使用 utf8 了

**Comment by JasonStein** [comment]
哦哦 我的意思是 Win32那个文件保存框 UWP是没有权限魔改的，如果要做的话，就应该像notepad.exe那样在保存框的下面多一个选项，你自己选编码。

**Comment by lindexi** [comment]
@JasonStein 我想了一个馊主意，也许咱通过给用户两个 Dialog 可以解决，一个给用户选编码，一个让用户选保存到哪，就可以解决

**Comment by JasonStein** [comment]
我之前想过，太丑了。。。所以就打算这样了。 毕竟Notepads面向的大多数用户，用不上这个功能。需要这个功能的人多半电脑里也有VSCode或者notepad++

**Comment by JasonStein** [comment]
@dunkeng 暂时你先去设置里选择ANSI 作为默认编码识别，重启app之后再打开你那些乱码的文件看看。

**Comment by dunkeng** [comment]
可以，打开这个文件没问题，但打开JIS的日文的就不行了，无论是UTF8还是ANSI
[新建文本文档.txt](https://github.com/JasonStein/Notepads/files/4288015/default.txt)

**Comment by JasonStein** [comment]
@dunkeng 是的，默认使用本机当前语言编码，所以是gbk，日语就不行了，得手动来。等我加个以另一种编码重新打开的功能吧

**Comment by JasonStein** [comment]
![image](https://user-images.githubusercontent.com/1166162/76267516-51deef00-6228-11ea-9ca7-0318fbe6d3d2.png)

**Comment by lindexi** [comment]
@JasonStein 大佬考虑给个搜寻框不，这么多内容可不好找

**Comment by JasonStein** [comment]
你看中间那个，会根据你的系统语言，优先推荐当前系统ANSI编码，如果是中文的话就是GB 3213。意思就是大部分情况下，大部分国家的用户都能在中间那里找到自己想要的。

**Comment by lindexi** [comment]
厉害了这个交互细节

**Comment by JasonStein** [comment]
@lindexi 更厉害的是，如果像我这样电脑是英文，地区有中文的话，提示两个:

**Comment by JasonStein** [comment]
![image](https://user-images.githubusercontent.com/1166162/76697080-af6fa300-664f-11ea-9823-0cfa4e662cbd.png)

**Comment by JasonStein** [comment]
Closing this thread since v1.1.4.0 is released with "Auto Guess Encoding" feature.
