### ISSUE TITLE
[Feature request] i need GBK or GB2312 encoding choice

### ISSUE THREAD

**Issue by kasusa** [JasonStein/Notepads#323]
# need  a GBK encoding option 
I am a user from china , and lots of txt stuff I download from internet are encoding by `GBK` which is not readable under `utf-8` encoding style.

I need to have a `GBK` encoding option or you can give me a button to easy change the encod from GBK to utf-8 , then i don't have to change the encode using vscode every time

**Comment by JasonStein** [comment]
?

**Comment by JasonStein** [comment]
From the time being, can you try use "ANSI" as default encoding in the setting menu? It will treat files with no BOM as ANSI and use default windows code page. If your system is using Chinese as language, it should use GBK as default.

**Comment by kasusa** [comment]
ANSI setting isn't really working...

I guess i have to hope for the next version have a <kbd>Reopen </kbd> button

ps: attached photo here
![image.png](http://ww1.sinaimg.cn/large/0083vuQJly1gciaia8la6j30n60jogo4.jpg)

**Comment by xieccc** [comment]
> ANSI setting isn't really working...
> 
> I guess i have to hope for the next version have a Reopen button
> 
> ps: attached photo here
> ![image.png](https://camo.githubusercontent.com/40b775ea7361c8d101ad6a873eae4a2ad149510c/687474703a2f2f7777312e73696e61696d672e636e2f6c617267652f303038337675514a6c7931676369616961386c61366a33306e36306a6f676f342e6a7067)

你的这个记事本是utf8，当然不起作用，看右下角

**Comment by xieccc** [comment]
> i

Can the new feature be like vscode, click the lower right corner button to switch coding?

**Comment by JasonStein** [comment]
> > i
> 
> Can the new feature be like vscode, click the lower right corner button to switch coding?

Yes, I am working on the feature (reopen with encoding + save as encoding). Basically I am going to add all ANSI encodings including GB2312.

**Comment by JasonStein** [comment]
<img width="600" alt="Screen Shot 2020-03-07 at 11 13 39 PM" src="https://user-images.githubusercontent.com/1166162/76158294-4d4ff480-60c9-11ea-8649-3f25766d9a67.png">

**Comment by JasonStein** [comment]
![image](https://user-images.githubusercontent.com/1166162/76267505-468bc380-6228-11ea-9251-bb1dd9671097.png)

**Comment by JasonStein** [comment]
Closing this thread since v1.1.4.0 is released with "Auto Guess Encoding" feature.
