### ISSUE TITLE
[Bug] Wrong icon size for TXT files

### ISSUE THREAD

**Issue by guari** [JasonStein/Notepads#324]
The icon used for .txt file has a wrong size, the bug started after latest app update (v.1.1.0.0) released through Windows Store

**Screenshots**

<img src="https://user-images.githubusercontent.com/3869503/75862307-0202c100-5dff-11ea-997a-c977eae60770.png" width="300"/>

**Desktop:**
 - OS: Windows 10 Pro 1909 18363.693
 - App Version: 1.1.0.0
 - Device: Surface Book 2 (display 15' 3240x2160px, DPI scaling 250%)

**Comment by JasonStein** [comment]
Looking into it. I will fix it in v1.1.2.0

**Comment by JasonStein** [comment]
Fixed: https://github.com/JasonStein/Notepads/commit/0135c5761d3e0e6c66b45dd21e8feeb8200288b7

**Comment by guari** [comment]
thank you!
