### ISSUE TITLE
[Feature request] Syntax Highlightning

### ISSUE THREAD

**Issue by MarcelCoding** [JasonStein/Notepads#326]
**Is your feature request related to a problem? Please describe.**
It would be cool if configuration formats such as YAML or XML were provided with syntax highlighting.

**Describe the solution you'd like**
Syntax highlighting for configuration formats. (YAML, XML, ...)

**Comment by JasonStein** [comment]
Use this thread: https://github.com/JasonStein/Notepads/issues/74
