### ISSUE TITLE
[Feature request] Extend file extension capabilities

### ISSUE THREAD

**Issue by microrache** [JasonStein/Notepads#328]
I would like to use Notepads app for some more file extensions. Could you please provide support (and a respective icon) for the following extensions:

- .vue
- .vuerc
- .bash_history
- .npmrc
- .cgi
- .pl
- .gitconfig
- .gitignore
- .gitattributes
- .htaccess
- .buildpath
- .project
- .prj

I managed to gain support for these file extensions myself by storing new keys under Computer\HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppModel\Repository\Packages\19282JackieLiu.Notepads-Beta_1.1.2.0_x64__echhpq9pdbte8\App\Capabilities\FileAssociations but what's missing is the respective file icons - therefore it would be awesome if you could 
a) create new icons for these extensions or 
b) just link the file.png in a first place

**Comment by JasonStein** [comment]
I can add them and use file.png as default for now. 

@mah-qurashy If you are interested in creating those file icons, please let me know. Thanks!

**Comment by mah-qurashy** [comment]
will definitely do it

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mah-qurashy** [comment]
> I can add them and use file.png as default for now.
> 
> @mah-qurashy If you are interested in creating those file icons, please let me know. Thanks!

will definitely do it

**Comment by JasonStein** [comment]
I have added those extensions and @mah-qurashy has been working on adding the corresponding  icons. It is now checked in.

**Comment by mah-qurashy** [comment]
some of these seem difficult to be done without breaking icon consistency because the names are too long, i will try to figure something out

**Comment by JasonStein** [comment]
> some of these seem difficult to be done without breaking icon consistency because the names are too long, i will try to figure something out

Don't waste time on those long file name icons if you think the extension it not widely used like .bash_history. Just focus on broadly used extensions.

As well for things like .gitignore, you can use "Git" in the icon for instance.
