### ISSUE TITLE
NL/LF characters are being selected at the end of the line

### ISSUE THREAD

**Issue by alirezanoori1986** [JasonStein/Notepads#329]
Suppose I type a single word in an empty document. When I triple-click on it, or worse than that, when I "Hole Shift + Home then End" to select the whole line, the app selects an invisible character which is a NL/LF character and when I copy/paste it, it copies that character. This is not the case in any other text editor and most of the time it's pretty annoying.

**Comment by JasonStein** [comment]
This is something enabled by default by WinRT "RichEdit" control. I tried to change the behavior but unfortunately, there is no flag or settings can be made to tweak this behavior.
