### ISSUE TITLE
[Feature request]请问能否添加更多的后缀名关联支持，比如字幕类型。

### ISSUE THREAD

**Issue by suyangzuo** [JasonStein/Notepads#333]
我在电脑上想将 .srt 字幕跟Notepads关联起来，但是在“打开方式”中没有Notepads，而且这个是微软商店程序，没办法像普通Win32程序一样去选择.exe进行关联。

**Comment by JasonStein** [comment]
下个版本帮你加上

**Comment by suyangzuo** [comment]
感谢！
主要的字幕文件格式有 ".srt" 、".ass" 、“.ssa”。

**Comment by Ni1fheim** [comment]
还有像.ps1啊这些脚本后缀名也可以加上😍

**Comment by JasonStein** [comment]
> > 感谢！
> > 主要的字幕文件格式有 ".srt" 、".ass" 、“.ssa”。
> 
> 还有像.ps1啊这些脚本后缀名也可以加上😍 @JasonStein

UWP app 都不支持 .ps1 这类有可能会伤害你电脑的文件后缀，这个我也没办法

**Comment by JasonStein** [comment]
@mah-qurashy  FYI: ".srt", ".ass", “.ssa”

**Comment by xieccc** [comment]
> > > 感谢！
> > > 主要的字幕文件格式有 ".srt" 、".ass" 、“.ssa”。
> > 
> > 
> > 还有像.ps1啊这些脚本后缀名也可以加上😍 @JasonStein
> 
> UWP app 都不支持 .ps1 这类有可能会伤害你电脑的文件后缀，这个我也没办法

希望可以增加.go等各种文本文件的支持

**Comment by Haurchefant-G** [comment]
> > > 感谢！
> > > 主要的字幕文件格式有 ".srt" 、".ass" 、“.ssa”。
> > 
> > 
> > 还有像.ps1啊这些脚本后缀名也可以加上😍 @JasonStein
> 
> UWP app 都不支持 .ps1 这类有可能会伤害你电脑的文件后缀，这个我也没办法

希望可以添加.sql后缀关联

**Comment by JasonStein** [comment]
> > > > 感谢！
> > > > 主要的字幕文件格式有 ".srt" 、".ass" 、“.ssa”。
> > > 
> > > 
> > > 还有像.ps1啊这些脚本后缀名也可以加上😍 @JasonStein
> > 
> > 
> > UWP app 都不支持 .ps1 这类有可能会伤害你电脑的文件后缀，这个我也没办法
> 
> 希望可以添加.sql后缀关联

.sql讲道理不算文本文档，所以不打算支持。

**Comment by JasonStein** [comment]
> > > > 感谢！
> > > > 主要的字幕文件格式有 ".srt" 、".ass" 、“.ssa”。
> > > 
> > > 
> > > 还有像.ps1啊这些脚本后缀名也可以加上😍 @JasonStein
> > 
> > 
> > UWP app 都不支持 .ps1 这类有可能会伤害你电脑的文件后缀，这个我也没办法
> 
> 希望可以添加.sql后缀关联

OK

**Comment by JasonStein** [comment]
这个楼我就关了，你们想要的都加进去了。
