### ISSUE TITLE
[Feature request] Pressing Tab with selected text

### ISSUE THREAD

**Issue by NickeManarin** [JasonStein/Notepads#336]
**Is your feature request related to a problem? Please describe.**
Yes, pressing Tab (and Shift + Tab) with text selected should add/remove /t (or spaces) from the text, not remove the text.

**Describe the solution you'd like**
This feature should be optional, since the expected behavior of pressing any text-changing key with a text selection active is to replace the text.
When enabled, the selected text should be shifted as desired with Tab or Shift-Tab (as the inverted action) like Visual Studio.

**Comment by JasonStein** [comment]
Yeah, this is the feature I always wanted to do but always keep forgetting. We do not need to add a settings flag here, we should just do it as you described. @soumyamahunt Are you interested in implementing such behavior just like Notepad++ and VSCode?

**Comment by kasusa** [comment]
i really want to have the vscode using experience here !

Two things i really like in VScode
<kbd>Pressing Tab with selected text</kbd> & <kbd>holding alt muti cursor</kbd>

**Comment by soumyamahunt** [comment]
> Yeah, this is the feature I always wanted to do but always keep forgetting. We do not need to add a settings flag here, we should just do it as you described. @soumyamahunt Are you interested in implementing such behavior just like Notepad++ and VSCode?

Sorry for replying so late, I was on vacation. I will make a pull request today.

**Comment by JasonStein** [comment]
This feature has been implemented by @soumyamahunt and alive on the store. Please update and check out.

**Comment by NickeManarin** [comment]
Great. Thanks :)
