### ISSUE TITLE
[Bug]保存逻辑出错

### ISSUE THREAD

**Issue by Vixb1122** [JasonStein/Notepads#339]
以拖拽的方式打开文本文档，保存时会触发另存为。
复现步骤：
1. 打开应用。
2. 将一个文本文档拖拽到窗体打开。
3. 修改文档
4. 保存

**Comment by JasonStein** [comment]
<img width="919" alt="Screen Shot 2020-03-11 at 12 53 23 AM" src="https://user-images.githubusercontent.com/1166162/76394455-c9994080-6332-11ea-8b1b-08d2aa983307.png">

无能为力，这是微软做的决定，所有拖入进UWP应用的文件都是只读 （我知道这很傻逼，但是UWP就是这么规定的），所以你保存的时候才会弹出另存为 （本来的文件是只读，Notepads没法覆盖写入）
