### ISSUE TITLE
[Feature request]关闭高亮框框

### ISSUE THREAD

**Issue by kasusa** [JasonStein/Notepads#344]
新版本增加了高亮的框框，方便我知道自己在第几行。
但是我真的觉得它很丑，又找不到关闭的按钮。

尤其是我换了其他的字体。字体会不显示在框的中央。

**Comment by JasonStein** [comment]
设置里有关闭选项，另外你的的字体是什么，可以给个截图不？

![image](https://user-images.githubusercontent.com/1166162/76646394-1c801d00-6518-11ea-8c91-b0b74ae32978.png)
