### ISSUE TITLE
[Feature request] indentation as a whole，多行整体缩进

### ISSUE THREAD

**Issue by CodeWolf-G7** [JasonStein/Notepads#351]
Hello there,
I really like the style and use of notepads. But I have a doubt:

**It seems that notepads did not implement the function of "selecting multiple lines and then using the Tab key to achieve the" indentation as a whole ".**

If I have n’t found a way to achieve ‘indent overall’, I welcome your guidance

Part of this paragraph was translated by Google, from friendly Chinese students

**Comment by JasonStein** [comment]
有人已经问了相同问题了，就在你下面：https://github.com/JasonStein/Notepads/issues/336

这个功能我一直忘记做了，下个版本或者下下个版本会加上。

**Comment by CodeWolf-G7** [comment]
> 有人已经问了相同问题了，就在你下面：#336
> 
> 这个功能我一直忘记做了，下个版本或者下下个版本会加上。

我就记得作者是国人，哈哈。以后我会多看一些。
**谢谢你在notepads上的工作。**
