### ISSUE TITLE
[Bug] Scrolling speed when selecting is dependent on mouse movement

### ISSUE THREAD

**Issue by Dansel** [JasonStein/Notepads#36]
**Description**
Speed when selecting text via mouse selection when a window is scrolling is depending on mouse movement

**To Reproduce**
Open a large text file, enough lines to populate at least 10x the height of your window.

**Expected behavior**
Use click and drag to select text beyond the "visible" scope.

![notepadsscrollingbug](https://user-images.githubusercontent.com/2886387/60810410-5d57b300-a18d-11e9-9c74-b58fe7f9e1e8.gif)

**Desktop (please complete the following information):**
 - OS: 1809 17763.557
 - Version v0.9.3.0

**Comment by entdark** [comment]
That "feature" has been always like that in other programs and older Windows versions as well. Not sure if such a behavior fixable.

**Comment by JasonStein** [comment]
OK, @Dansel can you do one thing first: go to Settings->Advanced Settings->Hide status bar and check it again? Reply your observation in the comments below.

**Comment by Dansel** [comment]
> OK, @Dansel can you do one thing first: go to Settings->Advanced Settings->Hide status bar and check it again? Reply your observation in the comments below.

@JasonStein Yeah, same behavior.

**Comment by JasonStein** [comment]
I think it is indended (by Windows) and I have no way to control it. Sorry about that. If someone know more about this behaviour, feel free to leave your comments.

**Comment by adrian-basheer** [comment]
It would be nice to be able to scroll down with the scroll-wheel while selecting please :)

**Comment by entdark** [comment]
> It would be nice to be able to scroll down with the scroll-wheel while selecting please :)

You can actually. Your cursor has to be inside the application window.

**Comment by adrian-basheer** [comment]
> u

If I have nothing selected the scrolling works fine with the mouse-wheel, but if I have some text selected then scrolling the mouse-wheel does nothing...

**Comment by JasonStein** [comment]
@adrian-basheer I will try add that feature.

**Comment by JasonStein** [comment]
@adrian-basheer What you have requested is implemented here: https://github.com/JasonStein/Notepads/commit/8166767385293157e833e771729393759294dcec

It will be available in v0.9.6.0
