### ISSUE TITLE
Selecting text with CTRL + A adds a space at the end [Bug]

### ISSUE THREAD

**Issue by 4hench** [JasonStein/Notepads#360]
is it possible to turn off?

**Comment by JasonStein** [comment]
Are you saying that if there is one or more empty line(s) at end of the file, notepads select them all?

**Comment by 4hench** [comment]
> Are you saying that if there is one or more empty line(s) at end of the file, notepads select them all?

it acts like i would been pressing spacebar

**Comment by JasonStein** [comment]
Oh I see, it is the line ending character. Ctrl+A will select it as well. If you copy selected text to another place, the line ending will be included as well.

**Comment by 4hench** [comment]
so is it possible to have no line ending with Ctrl+A ?

**Comment by 4hench** [comment]
> Oh I see, it is the line ending character. Ctrl+A will select it as well. If you copy selected text to another place, the line ending will be included as well.

or maybe have an option to turn on and off the line ending would be cool

**Comment by JasonStein** [comment]
I am using the standard RichEdit control from WinRT, as far as I know, there is no option to change this behavior.
