### ISSUE TITLE
[Bug] Saving LF on Windows converts to CRLF.

### ISSUE THREAD

**Issue by MrAmos123** [JasonStein/Notepads#37]
**Describe the bug**
Saving a new document in LF the opening the same document back up will open it in CRLF and not the intended LF.

**To Reproduce**
Open Notepads
Select Unix LF
Type some example out...
Save
Open the newly saved document, in bottom right it'll read CRLF.

**Expected behavior**
Documents using a specific line ending format to be saved. If I save LF it should open in LF, if I save in CRLF it should open in CRLF. 

**Desktop (please complete the following information):**
 - OS: Windows 10 1809 17763.557
 - Version v0.9.4.0

**Comment by JasonStein** [comment]
Just want to make sure, your test file contains not only just one line right?

**Comment by MrAmos123** [comment]
> Just want to make sure, your test file contains not only just one line right?

Whoops... You're right that was the issue. I was writing one line then returning and saving.

LF is working as intended. :)

**Comment by JasonStein** [comment]
It's ok, I made this same mistake before wondering why line ending is not correctly set. Turns out there is no line ending to check at all if your file has only one line:)
