### ISSUE TITLE
关于窗口的建议

### ISSUE THREAD

**Issue by DYLINJIA** [JasonStein/Notepads#374]
**在使用过一段时间后关于窗口的建议**
默认合并在一个窗口有时会很难受(当要两个txt相互对照时，需要新建窗口再拉过去对比)
如果可以的话，建议实行多窗口或者可以设置默认多窗口或者合并窗口的功能
这也只是我使用过程中最大的痛处，UI及其他方面真的很可，感谢大佬开发

**Comment by JasonStein** [comment]
![image](https://user-images.githubusercontent.com/1166162/77222954-5dc68d00-6b15-11ea-8822-496b1d6d2386.png)

**Comment by DYLINJIA** [comment]
我好傻XD 抱歉没看见
