### ISSUE TITLE
[Bug] Clicking on link not working in MarkDown preview in some cases

### ISSUE THREAD

**Issue by soumyamahunt** [JasonStein/Notepads#377]
**Describe the bug**
When MarkDown preview is on and tab is switched, clicking on links won't work until closing and reopening the preview again.

**To Reproduce**
Open a MarkDown file which has links in it. Turn on preview. Swith tab/Create a new tab. Switch to the tab in which preview is on. Click on any link in the preview.

**Expected behavior**
Clicking on link should work.

**Screenshots**
![7mtqtvAMls](https://user-images.githubusercontent.com/51203900/77249156-2666f600-6c65-11ea-9321-7877395e23f6.gif)

**Desktop:**
 - OS: Windows 10 1903 18362.239
 - Version v1.1.7

**Comment by JasonStein** [comment]
Created a PR in WindowsCommunityToolkit repo to fix the problem: https://github.com/windows-toolkit/WindowsCommunityToolkit/pull/3180

**Comment by JasonStein** [comment]
Closing this since v1.2.2.0 is out.
