### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by 1234scarecrow** [JasonStein/Notepads#384]
**Describe the bug**
个性化里设置 背景透明度为 0% 时, 在桌面拖动窗口会闪烁, 在窗口内点住鼠标拖动选中文本, 松开鼠标也会闪烁, 怀疑是鼠标检测鼠标松开动作时的方法有 bug

**To Reproduce**
设置 - 个性化, 设置背景透明度 0% , 拖动窗口或用拖动光标选中文本时, 大概 85% 概率会复现. 窗口内单击鼠标偶尔也会发生闪烁

**Expected behavior**
希望进行以上设置后, 鼠标动作时, 窗口不闪烁

**Screenshots**
![闪烁动图](https://s1.ax1x.com/2020/03/24/8qB2TJ.gif)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909 18363.720]
 - Version [e.g. v1.1.7.0]

**Additional context**

**Comment by JasonStein** [comment]
我这没法复现你的问题，然后你试试黑色模式会不会这样，如果黑色不会的话，那大概率就是微软的亚克力笔刷问题了，或者显卡驱动+系统问题。

**Comment by 1234scarecrow** [comment]
好的谢谢!
