### ISSUE TITLE
[Feature request] 请求加入 shift＋鼠标滚轮 左右滚动热键

### ISSUE THREAD

**Issue by KFERMercer** [JasonStein/Notepads#389]
场景举例:

在编辑markdown文件时, 有时候会碰到较长的行, 这时候想要左右滚动就必须要拖动下方滑块, 会降低编辑效率.

![image](https://user-images.githubusercontent.com/37098748/77647354-36524300-6fa1-11ea-93ba-84ae06cc31ab.png)

**Comment by JasonStein** [comment]
ctrl+shift+滚轮

**Comment by KFERMercer** [comment]
请问能否进一步解答一下, 是出于什么考量才不用单纯的 shift 加滚轮呢?
按 shift 只需要用小拇指就可以操作, 如果是 ctrl+shift, 则需要放平小拇指或者额外需要无名指进行辅助.

**Comment by JasonStein** [comment]
之前有讨论过：https://github.com/JasonStein/Notepads/issues/214

**Comment by JasonStein** [comment]
这样吧，我给你加了一个鼠标中间+滚轮来进行左右滚动的热键，你看满意不？https://github.com/JasonStein/Notepads/commit/dcdb82537f0f716124bcf8cd4f21e4ff8fd37f60

**Comment by KFERMercer** [comment]
感谢你为了解决问题进行的尝试 抱歉没能给予实质性的帮助
