### ISSUE TITLE
鼠标形状优化

### ISSUE THREAD

**Issue by thorly** [JasonStein/Notepads#396]
鼠标移动到垂直滚动条上时，没有更改鼠标形状，仍然是编辑状态的形状

**Comment by JasonStein** [comment]
这是微软的问题：https://github.com/microsoft/microsoft-ui-xaml/issues/1986

![image](https://user-images.githubusercontent.com/1166162/77838871-ba850180-712c-11ea-8e6c-8e415526e68a.png)
