### ISSUE TITLE
[Bug] Pasting Arabic text may make it left-to-right

### ISSUE THREAD

**Issue by be5invis** [JasonStein/Notepads#397]
**Describe the bug**
Right-to-Left scripts (Arabic, Hebrew, etc.) are not treated as RTL.

**To Reproduce**
Type this string into Notepads:
```
العربية
```

This is the word "Arabic" in Arabic, contains 7 letters:

 * `ا` Alif;
 * `ل` Lam;
 * `ع` Ayin;
 * `د` Ra;
 * `ب` Ba;
 * `ي` Ya;
 * `ة` Ta Marbutah.

**Expected behavior**
This string is shown like this:
![image](https://user-images.githubusercontent.com/240091/77881822-a0bee980-7214-11ea-8372-6467047f9cf7.png)
It arranges the letters from right to left, and shows:
 * Alif in initial-isolated form;
 * Lam in initial form;
 * Ayin in medial form;
 * Ra in final form;
 * Ba in initial form;
 * Ya in medial form;
 * Ta Marbutah in final form;

**Screenshots**
![image](https://user-images.githubusercontent.com/240091/77881798-8f75dd00-7214-11ea-96fd-6c2a4d21773e.png)
It could be observed that this word is treated as left-to-right and then shaped together. Currently it is shown like this, which is wrong:
 * Alif and Lam shown in a Lam-Alif ligature in its final form;
 * Ayin in initial form;
 * Ra in final form;
 * Ba in medial form;
 * Ya in initial form;
 * Ta Marbutah in isolated form.

**Desktop (please complete the following information):**
 - OS: 18363.720
 - Version: 1.1.7.0

**Additional context**
Please note that BiDi is not only supporting text that flows from right to left, but also the mixture of LTR and RTL scripts, and various BiDi control characters. Please refer to here for more detail: https://en.wikipedia.org/wiki/Bidirectional_text

**Comment by be5invis** [comment]
Note: Pressing CTRL+R makes the editor look like this:
![image](https://user-images.githubusercontent.com/240091/77882890-dd8be000-7216-11ea-96d7-6acf257e5350.png)

**Comment by JasonStein** [comment]
I did some update to the flow direction change shortcut yesterday and it should be available in v1.1.8.0.

Basically you can use Ctrl+L or Ctrl+R to quickly swtich text flow direction. You need to retype after changing text flow direction. It might not work for existing words.

**Comment by be5invis** [comment]
The problem is that the direction of **the letters in the Arabic word** is wrong.

No matter what what the paragraph direction is, Arabic letters should always be handled right-to-left. Paragraph direction will influence the order of many things, like the order of _words_ or _numbers_, but not the order of letters within an Arabic word.

The following string is the sample of the [Unicode Bidi Algorithm demo](https://unicode.org/cldr/utility/bidi.jsp):

```
mark 3.1% مارْك 2.0.
```

When shown in a LTR paragraph:

![image](https://user-images.githubusercontent.com/240091/77883511-21331980-7218-11ea-9abd-0cf43c50c5b8.png)

When shown in a RTL paragraph:
![image](https://user-images.githubusercontent.com/240091/77883530-2728fa80-7218-11ea-9141-3c0d37ca89e0.png)

**Comment by JasonStein** [comment]
https://github.com/JasonStein/Notepads/commit/e0e470427ceaea081d67a212a219e61166c93861

Can you try latest master build?

![image](https://user-images.githubusercontent.com/1166162/77885484-f1861080-721b-11ea-8e92-538569a0adcf.png)

![image](https://user-images.githubusercontent.com/1166162/77885502-f77bf180-721b-11ea-9a4e-6d1466e77f10.png)

**Comment by be5invis** [comment]
How does this `mark 3.1% مارْك 2.0.` look in a LTR paragraph?

**Comment by JasonStein** [comment]
![image](https://user-images.githubusercontent.com/1166162/77885979-e2ec2900-721c-11ea-8013-5b477c9f7725.png)
![image](https://user-images.githubusercontent.com/1166162/77885995-ec759100-721c-11ea-9816-1784815c3934.png)
![image](https://user-images.githubusercontent.com/1166162/77886018-f9928000-721c-11ea-80a4-45cd4f4425d8.png)
![image](https://user-images.githubusercontent.com/1166162/77886023-fdbe9d80-721c-11ea-9a2d-4649d502547a.png)

**Comment by be5invis** [comment]
Seems fine, let me grab a private build and test more strings 🤔.

**Comment by be5invis** [comment]
Strange, in Master it looks like this:
![image](https://user-images.githubusercontent.com/240091/77886605-06fc3a00-721e-11ea-87fe-2696f8c6f82c.png)

**Comment by be5invis** [comment]
It looks like if I paste the string when having CHS IME enabled, then the BiDi result is incorrect. If using English keyboard, it is correct.
![image](https://user-images.githubusercontent.com/240091/77887249-2182e300-721f-11ea-9ebe-c6a49d32c9e9.png)

**Comment by be5invis** [comment]
The pasting behavior looks very unstable, but enabling IME will always ruin RTL runs...

**Comment by JasonStein** [comment]
It is definitely doing something under the hood and it is biased towards local + IME as well. Another thing I found is that manual changing the direction when there is nothing will not work. However, the default RichEditBox shortcut (Ctrl+L/R) works without any problem.

**Comment by JasonStein** [comment]
This PR should properly handles all cases: https://github.com/JasonStein/Notepads/pull/395/files

![image](https://user-images.githubusercontent.com/1166162/77896404-1767e100-722d-11ea-95f2-28c747a2a270.png)
![image](https://user-images.githubusercontent.com/1166162/77896413-1c2c9500-722d-11ea-8c06-d70a99aa1f18.png)

**Comment by be5invis** [comment]
Slightly modifying `PastePlainTextFromWindowsClipboard` could fix the IME-paste issue:

```C#
Document.BeginUndoGroup();
Document.Selection.SetText(TextSetOptions.None, text);
Document.Selection.CharacterFormat.TextScript = TextScript.Ansi;
Document.Selection.StartPosition = Document.Selection.EndPosition;
Document.EndUndoGroup();
```

**Comment by be5invis** [comment]
Confirm fixed. Closed.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/77904405-5439d500-7239-11ea-9035-877218214624.png)

Test String:
```
Adlam:	𞤑𞤵𞥅𞤤𞤢𞤤 𞤺𞤢𞤣𞤢𞤲𞤢𞤤 𞤋𞤲𞥆𞤢𞤥𞤢 𞤢𞥄𞤣𞤫𞥅𞤶𞤭 𞤬𞤮𞤬 𞤨𞤮𞤼𞤭⹁ 𞤲'𞤣𞤭𞤥𞤯𞤭𞤣𞤭 𞤫 𞤶𞤭𞤦𞤭𞤲𞤢𞤲𞥆𞤣𞤫 𞤼𞤮 𞤦𞤢𞤲𞥆𞤺𞤫 𞤸𞤢𞤳𞥆𞤫𞥅𞤶𞤭.
Arabic:	عندما يريد العالم أن ‪يتكلّم ‬ ، فهو يتحدّث بلغة يونيكود. تسجّل الآن لحضور المؤتمر الدولي العاشر ليونيكود (Unicode Conference)، الذي سيعقد في 10-12 آذار 1997 بمدينة مَايِنْتْس، ألمانيا.
Hebrew:	סעיף א. כל בני אדם נולדו בני חורין ושווים בערכם ובזכויותיהם. כולם חוננו בתבונה ובמצפון, לפיכך חובה עליהם לנהוג איש ברעהו ברוח של אחוה.
N'ko:		ߞߏ ߡߍ߲ ߞߵߊ߬ ߞߍ߫ ߊ߲ ߛߋ߫ ߘߊ߫ ߞߊ߬ ߕߟߋ߬ߓߊ߰ߓߟߐߟߐ ߘߊߦߟߍ߬ ߒߞߏ ߦߋ߫ ߸ 
Syriac:	ܫܠܡ ܘܠܐܠܗܐ ܏ܫܘܒ܆ ܘܠܕܘܝܐ ܕܣܡ ܗܠܝܢ ܫܘܒܩܢܐ܀
Thaana:	ވަނަ މާއްދާ ހުރިހާ އިންސާނުންވެސް ދުނިޔެއަށް އުފަންވަނީ، މިނިވަންކަމުގައި، ހަމަހަމަ ޙައްޤުތަކަކާއެކު، ހަމަހަމަ ދަރަޖައެއްގައި ކަމޭހިތެވިގެންވާ ބައެއްގެ ގޮތުގައެވެ.
```
