### ISSUE TITLE
[Feature request] Font color in dark mode

### ISSUE THREAD

**Issue by seanxnie** [JasonStein/Notepads#401]
您好，是否可以考虑在深色模式时将字体颜色改为浅灰、银色等，白色的对比度太强，实际感觉有些晃眼。对比vscode的字体颜色时就会明显感觉到。谢谢！

**Comment by JasonStein** [comment]
有这个想法，给我点时间。

**Comment by JasonStein** [comment]
我把深色模式下的字体颜色稍微调淡了一点，v1.2.0.0出来的时候你试试看。

**Comment by seanxnie** [comment]
谢谢您的付出！
