### ISSUE TITLE
回车后和上一行对齐，比如上面一行首行前端有一个tab，那回车后也自动空出一个tab（比如editplus做的那样）

### ISSUE THREAD

**Issue by One010101** [JasonStein/Notepads#403]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by JasonStein** [comment]
实现了：https://github.com/JasonStein/Notepads/commit/d359000cb5f63b8a30c6424749967a3d275dd016

v1.1.9.0会加入
