### ISSUE TITLE
[Bug] 软件打不开

### ISSUE THREAD

**Issue by EVNII** [JasonStein/Notepads#413]
软件打不开，不知道什么原因。不管是windows store下的 还是github下载然后powershell安装的都无法运行。也没有报错信息就算软件出来一个界面立马闪退。

Windows 10 1909 18363.720

**Comment by JasonStein** [comment]
感谢反馈，还是第一次有人说打不开，我也很感兴趣想知道咋回事，能帮个忙嘛？
按以下操作可以拿到为什么闪退的日志：
先打开事件查看器：
![image](https://user-images.githubusercontent.com/1166162/78291250-ef50da00-74d9-11ea-8ecf-70221983c1a2.png)
然后选择这里：
![image](https://user-images.githubusercontent.com/1166162/78291377-232bff80-74da-11ea-9e7d-52fe1ed12a9c.png)
然后你看看有没有什么有用的日志可以拷贝过来我帮你看看。
你可以先打开Notepads让它闪退，然后在日志查看器里看同一时间有没有应用奔溃的记录，然后把记录拷贝到这里来。

**Comment by JasonStein** [comment]
就像这样：
![image](https://user-images.githubusercontent.com/1166162/78291565-77cf7a80-74da-11ea-8565-b7c700ec39ab.png)

**Comment by JasonStein** [comment]
顺便如果方便的话，你试试下载一个比较古老的版本看看能不能打开？

**Comment by EVNII** [comment]
我并没有在应用程序分类下找到有关于notepads的事件记录。不过我在自定义视图找到了有关的事件：

> 0x80070057: 无法为程序包 19282JackieLiu.Notepads-Beta_1.1.9.0_x64__echhpq9pdbte8 创建进程，因为在准备激活的过程中遇到错误。[LaunchProcess]

详细信息：
```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Microsoft-Windows-AppModel-Runtime" Guid="{f1ef270a-0d32-4352-ba52-dbab41e1d859}" /> 
  <EventID>203</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x2000000000000004</Keywords> 
  <TimeCreated SystemTime="2020-04-03T23:30:02.841505700Z" /> 
  <EventRecordID>40910</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="12544" ThreadID="25416" /> 
  <Channel>Microsoft-Windows-AppModel-Runtime/Admin</Channel> 
  <Computer>YuzhousPC</Computer> 
  <Security UserID="S-1-5-18" /> 
  </System>
- <EventData>
  <Data Name="PackageName">19282JackieLiu.Notepads-Beta_1.1.9.0_x64__echhpq9pdbte8</Data> 
  <Data Name="ImageName">Notepads.exe</Data> 
  <Data Name="ApplicationName">19282JackieLiu.Notepads-Beta_echhpq9pdbte8!App</Data> 
  <Data Name="ErrorCode">2147942487</Data> 
  <Data Name="Message">[LaunchProcess]</Data> 
  </EventData>
  </Event>

```

**Comment by EVNII** [comment]
我尝试了一下旧版本。 1.0正式版是同样的问题 打不开。不过0.9的beta版是可以打开的。

**Comment by JasonStein** [comment]
我大概率觉得是你的系统有问题，可能之前更新或者用的时候有些模块坏了，你先试试看在商店里下载别的UWP应用能不能打开？然后你跟着这个教程修复一下系统试试：https://support.microsoft.com/zh-cn/help/929833/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system

**Comment by EVNII** [comment]
解决了了谢谢！

**Comment by JasonStein** [comment]
> 解决了了谢谢！

咋解决的？

**Comment by SoDebug** [comment]
> 解决了了谢谢！

咋解决的呢 我也遇到同样的问题了

**Comment by SoDebug** [comment]
> > 解决了了谢谢！
> 
> 咋解决的？

联网后重新打开即可 目测是首次打开需要联网
