### ISSUE TITLE
[Bug] color banding on aclyric background

### ISSUE THREAD

**Issue by mah-qurashy** [JasonStein/Notepads#414]
not sure if this happened after some recent version but never noticed it before
applies to both light and dark mode

![Untitled](https://user-images.githubusercontent.com/20822445/78296641-61530e80-752e-11ea-9229-714a76b0dcbf.png)

**Comment by JasonStein** [comment]
Done: https://github.com/JasonStein/Notepads/commit/b16ca7c4145440035fa889cfe0616969fb1df48b

**Comment by JasonStein** [comment]
It (the banding effect) will be fixed in v1.2.0.0, closing this thread for now.
