### ISSUE TITLE
[Bug]PowerShell Window/Windows Terminal Closes after manual installation

### ISSUE THREAD

**Issue by Restia666Ashdoll** [JasonStein/Notepads#417]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
After installation PowerShell/Windows Terminal window remains

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10 1909 18363.720]
 - Version [1.1.9.0]

**Additional context**
I am creating a Scoop manifest to install Notepads directly. However, no matter what I cant make the Window not close after installation
https://gist.github.com/Restia666Ashdoll/61fd66c2e153462becac877249903d06

**Comment by JasonStein** [comment]
Is it a wrapper of the store installation ps1 script? If it is, then this is not the right place to ask but you can actually modify the scrip as you want to see if you can remove the logic of exiting the process after installation in the add-package script.

**Comment by JasonStein** [comment]
Try modify this method: 
![image](https://user-images.githubusercontent.com/1166162/78519940-a5861f00-7779-11ea-80fd-7cc716592be3.png)

**Comment by JasonStein** [comment]
Basically make changes to that function and do not exit if it is $ErrorCodes.Success.

![image](https://user-images.githubusercontent.com/1166162/78520068-26451b00-777a-11ea-9873-96e92778e7c8.png)

**Comment by JasonStein** [comment]
However, I do not recommend anyone to spend time on making third party installation script. Microsoft Store is the easiest way for users to securly download and install UWP apps and the auto-update feature comes with the store is very nice.

**Comment by Restia666Ashdoll** [comment]
The Scoop manifest manages everything(dev mode, installing the certificate and running Install.ps1), so that you can install it with one command - `scoop install notepads-np`(after it is added to a bucket). It also contains instructions for bucket managers to autoupdate the manifest to latest version.
I find installing and managing apps through a package manager like Scoop easier than the Store(managing updates is also easier). I cant modify the Add-AppDevPackage.ps1 script since Scoop is designed to always download your latest release and install as instructed on the manifest.
The manifest I made actually works accept it closes the terminal after finishing installation. I need to find a way to call Install.ps1 but prevent the exit.

**Comment by JasonStein** [comment]
> The Scoop manifest manages everything(dev mode, installing the certificate and running Install.ps1), so that you can install it with one command - `scoop install notepads-np`(after it is added to a bucket). It also contains instructions for bucket managers to autoupdate the manifest to latest version.
> I find installing and managing apps through a package manager like Scoop easier than the Store(managing updates is also easier). I cant modify the Add-AppDevPackage.ps1 script since Scoop is designed to always download your latest release and install as instructed on the manifest.
> The manifest I made actually works accept it closes the terminal after finishing installation. I need to find a way to call Install.ps1 but prevent the exit.

Got it, what about using `notepads-app` instead of `notepads-np` as the package name?

**Comment by Restia666Ashdoll** [comment]
> > The Scoop manifest manages everything(dev mode, installing the certificate and running Install.ps1), so that you can install it with one command - `scoop install notepads-np`(after it is added to a bucket). It also contains instructions for bucket managers to autoupdate the manifest to latest version.
> > I find installing and managing apps through a package manager like Scoop easier than the Store(managing updates is also easier). I cant modify the Add-AppDevPackage.ps1 script since Scoop is designed to always download your latest release and install as instructed on the manifest.
> > The manifest I made actually works accept it closes the terminal after finishing installation. I need to find a way to call Install.ps1 but prevent the exit.
> 
> Got it, what about using `notepads-app` instead of `notepads-np` as the package name?

np stands for nonportable. Everything in the nonportable bucket has this suffix. 
https://github.com/TheRandomLabs/scoop-nonportable/

**Comment by Restia666Ashdoll** [comment]
By the way, can you not have an alternate Install.ps1(its more of a feature request) that does not close after installation ?

**Comment by JasonStein** [comment]
> By the way, can you not have an alternate Install.ps1(its more of a feature request) that does not close after installation ?

I can, but it is extra work that I need to do every time. Maybe I can write a script to do it before packaging the release binary. I don't have a plan for now unless more users are needed. Even for Github Releases, there are not many users download it and use it as a way to install Notepads. I don't think it is worth the effort to be honest.

**Comment by Restia666Ashdoll** [comment]
Thanks. It may add more users from people like us who mostly use Scoop to install everything.

**Comment by JasonStein** [comment]
> Thanks. It may add more users from people like us who mostly use Scoop to install everything.

I know, but now you need to maintain it and there is no auto-update built-in right? Whenever new version come out, user still needs to run the update command right? The benefits of it is really low considering Notepads is still in active development state. I would prefer more users to install from the store and have Windows auto-update their app. It is much simpler for me and also for end users. Just my 2 cents here.

**Comment by Restia666Ashdoll** [comment]
There is auto update built in. I dont know how it works, but the bucket maintainers use some scripts to automatically update the manifests to latest version.
https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate
This manifest only says
```
    "checkver": {
        "github": "https://github.com/JasonStein/Notepads"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/JasonStein/Notepads/releases/download/v$version/Notepads_$version_x64.zip"
            },
            "32bit": {
                "url": "https://github.com/JasonStein/Notepads/releases/download/v$version/Notepads_$version_x86.zip"
            }
        }
    }
}
```

**Comment by JasonStein** [comment]
Yes, I know, exactly, you need to run that scoop update * -I command and not every Scoop user will do it like you. But for Store users, they are receiving the update automatically out of box. I still do not see a benefit of shipping this app out of store even if it is on GitHub. At least before Microsoft allows UWP app to be shipped and packaged as a standalone exe binary.

**Comment by Restia666Ashdoll** [comment]
So, I used sed in the pre-install script to remove that particular line. It looks like this, but still closes after installation
![image](https://user-images.githubusercontent.com/56309157/78642845-fcead300-78d0-11ea-8834-bb7d7808ff45.png)
Are you sure thats all I need to change ?

**Comment by Restia666Ashdoll** [comment]
So, is there anything else in Install.ps1 that closes the shell? It just goes 'Not Responding' after installation is finished and terminates. The line you underlined has been removed before running the install script. Or should I replace it with something else ?

**Comment by Restia666Ashdoll** [comment]
You are saying I need to modify the PrintMessageAndExit function
![image](https://user-images.githubusercontent.com/56309157/78684803-8967b680-790e-11ea-9c89-99b26f8e7b8d.png)
But what is the part I need to change ?

**Comment by JasonStein** [comment]
I think if you remove "Exit" here, it should not. Unless some underlining method is calling the exit so it exits after finishing. Again, I do not create this script and have no idea what it is doing under the hood. This script is generated by Visual Studio packaging tool.
![Screen Shot 2020-04-07 at 9 35 48 AM](https://user-images.githubusercontent.com/1166162/78695633-33b1f080-78b3-11ea-8866-902512106f5b.png)

**Comment by Restia666Ashdoll** [comment]
Sorry for removing my previous replies. I have decided to not use the install script. Since, registering the certificate and enabling dev mode are all handled by the manifest, it will install through the msixbundle from the manifest itself. Thanks for your concern. I have already submitted a pull request since it works.
https://github.com/TheRandomLabs/scoop-nonportable/pull/133

**Comment by JasonStein** [comment]
> Sorry for removing my previous replies. I have decided to not use the install script. Since, registering the certificate and enabling dev mode are all handled by the manifest, it will install through the msixbundle from the manifest itself. Thanks for your concern. I have already submitted a pull request since it works.
> [TheRandomLabs/scoop-nonportable#133](https://github.com/TheRandomLabs/scoop-nonportable/pull/133)

Good news, so you do not need to do anything, that's nice. Can you upgrade the script to use the latest version? v1.2.1.0 is out. Thanks!

**Comment by Restia666Ashdoll** [comment]
Done. Thanks. Once it gets merged it will be automatically updated to latest versions.

**Comment by Restia666Ashdoll** [comment]
@JasonStein It got merged
Notepads can now be installed with
```
scoop bucket add nonportable
scoop install notepads-np
```
Also, closing the issue.
