### ISSUE TITLE
Using spaces as tab style should not convert already existing files tabs

### ISSUE THREAD

**Issue by AmionSky** [JasonStein/Notepads#42]
I really don't think it should modify existing files in such a way.
The problem is that this runs on file open:
https://github.com/JasonStein/Notepads/blob/49b56d68bcce79d844f0d8cddb9c6ad11a609717/src/Notepads/Controls/TextEditor/TextEditor.cs#L115-L121

**Comment by JasonStein** [comment]
Let me think about it..... I am 5:5 on this right now. The solution would be remove it or give user an option. Not sure which way is better.

**Comment by entdark** [comment]
I think the correct behavior is to apply either spaces or tabulation for the editions, but don't change unedited parts of file.

**Comment by JasonStein** [comment]
OK, I am removing GetTextWithDefaultTabIndentation for SetText, what about copied text from clipboard? Should I respect "\t" as well?

```
        public async Task PastePlainTextFromWindowsClipboard(TextControlPasteEventArgs e)
        {
            if (e != null)
            {
                e.Handled = true;
            }

            if (!Document.CanPaste()) return;

            var dataPackageView = Windows.ApplicationModel.DataTransfer.Clipboard.GetContent();
            if (!dataPackageView.Contains(StandardDataFormats.Text)) return;
            try
            {
                var text = await dataPackageView.GetTextAsync();
                text = GetTextWithDefaultTabIndentation(text);
                Document.Selection.SetText(TextSetOptions.None, text);
                Document.Selection.StartPosition = Document.Selection.EndPosition;
            }
            catch (Exception)
            {
                // ignore
            }
        }
```

**Comment by AmionSky** [comment]
I think it should respect "\t". Or give an option if it should convert copied text.

**Comment by JasonStein** [comment]
OK, I am making it to respect all existing "\t" and tab key behaviour will only impact on new tabs inserted by user:
https://github.com/JasonStein/Notepads/commit/b1c3760a446f9afdd2b9dcd515e8471b3b3615d6
