### ISSUE TITLE
[Feature request] File name instead of Notepads in taskbar

### ISSUE THREAD

**Issue by Nionor** [JasonStein/Notepads#420]
Would be lovely to have it like regular notepad where the app name in the taskbar is the actual file name. Since there are tabs here maybe it reflects the open tab if there are multiple files open.

**Comment by JasonStein** [comment]
Sure, will add it in v1.2.2.0

**Comment by JasonStein** [comment]
![image](https://user-images.githubusercontent.com/1166162/78723808-fb290b80-78e0-11ea-8602-b1fb6c2bee94.png)

**Comment by Nionor** [comment]
Great, thanks!
