### ISSUE TITLE
[Feature request] Hope to add syntax highlighting support

### ISSUE THREAD

**Issue by cathaysia** [JasonStein/Notepads#423]
没有语法高亮改xml格式的配置文件太难受啦，全部都是一个色的，分不清哪里是注释哪里是正文。希望可以加入语法高亮的支持，只有.conf和.xml的就行。

**Comment by JasonStein** [comment]
https://github.com/JasonStein/Notepads/issues/326
https://github.com/JasonStein/Notepads/issues/286
https://github.com/JasonStein/Notepads/issues/74
