### ISSUE TITLE
[Feature request] Add support for .vimrc files

### ISSUE THREAD

**Issue by Teraskull** [JasonStein/Notepads#424]
**Is your feature request related to a problem? Please describe.**
The default notepad does have an option for UNIX line endings, but it is not convenient.

**Describe the solution you'd like**
Possibility to open .vimrc files with Notepads, just like it is possible now with .bashrc

**Comment by JasonStein** [comment]
Done: https://github.com/JasonStein/Notepads/commit/0ac8e1a6d511255bb73d20e967c4a2427ac665fa

**Comment by JasonStein** [comment]
Closing this since v1.2.2.0 is out.
