### ISSUE TITLE
[Bug]Regular Expression Replacing does not support replace TO \r

### ISSUE THREAD

**Issue by wanderseeme** [JasonStein/Notepads#425]
**Describe the bug**

Regular Expression Replacing does not support replace TO \r

For example, you wanna replace all two newlines to one newline, you type "\r\r" and replace them to "\r", the application will indeed replace all newlines to two charater "\" and "r", which is not expected.

**To Reproduce**
Steps to reproduce the behavior.

Eample text:

line 1

line 2

1. Hit Ctrl+H to launch Replace
2. Hit Alt+E to turn Regular Expression Replacing on
3. Type "\r\r" in upper text box, type "\r" in lower text box
4. Hit Ctrl+Alt+Enter to replace all
5. You expect:

line1
line2

6. You actually get (not exptected, it is the bug):

line1\rline2

**Expected behavior**

You expect:

line1
line2

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 1909 18363.720
 - Version 1.1.9.0

**Additional context**

**Comment by JasonStein** [comment]
yes this is an issue, however I think if you search "\r\r", instead of doing anything, it should not. Since "\r" you type in the search box is actually two characters: '\' and 'r'. 

Considering if you have a case like this:
```
line 1\r\r

line1\r\r
```

I tried Notepad++ and VSCode and they do not allow line ending character at all, which means "\r\r" will consider as "\\r\\r"

**Comment by wanderseeme** [comment]
哈哈好像老哥是中国人？首先致敬能写出我心目中一款最接近完美的文本编辑器，太简洁高效好用了，给你点个大大的赞！

为了方便说明问题，下面我就直接打中文了哈。

我的工作流中经常需要使用这类文本编辑器来进行对换行符的替换，**这是我选择文本编辑器时最看重的功能**。例如：（1）把Excel中一长列的词儿先复制到文本编辑器中，然后替换换行符为“、”，形成一行话再粘贴到Word里；（2）或者如上个示例中，Excel的一长列词之复制出来中间换行符太多了，我需要先把两个换行符替换成一个换行符，再进行后续处理。

![1](https://user-images.githubusercontent.com/1303078/79035452-7811f900-7bf1-11ea-82e8-6785bb1cc923.png)

如果按上图点击替换的话，结果如下：

![2](https://user-images.githubusercontent.com/1303078/79035476-aa235b00-7bf1-11ea-8fa1-5e5ddb224443.png)

而我真实希望的，是如下的样子：

![5](https://user-images.githubusercontent.com/1303078/79035710-b7414980-7bf3-11ea-8909-48dc4eb06be1.png)

我之前一直使用Notepad++（但是因为它比较丑所以我一直在找替代品），同样的需求，我可以在Notepad++中这样操作，请留意Notepad++严格认为Windows的换行符是CR LF（即“\r\n”），故需要如图的替换：

![3](https://user-images.githubusercontent.com/1303078/79035518-00909980-7bf2-11ea-9931-a66c37b52278.png)

上图中选择”查找模式“为”扩展“或”正则表达式“其实都支持”\r\n“的替换，Notepad++是可以成功替换的，这个功能我十分依赖用了很多年：

![6](https://user-images.githubusercontent.com/1303078/79035781-36368200-7bf4-11ea-845b-94d7b786fde7.png)

我最早在Notepads中肯定最先沿用的也是Notepad++里”\r\n“的习惯，不过提示的是”未找到“，我才摸索到Notepads UWP可能暂时用的是Mac方式的”\r“做换行。

![4](https://user-images.githubusercontent.com/1303078/79035792-477f8e80-7bf4-11ea-9291-24a41affecd7.png)

换行符方面，我的理解是
Windows，用”回车符+换行符“CR LF，即\r\n
macOS，用”回车符“CR，即\r
Unix/Linux，用”换行符“LF，即\n

所以深层次讲Notepads可以在换行符查找到替换功能上再明确细化一些，当然就解决本issue而言”替换为“的输入框里能识别”\r“为换行符就足够我完美使用了。

感谢，祝好！

**Comment by JasonStein** [comment]
明白了，让我想想怎么做比较合适再回复你。

**Comment by JasonStein** [comment]
现在实现的效果是，搜索你还是得用\r但是替换里面\t \r \n都支持了，所以也还是比较完美解决你的痛点：
https://github.com/JasonStein/Notepads/commit/8b4db7b7b408513f9d37c0573367ea642701b094

![image](https://user-images.githubusercontent.com/1166162/79091436-1ab99d00-7d02-11ea-82b3-33dac17dd246.png)

![image](https://user-images.githubusercontent.com/1166162/79091440-1ee5ba80-7d02-11ea-8923-29ed06daa8fb.png)

![image](https://user-images.githubusercontent.com/1166162/79091454-2c02a980-7d02-11ea-8bf5-6156733dfae8.png)

![image](https://user-images.githubusercontent.com/1166162/79091464-315ff400-7d02-11ea-892a-bc1d6a4edaeb.png)

**Comment by JasonStein** [comment]
先关闭了哈，v1.2.2.0已经放出来，明后天应该就能在应用商店里更新了。有什么问题之后可以再问我。
