### ISSUE TITLE
[Feature request] Plugin System for In Place Preview

### ISSUE THREAD

**Issue by sirinath** [JasonStein/Notepads#431]
Move MD format to a plugin and introduce a plugins system for different formats like MD, AsciiDoc, HTML, etc. with the ability to add new formats. Only at the point of editing the underlying markdown should be shown and rest will be in preview mode.

**Comment by JasonStein** [comment]
No plan for adding plugin system at this moment. I wanted to keep notepads as a simple text editor as possible,
