### ISSUE TITLE
[Bug] Can not open any url in Notepads

### ISSUE THREAD

**Issue by caizefeng** [JasonStein/Notepads#434]
**Describe the bug**
two problem actually, but maybe due to the same reason.
1. Only searching via "google" is available, neither "Bing" nor "Duck Duck go" works well (the browser cant pop up). (basicly click the button and nothing happens)
2. Almost every url link on markdown preview ( and on "settings" sidebar ) cant be opened, the browser can't pop as well. (basicly click the url and nothing happens)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909 18363.720]
 - Version [e.g. v1.2.1.0]

**Additional context**
1. I was thinking it's my network setting at the first place, but changing to another default browser (chrome -> edge) didn't help.
2. I once used Fiddler to allow UMP app accessible to local ports before, but the situation did not change  after i disabled this loopback exemption thing, 
3. I was thinking it's because of using proxy (actually browser not popping indicates that probably not the case ), closing proxy did not help.

**Comment by JasonStein** [comment]
It might due to this issue: https://github.com/JasonStein/Notepads/issues/377

I send out a PR to fix the problem in Windows Community Toolkit:  https://github.com/windows-toolkit/WindowsCommunityToolkit/pull/3180

**Comment by caizefeng** [comment]
thanks, so it means the bug can not be fixed till new Windows Community Toolkit is released ?

**Comment by JasonStein** [comment]
> thanks, so it means the bug can not be fixed till new Windows Community Toolkit is released ?

Actually, I am waiting for this PR to check-in: https://github.com/windows-toolkit/WindowsCommunityToolkit/pull/3206
This PR addresses some threading issues with the toolkit so it can help resolve issues with the Notepads Xbox game bar widget implementation. I will use the nightly build after this PR which will also have my fix for the MarkdownTextBlock. If everything works fine I will just use it for the next Notepads release.

**Comment by JasonStein** [comment]
This has been fixed in master and will be part of next release.

**Comment by JasonStein** [comment]
Closing this since v1.2.2.0 is out.
