### ISSUE TITLE
[Bug] Acrylic effects in battery saver mode

### ISSUE THREAD

**Issue by krlvm** [JasonStein/Notepads#436]
**Describe the bug**
Acrylic and transparency effects automatically disables in battery saver mode, so, when acrylic is enabled in Notepads, its window looks strange, ugly and, mostly, unusable.

**To Reproduce**
1) Set acrylic blur percentage less than 100% in Notepads settings
2) Enable battery saver mode
3) Open Notepads

**Expected behavior**
Notepads should disable all transparency effects in battery saver mode automatically

**Screenshots**
![btsaver](https://user-images.githubusercontent.com/51774833/79065455-16b55d00-7cb9-11ea-87ad-75e98b3cbc14.png)

**Desktop:**
 - OS: Windows 10 1903 19362.719
 - Version v1.2.1.0

**Comment by JasonStein** [comment]
Good point, will fix.

**Comment by JasonStein** [comment]
Fixed here: https://github.com/JasonStein/Notepads/commit/d1ac90a4ad9f9a6104861792ca5485dba427a178

Now Acrylic effect turns off automatically when battery saver mode is on or transparency effects is turned off in system settings. Opacity will be adjusted to 100% behind sense if when that happens.

![image](https://user-images.githubusercontent.com/1166162/79082398-7cfea780-7cda-11ea-9b0d-595fbce84177.png)
![image](https://user-images.githubusercontent.com/1166162/79082400-82f48880-7cda-11ea-942f-da91e975182e.png)
![image](https://user-images.githubusercontent.com/1166162/79082401-88ea6980-7cda-11ea-9c82-bf68c5a55571.png)

**Comment by JasonStein** [comment]
![image](https://user-images.githubusercontent.com/1166162/79082407-9c95d000-7cda-11ea-86de-46550ede2a6c.png)
![image](https://user-images.githubusercontent.com/1166162/79082414-a4557480-7cda-11ea-975a-1d2a7229cf87.png)
