### ISSUE TITLE
[Feature request] Edit .bat files using windows cotext menu

### ISSUE THREAD

**Issue by brunofpires** [JasonStein/Notepads#438]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Would be useful to be possible to select Notepads to edit .bat files. At the moment, when I right click a .bat file, there's no way to assign Notepads to edit

**Describe alternatives you've considered**
I tried to modify the registry in order to change the defaut edit software, but I can't assing notepads that way cause the software is UWP, so I couldn't finde the .exe file.

**Additional context**
NA

**Comment by JasonStein** [comment]
This is a known security limitation of UWP apps. This is not allowed by Windows 10. Nothing I can do here.

**Comment by soumyamahunt** [comment]
> I tried to modify the registry in order to change the defaut edit software, but I can't assing notepads that way cause the software is PWA, so I couldn't finde the .exe file.

Which registry path did you use??

**Comment by brunofpires** [comment]
\HKEY_CLASSES_ROOT\batfile\shell\edit\command

**Comment by JasonStein** [comment]
Closing this since it is restricted by UWP app model policy.
