### ISSUE TITLE
[Bug]Wrong text render

### ISSUE THREAD

**Issue by MikiraSora** [JasonStein/Notepads#445]
**Describe the bug**
Wrong text rendering in last text line.

**To Reproduce**
Just open file and drag slider tick to end.

* File which is opening is personal file . I cant provide.

**Expected behavior**
Just seems good.

**Screenshots**
![image](https://user-images.githubusercontent.com/7549173/79194359-fde6ac00-7e5e-11ea-9ecd-5f53b84cd88a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1909 18363.720
 - Version v1.2.0.0 from Github Release Page provide

**Additional context**
Nope

**Comment by JasonStein** [comment]
Duplicate: https://github.com/JasonStein/Notepads/issues/373
