### ISSUE TITLE
选中文字的感觉很卡顿

### ISSUE THREAD

**Issue by tsogview** [JasonStein/Notepads#448]
相对于记事本和vscode,以及普通的网页上的文本编辑框来说,选中的感觉(动画)很卡顿,很掉帧.

最开始使用这个软件没有这种感觉,好像是哪次更新以后才有的感觉

**Comment by JasonStein** [comment]
有时候会这样，你重启一下应用或者系统就又好了，感觉是系统的问题，我遇到过几次。

**Comment by tsogview** [comment]
我并不是遇到几次,而是每次都会必定遇到.
重启(无论是应用还是pc)对我来说好想都没有明显的效果
掉帧的体验感觉真的很差.就好像机器卡卡的,但是实际上机器不卡
和记事本比是一个大缺点

**Comment by JasonStein** [comment]
可以录个屏嘛？然后是什么文件，多大的文件会这样？显卡是啥，系统版本呢？

**Comment by kasusa** [comment]
我可以明天录个屏～打开的文件是很小的那种。 我之前试过录制GIF.效果不好看着不明显.但是对于肉眼来说很明显.

不知道是不是我显示器是75hz的原因……（泰拉瑞亚在75hz就很卡.但是60hz就很流畅）

系统版本并不记得，我一直是保持最新的.我的显卡是gtx1050ti

**Comment by tsogview** [comment]
https://kasusa.lanzous.com/ibkb58f 这是录制的视频例子 , 3.8mb

**Comment by tsogview** [comment]
我去重现了一下,移动鼠标越快速,卡顿越明显.

**Comment by kasusa** [comment]
这是一个真的存在的,严重的使用体验问题!

**Comment by JasonStein** [comment]
我这边试了同样的文件 没有发现这个问题，我一个显示器100hz一个显示器50hz都没出现这个问题。。

**Comment by JasonStein** [comment]
你把这个文件发我试试？

**Comment by kasusa** [comment]
我认为不是文件的问题,我打开所有的,txt文档都有这个问题.
只要我选一个点,然后快速的来回拖动鼠标,就会很卡顿

**Comment by kasusa** [comment]
![cardview demo.gif](http://ww1.sinaimg.cn/large/0083vuQJly1ge16wjgf1mg30jn0i44qp.gif)

**Comment by JasonStein** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1166162/79819586-2418ba00-833f-11ea-9a13-c042c6d68448.gif)

**Comment by kasusa** [comment]
嗯... 这就很奇怪.
我这里就会非常卡顿.
但是除了这个软件以外的其他任何软件都不会有这样的问题.

**Comment by JasonStein** [comment]
系统版本？

**Comment by kasusa** [comment]
Microsoft Windows
1909〔OS内部本18363.778）

**Comment by kasusa** [comment]
我又去下载了其他的 fluent design的记事本应用... 都会卡

**Comment by JasonStein** [comment]
系统问题，UWP和你显卡或者系统什么设置有关系，你试着修复下系统，调整下dpi 设置下分辨率刷新率什么的，然后重启试试？

**Comment by JasonStein** [comment]
d

**Comment by kasusa** [comment]
你好,我现在买了一个新电脑,我认为这卡顿问题应该不是个例.
新电脑配置很高,驱动应该也没有问题,但是这个卡顿感仍旧存在
但是我发现了一个很重要的点,就是笔记本没有插入电源的时候才会有这种卡顿感，
插上了电源就不会有这种卡顿感了。
并且根据我的观察和文件的大小没有关系。

同样适用电池的时候在chrome的输入框和vscode中不会有选择的卡顿感。

**Comment by JasonStein** [comment]
> 你好,我现在买了一个新电脑,我认为这卡顿问题应该不是个例.
> 新电脑配置很高,驱动应该也没有问题,但是这个卡顿感仍旧存在
> 但是我发现了一个很重要的点,就是笔记本没有插入电源的时候才会有这种卡顿感，
> 插上了电源就不会有这种卡顿感了。
> 并且根据我的观察和文件的大小没有关系。
> 
> 同样适用电池的时候在chrome的输入框和vscode中不会有选择的卡顿感。

是节能模式还是普通电池模式？
