### ISSUE TITLE
[Bug] Searching stops on the first occurrence

### ISSUE THREAD

**Issue by entdark** [JasonStein/Notepads#45]
When you try to search in text, once it finds the first occurrence, it switches focus to the editor.

To reproduce the issue you need to just try to find some text, hit Enter to find the first occurrence, then hit Enter again, and then it will "replace" the found selected text with next line.

The expected behavior is try to search some text, hit Enter to find first occurrence, hit Enter again to find the next occurrence and so on with highlighting text in the editor with selection but without switching the focus to the editor. Once searching reaches the last element, it could either stop searching and notify that it reached the end, or cycle searching and start from the beginning. I am behind the 2nd way where it cycles searching.

OS: Windows 10 1809 17763.557
Version: v0.9.4.0

**Comment by JasonStein** [comment]
F3

**Comment by entdark** [comment]
Then it is very counter-intuitive behavior.
Compare to searching in many other programs: original Notepad, Sublime Text, Chrome, Edge, Visual Studio etc - all of them seek the next item on hitting Enter.

Also would be nice to have "Fine next" and "Find previous" buttons as text and/or as arrows at least, for accessibility for touch input at least.

**Comment by JasonStein** [comment]
On the other hand, all of them seek the next item on hitting F3, right? 
The reason "enter" works differently is purely because it is easy to implement. It took me only an hour to finish the whole "Find" UX. I will revisit this part later and hopefully I can have a much better find experience which should show all findings at once along with arrows that you mentioned.

**Comment by JasonStein** [comment]
This has been fixed, now you can continuously find/search using "Enter" key.
