### ISSUE TITLE
the Label default name

### ISSUE THREAD

**Issue by duzili** [JasonStein/Notepads#451]
**问题描述**
对于尚未保存的文件，默认标题都是新建文档.txt，是否可以参考SubLime，取文本首行作为标题，这样多个未保存的文档更容易区分
![image](https://user-images.githubusercontent.com/24836200/79722287-58c44b80-8316-11ea-82fb-29108d60a15a.png)
![image](https://user-images.githubusercontent.com/24836200/79722376-85786300-8316-11ea-9e17-ba7f0f7b85e7.png)

**Comment by JasonStein** [comment]
暂时的想法是以后的版本我会加入新建的时候选择文件类型txt/md和自取名字。你这个主意也很不错，我会权衡一下。

**Comment by duzili** [comment]
感谢回复，也期待未来的版本能支持！
