### ISSUE TITLE
为什么没有单独安装包[Feature request]

### ISSUE THREAD

**Issue by timaker** [JasonStein/Notepads#454]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by JasonStein** [comment]
<img width="1018" alt="Screen Shot 2020-04-21 at 8 23 25 AM" src="https://user-images.githubusercontent.com/1166162/79884025-7b537480-83a9-11ea-8b6a-9b9b8ff45dea.png">
