### ISSUE TITLE
我想卸载重新安装,可是不知道怎么卸载

### ISSUE THREAD

**Issue by rosyzc7** [JasonStein/Notepads#458]
能告诉我怎么卸载吗？
 谢谢
<img width="769" alt="20200423092719" src="https://user-images.githubusercontent.com/34859856/80049118-a920f080-8544-11ea-9c8f-c439818abfeb.png">

**Comment by JasonStein** [comment]
开始菜单里面搜索notepads，看到图标后对着图标点右键有一个删除按钮，按完就完全卸载了。

**Comment by JasonStein** [comment]
> 开始菜单里面搜索notepads，看到图标后对着图标点右键有一个删除按钮，按完就完全卸载了。
然后就是最新版本已经是1.2.4.0了，你咋还在用1.1.3.0
