### ISSUE TITLE
[Feature request] Render $...$ with math engine in markdown

### ISSUE THREAD

**Issue by Ghastlcon** [JasonStein/Notepads#469]
**Is your feature request related to a problem? Please describe.**
编辑 markdown 文件的时候内嵌的 $...$ 公式不能渲染

**Describe the solution you'd like**
为了保持引擎的简洁，用 mathjax 一类基于 js 的数学引擎应该是不可能了，可以考虑一下直接用 `https://www.zhihu.com/equation?tex=` 来渲染 svg？

**Describe alternatives you've considered**

**Additional context**

**Comment by JasonStein** [comment]
并不太想依赖第三方，特别是network ending，更何况是某乎。 一旦不可用或者路径改了，所有用户就用不了，我还得追着改和更新。这个markdown engine和parser很多人在community toolkit都有想法，后期应该会有动作。

**Comment by Ghastlcon** [comment]
除了某乎还有很多其他的老牌在线渲染，不过network ending确实是个问题大概，加油吧

发自我的 iPhone
