### ISSUE TITLE
[Bug] Tab does not close if the user was asked to save the file

### ISSUE THREAD

**Issue by AmionSky** [JasonStein/Notepads#47]
**Describe the bug**
When we close a tab with unsaved content it pops up the save dialog. If we chose to save the file it does not close the tab afterwards.

**To Reproduce**
Open notepads.
Type some text.
Press the "X" on tab.
Save the file.
Notepads is still open with the file.

**Expected behavior**
It should close the tab if the save was successful.

**Comment by JasonStein** [comment]
https://github.com/JasonStein/Notepads/commit/bd55a73794ccea95bffaff3348f78167926c12ab

**Comment by AmionSky** [comment]
Looks good
