### ISSUE TITLE
After Copy&Paste of Emoji the Text after the Emoji is wrong

### ISSUE THREAD

**Issue by Telmur** [JasonStein/Notepads#470]
**Describe the Bug**
If you paste this 🤷🏻‍♀ to Notepads, the whole text after the Emoji, until the next line, is garbage.

**To Reproduce**
Copy and Paste 🤷🏻‍♀ to your Notepads and type some text after it

**Expected behavior**
Text with the normal encoding

**Screenshots**
![image](https://user-images.githubusercontent.com/13147931/80685980-48576200-8ac8-11ea-8fe6-37530b298034.png)

**Desktop**
- Microsoft Windows [Version 10.0.18363.778]
- Notepads v.1.2.7.0

**Comment by JasonStein** [comment]
@be5invis This is only happing to notepads. I was wondering if it is related to the change you made last time:
https://github.com/JasonStein/Notepads/blob/06ba1427569978ff1b5fd8e2ac2bbd21ead4f3ad/src/Notepads/Controls/TextEditor/TextEditorCore.cs#L550

**Comment by JasonStein** [comment]
Fixed: 4d367c2

**Comment by jserodio** [comment]
I'm sorry but this is happening in the latest version for me as well.
https://github.com/JasonStein/Notepads/tree/v1.4.7.0

When I use windows + dot to write an emoji, when I start to write it makes weird characters.
![image](https://user-images.githubusercontent.com/5813094/160484834-949da7c6-b9aa-4769-b333-4a256ea74362.png)

Interestingly it doesn't always happen.
If I close and open the document again, it seems to be fixed somehow.

![image](https://user-images.githubusercontent.com/5813094/160484950-456ff22c-976e-4fa0-a005-191be0607159.png)

🧙🏻‍♂️ this one seemed problematic
![image](https://user-images.githubusercontent.com/5813094/160485460-ad914c3b-c1f0-40f7-a39a-501c4fe5473b.png)

Close and open...
![image](https://user-images.githubusercontent.com/5813094/160485513-0211294c-d62d-4a66-85c2-5222761041d3.png)

Can you guys try using this emoji? 🧙🏻‍♂️
