### ISSUE TITLE
[Feature request] Support custom snippets

### ISSUE THREAD

**Issue by lindexi** [JasonStein/Notepads#471]
**Describe the solution you'd like**

I can use my custom snippets.

如 SublimeText 一样，输入 ck[tab] 就替换为 ck 代码片内容

**Comment by JasonStein** [comment]
No...这个就过份了啊。。beyond scope了。。

**Comment by lindexi** [comment]
@JasonStein 哈哈

**Comment by lindexi** [comment]
@JasonStein 主要是刚才在写 MarkDown 的时候，在输入代码的时候，需要写入 \`\`\` csharp 这个代码比较重复
