### ISSUE TITLE
[Bug] Default Search Engine setting is reset on restart of Notepads

### ISSUE THREAD

**Issue by kompjoefriek** [JasonStein/Notepads#472]
**Describe the bug**
Every time Notepads is restarted, the Default Search Engine setting is reset to Bing.

**To Reproduce**
- Start Notepads
- Go to settings (F1)
- Select Google or Duck Duck Go as Default Search Engine.
- Close Notepads
- Start Notepads
- Go to settings (F1)
Default Search Engine has reset to Bing.
Doing the actual search will also use Bing.

**Expected behavior**
Default Search Engine setting remains set between application restarts.

**Desktop (please complete the following information):**
 - OS: Windows 10 1909 18363.815
 - Version v1.2.7.0

**Comment by JasonStein** [comment]
I don't see this issue on my machine. Can you check if this only happening to search engine settings or is it happening to other settings on your machine as well?

**Comment by beerisgood** [comment]
Can confirm that.

As suggest, i change another setting too (font size) and that works without problems.
But not so the search engine change

**Comment by JasonStein** [comment]
Looks like a bug here. I will fix it.

Side story: I used to work for Bing but I have no intention of forcing you guys to use Bing in anyway🤣

**Comment by JasonStein** [comment]
Ok, I found where the bug is and it will be fixed in the next release.
