### ISSUE TITLE
[Feature request] Associate notepads as git core.editor

### ISSUE THREAD

**Issue by jakubsuchybio** [JasonStein/Notepads#473]
**Is your feature request related to a problem? Please describe.**
Yes. I'd like to open notepads when I write commit message in git

**Describe the solution you'd like**
I want to associate notepads as git's core.editor in its .gitconfig
There is guide for associating some other editors:
https://help.github.com/en/github/using-git/associating-text-editors-with-git
I tried to set it to notepads, but it just opens untitled.txt

**Describe alternatives you've considered**
I still can use VS Code as main editor, but that has like 1-3sec startup time and I don't need any extensions for creating commit message. So I think notepads would be great fit.

**Additional context**
![image](https://user-images.githubusercontent.com/6567287/80748757-b67e4200-8b25-11ea-91dc-1c4edb871f29.png)

**Comment by jakubsuchybio** [comment]
Alright googled for some more and found that I need to open ```.git/COMMIT_EDITMSG``` file, but even with
```
[core]
	editor = notepads ./.git/COMMIT_EDITMSG
```
I get 
```powershell
C:\DokumentyGIT [master ≡ +1 ~0 -0 ~]> git ci
hint: Waiting for your editor to close the file... notepads ./.git/COMMIT_EDITMSG: /c/Users/jakub/AppData/Local/Microsoft/WindowsApps/notepads: Permission denied
error: There was a problem with the editor 'notepads ./.git/COMMIT_EDITMSG'.
Please supply the message using either -m or -F option.
```
But when I write
```
notepads ./.git/COMMIT_EDITMSG
```
directly into powershell it opens just fine :/

**Comment by jakubsuchybio** [comment]
Hmmm. Interesting I tried to run it through powershell and I made notepads crash :D 
```
[core]
	editor = powershell -Command "notepads .\\.git\\COMMIT_EDITMSG"
```
output of ```git commit```
```
C:\DokumentyGit [(master)]> git ci
hint: Waiting for your editor to close the file... error: There was a problem with the editor 'powershell -Command notepads .\.git\COMMIT_EDITMSG'.
Please supply the message using either -m or -F option.
```
And error from Event viewer:
```
Faulting application name: Notepads.exe, version: 1.0.0.0, time stamp: 0x5ea65f4e
Faulting module name: ntdll.dll, version: 10.0.18362.815, time stamp: 0xb29ecf52
Exception code: 0xc0000008
Fault offset: 0x000000000009feba
Faulting process id: 0x8bb8
Faulting application start time: 0x01d61f25c7ef2a93
Faulting application path: C:\Program Files\WindowsApps\19282JackieLiu.Notepads-Beta_1.2.7.0_x64__echhpq9pdbte8\Notepads.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: 2838f657-6e05-49b4-a0df-6c1d3ec6bbdc
Faulting package full name: 19282JackieLiu.Notepads-Beta_1.2.7.0_x64__echhpq9pdbte8
Faulting package-relative application ID: App
```

**Comment by JasonStein** [comment]
What about this:

[core]
	editor = powershell -Command "notepads"

Will this work with no exception?

**Comment by jakubsuchybio** [comment]
That also produces the same error in output and event viewer as last time :/

**Comment by jakubsuchybio** [comment]
I just read, that you are planning releasing WPF or UWP targetting Win Desktop which should remove limitations which might be causing this. 

I'm also wondering if this is somehow debugable. I'd attach debuger somehow, but when I'm not in control of creating notepads process because the git is, I am kinda lost, how can I help more.

But I like your product for quick fast lightweight edits for git commits and other stuff like using with https://github.com/jrnl-org/jrnl for creating journal entries and with https://github.com/jarun/buku for creating bookmarks.

**Comment by jakubsuchybio** [comment]
Ha I think I got it!!!
I found about debugging git commands like so in cmd:
```
set GIT_TRACE=true
git commit
```
outputs
```cmd
C:\DokumentyGIT>git ci
12:31:05.464177 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
12:31:05.465209 git.c:703               trace: exec: git-ci
12:31:05.465209 run-command.c:662       trace: run_command: git-ci
12:31:05.468217 git.c:381               trace: alias expansion: ci => commit
12:31:05.468217 git.c:764               trace: exec: git commit
12:31:05.468217 run-command.c:662       trace: run_command: git commit
12:31:05.474180 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
12:31:05.475179 git.c:439               trace: built-in: git commit
hint: Waiting for your editor to close the file... 12:31:05.737219 run-command.c:662       trace: run_command: GIT_INDEX_FILE=.git/index notepads C:/DokumentyGIT/.git/COMMIT_EDITMSG
error: There was a problem with the editor 'notepads'.
Please supply the message using either -m or -F option.
```
So I tried to execute that command by hand:
```cmd
notepads C:/DokumentyGIT/.git/COMMIT_EDITMSG
```
which didn't open that file and then it hit me to try it with windows backslashes and it worked. 

So the problem for core.editor for git is that it calls that editor with path which contains forward slashes.
I will try to look at it in notepads and try to create PR with the fix if I'm capable, if not I will have to leave it to you :(

**Comment by cw789** [comment]
One quick question, but thirst thanks for this very very great text editor.

So I can't get git default editor work with notepads.
I'm always stuck with: `hint: Waiting for your editor to close the file...`

For code there is the command line option `--wait` available to make it work.
Wouldn't notepads need something similar?

**Comment by palenshus** [comment]
I tried setting notepads as my default editor and had the same issue as described here:

	  > git config --global core.editor notepads.exe
	  > git commit
	  hint: Waiting for your editor to close the file...

notepads launches with ./.git/COMMIT_EDITMSG open as expected

I type commit message, save and close

Then I get his output:

	hint: Waiting for your editor to close the file... error: There was a problem with the editor 'notepads.exe'.
	Please supply the message using either -m or -F option.

@jakubsuchybio, how did you get this working? Thanks!

**Comment by jakubsuchybio** [comment]
Sadly i didn't get it working

**Comment by palenshus** [comment]
@JasonStein I think this issue is still present. Unless I'm missing something, can you re-open?
