### ISSUE TITLE
如果可以轻在右键菜单中加入使用notepads打卡，就和sublime text那样

### ISSUE THREAD

**Issue by Plaudern** [JasonStein/Notepads#496]
非常支持作者，如果不打算付费的话，可以考虑开一个打赏，让我们支持一下啊！！！
希望在未来可以在多平台可用，mac，linux，ios，android，windows，win uwp，加油啊作者

**Comment by Plaudern** [comment]
啊，有paypal链接啊，是我瞎了

**Comment by Plaudern** [comment]
还有要是能打开文件夹那就更好了

**Comment by JasonStein** [comment]
重复了，看下这两个issue：
https://github.com/JasonStein/Notepads/issues/362
https://github.com/JasonStein/Notepads/issues/287

打赏的话也挣不了钱，喜欢白嫖的人太多了，开源基本就等于别想挣钱了，而且我也没想靠这个挣钱，还是希望能更多用户喜欢吧，争取早日100万下载，这个比钱来的开心。
