### ISSUE TITLE
[Feature request] Ability to choose font style in addition to font (family).

### ISSUE THREAD

**Issue by Diego251** [JasonStein/Notepads#497]
**Is your feature request related to a problem? Please describe.**
Not related to a problem, purely improvement.

**Describe the solution you'd like**
In addition to being able to select the font (ex. Iokseva Fixed), possibility to see and set the font styles (variants) as well for the same family (ex. medium, regular, light, etc.).

**Describe alternatives you've considered**
Using another font :)

**Additional context**
n/a

**Comment by JasonStein** [comment]
I do have a plan to add both "Font Style" and "Font Weight" to the settings. It will probably be part of the next release.

**Comment by JasonStein** [comment]
Done: https://github.com/JasonStein/Notepads/commit/c018bc79fe26fcf1b37b2fcd12d738495c0d074d

![image](https://user-images.githubusercontent.com/1166162/81401554-6afb0380-90e4-11ea-90f3-74b9de9de342.png)
