### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by Arvinzhg** [JasonStein/Notepads#503]
增加xml与json文件的格式化功能，对应{}选中一半另一半也高亮提示，还有支持大于1M文件的支持

**Comment by JasonStein** [comment]
除了最后一个，前两个都是让Notepads增加代码编辑器的功能，但是notepads不是代码编辑器，写代码请用VS Code或者别的正常IDE，最后一个跟微软有直接关系，所以很难答复，楼下很多帖子讨论的。
