### ISSUE TITLE
Project folder sidebar

### ISSUE THREAD

**Issue by tawissus** [JasonStein/Notepads#506]
Hello,

it would be great to get a sidebar with files of a project folder.
This would allow me to access my files faster without having to open a separate window.

Best
Guido

**Comment by JasonStein** [comment]
No, if that bothers you, use a proper IDE like VSCode. Notepads is a lightweight plain text editor not a full blown IDE.

**Comment by tawissus** [comment]
Yes. I agree with you, but I don't think the IDE comparison works for me.

For example, I use a folder with 15-20 text files.  For some files an IDE is overloaded and slow.  I would only need a small list without much ballast.  With this extension you could surely please some users.

**Comment by Teraskull** [comment]
> Yes. I agree with you, but I don't think the IDE comparison works for me.
> 
> For example, I use a folder with 15-20 text files. For some files an IDE is overloaded and slow. I would only need a small list without much ballast. With this extension you could surely please some users.

Again, use VS Code, it's not an IDE, and has all the features you need without being too "overloaded".

**Comment by JasonStein** [comment]
Closing this thread for now since I do not have plan to implement this feature.
