### ISSUE TITLE
Collecting ideas

### ISSUE THREAD

**Issue by JasonStein** [JasonStein/Notepads#511]
Do you guys prefer A, B, C or keep it as it is when line highlighter is enabled and when multiple lines are selected?

A:

![image](https://user-images.githubusercontent.com/1166162/81463571-4ac45680-916f-11ea-98a5-7436516eeb05.png)

B:

![image](https://user-images.githubusercontent.com/1166162/81463595-73e4e700-916f-11ea-8d72-338ad5467c08.png)

C:

![image](https://user-images.githubusercontent.com/1166162/81463670-12714800-9170-11ea-831a-052e6b0ea738.png)

Current: 

![image](https://user-images.githubusercontent.com/1166162/81463615-96770000-916f-11ea-8831-ff6d149725f1.png)

**Comment by JasonStein** [comment]
I will go "C" if I don't get enough response.

**Comment by RudeTheJack** [comment]
Please add right click option

**Comment by soumyamahunt** [comment]
C looks nice to me.

**Comment by pinholucas** [comment]
C is more beauty and logical

**Comment by narfanar** [comment]
A, C :T

**Comment by JasonStein** [comment]
I will stick with C and closing this thread for now.
