### ISSUE TITLE
Don't have any markdown preview

### ISSUE THREAD

**Issue by med44600** [JasonStein/Notepads#522]
Hi,
I just discover your nice App. Great work.
I have a new fresh install from Windows Store, but I couldn't get any markdown preview!? 
What should i do to get it work? I didn't even have it in the Menu

![image](https://user-images.githubusercontent.com/58919432/81533753-07343d00-9367-11ea-8627-19798bd56a32.png)

**Comment by JasonStein** [comment]
Open any .md or .markdown file.
