### ISSUE TITLE
[Feature request]White checked background in dark mode is recommended,建议在深色模式下采用白色的选中底色

### ISSUE THREAD

**Issue by Kingfish404** [JasonStein/Notepads#526]
深色模式下，字符选中后的底色不够明显
In dark mode, the negative color after the character is selected is not noticeable enough

建议在深色模式下采用白色的选中底色
White checked background in dark mode is recommended

![image](https://user-images.githubusercontent.com/49345832/81684540-a2253800-9489-11ea-9566-2880fec9743e.png)

**Comment by JasonStein** [comment]
![image](https://user-images.githubusercontent.com/1166162/81720339-213b5180-9433-11ea-8890-e3b129784e74.png)
