### ISSUE TITLE
[Bug] Some bash files have missing icons

### ISSUE THREAD

**Issue by Teraskull** [JasonStein/Notepads#550]
**Describe the bug**
Some bash files have missing icons and can not be opened with Notepads.

**To Reproduce**
Create a file with one of the names in the screenshot.

**Expected behavior**
The files with missing icons should be opened with Notepads and have the same icon as the .bash or .bash_history file.

**Screenshots**
![image](https://user-images.githubusercontent.com/24798198/82508195-99290c00-9b04-11ea-86b6-650dff371524.png)

**Desktop:**
 - OS: Windows 10 1909 18363.836
 - Version: v1.3.4.0

**Comment by JasonStein** [comment]
I added those recently, will be there in next release.
