### ISSUE TITLE
[Feature request] highlight current line 高亮当前行能提供颜色填充当前行吗？

### ISSUE THREAD

**Issue by MXTvc** [JasonStein/Notepads#553]
![image](https://user-images.githubusercontent.com/44336929/82719887-0db8a200-9ce1-11ea-8e3b-d4c647aecc62.png)
像这样

**Comment by JasonStein** [comment]
![image](https://user-images.githubusercontent.com/1166162/83297059-bca82280-a1a6-11ea-9786-f8ba344ce039.png)
