### ISSUE TITLE
[Bug] Lag When Opening Big Files

### ISSUE THREAD

**Issue by validatedev** [JasonStein/Notepads#571]
**Describe the bug**
The app is lagging when opening relatively large files < 1MB, classic Notepad, and Sublime Text have not that problem.

**To Reproduce**
Open a file > 500KB

**Expected behavior**
The file should be open quickly.

**Screenshots**
[video.zip](https://github.com/JasonStein/Notepads/files/4708286/video.zip)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 2004 19041.264]
 - Version [e.g. v1.3.7.0]

**Comment by JasonStein** [comment]
Yeah, known issue to WinRT RichEdit.
