### ISSUE TITLE
[Bug] Menu quits immediately

### ISSUE THREAD

**Issue by KristofKekesi** [JasonStein/Notepads#577]
I opened the menu, and clicked the (idk what is "Állapotsor" in english) and the menu closed itself.

**To Reproduce**
Open the menu and

**Expected behavior**
do not exit

**Screenshots**
![bug](https://user-images.githubusercontent.com/64812024/83864496-1a97b580-a725-11ea-8c14-bca39a83e0c6.gif)

**Desktop (please complete the following information):**
 - OS: Win10 1903 (x64) build: 18362.836
 - Version: 1.3.4.0

**Comment by JasonStein** [comment]
Known issue, won't fix since no one will ever switching status bar that often.
