### ISSUE TITLE
[Feature request] Add a hotkey for "Word Wrap"

### ISSUE THREAD

**Issue by alexanderkozlenko** [JasonStein/Notepads#58]
**Is your feature request related to a problem?**

I'd like to turn on and turn off word wrapping for a current document via a hotkey (e.g., "Alt+Z" in Visual Studio Code).

**Describe the solution you'd like**

Add a hotkey for existing feature "Word Wrap".

**Comment by JasonStein** [comment]
https://github.com/JasonStein/Notepads/commit/4d92b3caa1decc8028e71def5037f15f3aa63d87
It will be available in v0.9.5.0🎉

**Comment by JasonStein** [comment]
![image](https://user-images.githubusercontent.com/1166162/61162240-97da8c00-a4bc-11e9-949b-2311afc5275a.png)

**Comment by alexanderkozlenko** [comment]
Thank you!
