### ISSUE TITLE
[Feature request] A language option

### ISSUE THREAD

**Issue by obskyr** [JasonStein/Notepads#584]
I'd like to revisit #498, for some reasons that I will elaborate on!

You see, Notepads is in *Japanese* for me, because I have a Japanese keyboard installed. While I can read Japanese, it's much slower than English, and there are some complicated characters here and there that I need to look up. It makes Notepads quite impractical.

One might think I can add English to my list of system languages and prioritize it over Japanese, but I can't: adding a language also adds a keyboard layout, and since I'm Swedish, I have no use for a North American keyboard layout, and it only adds entries I have to toggle through manually every time I want to switch between Swedish and Japanese input. This wouldn't be an issue if Notepads had an independent language option.

For reference, I took survey of a few other text editors (Notepad++, Kate, Gedit, Geany, and Notepadqq), which all had an independent language option.

In essence: changing the language of Windows leads to undesired side effects for your entire operating system – in my opinion, changing your operating system shouldn't be required just to use Notepads.

**Comment by JasonStein** [comment]
![image](https://user-images.githubusercontent.com/1166162/84532381-03177a00-ac9b-11ea-9a5e-cdb98823bc0d.png)

Added option to switch app language in advanced settings (only supported languages installed on your system will be shown).

For example, you need to install Japanese language pack in Windows 10 settings before you can use it as Notepads app display language. This is controlled and forced by the system.

**Comment by obskyr** [comment]
Lovely! It works perfectly! Thanks a bundle for implementing it!
