### ISSUE TITLE
[Bug]Slow when inserting new lines on bigger text file

### ISSUE THREAD

**Issue by teebu** [JasonStein/Notepads#587]
**Describe the bug**
A file with 7000 lines of text (~200kb text file) makes notepads slow when creating new lines. 

**To Reproduce**
Get a big enough text file, hit enter in the beginning, middle or end of file..

**Expected behavior**
Smooth non-laggy behavior, like a small new text file.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 2004
 - Version 1.3.8.0

**Additional context**

**Comment by JasonStein** [comment]
Known issue of WinRT RichEdit, nothing I can do at this point.

**Comment by teebu** [comment]
That is unfortunate. I liked the simplicity of this app. I'll check back later if anything changes.
