### ISSUE TITLE
[Feature request]Make icon similar to new fluent design concepts

### ISSUE THREAD

**Issue by milindgoel15** [JasonStein/Notepads#588]
Hi, since new style of windows 10 tile icons are coming, it would be awesome to see notepads app with the same background as other ones. example all the office icons, some certain microsoft icons which already got. 

Right now, i am having an icon with accent background which i dont like to be honest. Attaching a screenshot so that you can get idea what i mean.
![Annotation 2020-06-12 161351](https://user-images.githubusercontent.com/45682747/84495139-4c31f300-acc8-11ea-808a-e0c3ed8d0c99.png)

If the new icon is already implemented and its an option made for it, kindly direct me the location as i was unable to look it.

**Comment by JasonStein** [comment]
I made it the same grayish color few weeks ago and a lot of users don't like it that way. They prefer accent color. I will not change it until Microsoft can provide a solution for user to choose or forcibly make everything white/dark background. Otherwise it will be a mess since you will anyway have apps that use accent color.

**Comment by milindgoel15** [comment]
Me cri😭

It's not possible to add a toggle or something to switch between the icons? Like people who want accented can leave the toggle to be off, rest can enable.

**Comment by JasonStein** [comment]
> Me cri😭
> 
> It's not possible to add a toggle or something to switch between the icons? Like people who want accented can leave the toggle to be off, rest can enable.

No... there is no such option in the system setting yet and app can only declare one color.

**Comment by KristofKekesi** [comment]
If you make two programs? Haha Notepads Accent

Dont take it seriously
