### ISSUE TITLE
Support .nfo files

### ISSUE THREAD

**Issue by ArtexJay** [JasonStein/Notepads#589]
**Describe the solution you'd like**
Have support to view .nfo files within the app, this would be very useful for me to view nfo directly withint the app.

**Comment by JasonStein** [comment]
.nfo is already supported:
![image](https://user-images.githubusercontent.com/1166162/84556549-64117300-acd8-11ea-83f5-8e192376ffae.png)

**Comment by ArtexJay** [comment]
Oh damn I didn't see that!
