### ISSUE TITLE
[Bug]输入中文双引号时，会自动选中后引号，而非将光标插入在前后引号之间。

### ISSUE THREAD

**Issue by suyangzuo** [JasonStein/Notepads#591]
**Bug描述**
输入中文双引号时，会自动选中后引号，而非将光标插入到前后引号之间。
我试了其它很多文本编辑器，光标都是正常插入在前后引号之间的，只有Notepads有这个问题。

**复现**
使用百度输入法，输入中文双引号，则自动选中后引号，但实际上光标应该插入在前后引号之间。

**预期改善结果**
输入中文双引号时，光标应位于前后引号之间。

**截图**
![333](https://user-images.githubusercontent.com/50766353/84581836-e05ea000-ae17-11ea-8ba8-ce010f9aec75.png)

**桌面信息**
 - 操作系统: [Windows 10 2004 19041.329]
 - 版本 [v1.3.9.0]

**附加信息**
这个问题我记得大概在1.1.2.0的时候就出现了。

**Comment by JasonStein** [comment]
百度输入法的问题吧？微软输入法我这没法复现。

**Comment by suyangzuo** [comment]
> 百度输入法的问题吧？微软输入法我这没法复现。

我试了一下，微软输入法的前后引号是要依次输入的。百度输入法输入前引号，后引号会自动补全。

**Comment by JasonStein** [comment]
> > 百度输入法的问题吧？微软输入法我这没法复现。
> 
> 我试了一下，微软输入法的前后引号是要依次输入的。百度输入法输入前引号，后引号会自动补全。

那就是百度输入法的问题了，投诉一下他们:) 另外为啥要用百度，无药可救公司。
