### ISSUE TITLE
Text icon when using the scroll bar

### ISSUE THREAD

**Issue by sertincho** [JasonStein/Notepads#592]
**Describe the bug**
when positioning on the scroll bar, the cursor is the text selection

**To Reproduce**
move the cursor to the scroll bar

**Expected behavior**
see arrow icon

**Screenshots**
https://i.imgur.com/MPP9g1y.png

**Desktop (please complete the following information):**

Windows 10 1909 v18363.900

**Comment by JasonStein** [comment]
This is a Windows 10 issue.

**Comment by sertincho** [comment]
Oh ok, thanks @JasonStein
