### ISSUE TITLE
[Feature request] Use format string for the resource that have word order

### ISSUE THREAD

**Issue by pnp0a03** [JasonStein/Notepads#60]
In sentence, order of the words are vary with each languages.
If the resource have some of word order, best practice is using the format string like as "Ln {0} Col {1}".
I've noticed that 2 cases.

1) "Ln Col" at the status bar. In English, the order is "Ln 2" but some language is "2 行", etc.

Screencapture - The black is a Notepads. The white one is a Notepad.exe, in Japanese. You can see "2行 4列".
![image](https://user-images.githubusercontent.com/10514567/61164448-2f3cef00-a550-11e9-9f1a-a5c6ffd9fa15.png)

2) FileOpenErrorDialog and FileSaveErrorDialog: It contain the sentence that was divided to the part1 and part2. This order vary with languages. If the resource is defined as "File {0} couldn't be saved.", translators can modify it to suitable for the languages.

**Comment by JasonStein** [comment]
Yes, I should use formatted string, and your case applies to Chinese as well. I will do the work tonight.

**Comment by JasonStein** [comment]
This is the commit to use format string for your second suggestion:
https://github.com/JasonStein/Notepads/commit/c191cf6cf522bdd00e5fc0436df4fef4baf419b0

**Comment by JasonStein** [comment]
And this one is for the line/column indicator text:
https://github.com/JasonStein/Notepads/commit/09335683ba91eec627277973e92099ffa522273c
