### ISSUE TITLE
[Feature request] Add the ability to disable acrylic on text box

### ISSUE THREAD

**Issue by Senko-Dev** [JasonStein/Notepads#604]

**Comment by JasonStein** [comment]
![image](https://user-images.githubusercontent.com/1166162/85888316-37605f80-b79e-11ea-9479-d3b141930163.png)
Setting it to 100% will disable the acrylic completely.

**Comment by Senko-Dev** [comment]
That doesn't do the desired effect.

**Comment by JasonStein** [comment]
> That doesn't do the desired effect.

What do you mean? If you set it to 100%, the code behind will swap the background with solid color brush and will eventually disable acrylic at all. Can you share screenshot and example that you want to achieve?

**Comment by Senko-Dev** [comment]
What I want to achieve is disabling acrylic on the text area.

**Comment by JasonStein** [comment]
![image](https://user-images.githubusercontent.com/1166162/85934917-c5237400-b89e-11ea-8353-3e6cbd1c1120.png)
Where? These is no acrylic in above screenshot.

**Comment by Senko-Dev** [comment]
I only want to remove textbox acrylic
