### ISSUE TITLE
Copy/Cut whole line when nothing selected with cursor

### ISSUE THREAD

**Issue by michaellewiswilson** [JasonStein/Notepads#620]
In many text editors and IDEs, if you have nothing selected with the cursor and press ctrl-c or ctrl-x, it will copy or cut the current line that the cursor is on.  I consider Notepads to be a very lightweight text editor, and I think it should also support this feature.

**Comment by gmaza** [comment]
I think this feature is important, so I created PR #622

**Comment by JasonStein** [comment]
Closing this thread since this feature is shipped.
