### ISSUE TITLE
[Bug] Preview in mardown ignores <br>

### ISSUE THREAD

**Issue by ItzNeviKat** [JasonStein/Notepads#625]
**Describe the bug**
If edit .md file, I can preview it. But all \<br\> tags in preview do not wrap text to the next line and remain visible

**To Reproduce**
1. Create markdown file (example.md)
2. Write text, \<br\> tag and again text
3. Right-Click to open preview
4. Bug in preview!

**Expected behavior**
The \<br\> tag is not visible, text wrapping successfulity.

**Screenshots**
Bug:
![image](https://user-images.githubusercontent.com/24193020/88175631-ca21dc00-cc2e-11ea-916d-9b27b422cdc8.png)

Expected behavior:
![image](https://user-images.githubusercontent.com/24193020/88175697-e6257d80-cc2e-11ea-9091-17b18df5a9d2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 1909 18363.959
 - Version: v1.3.9.0

**Comment by ianpan870102** [comment]
Have you tried `<br />` instead?

**Comment by JasonStein** [comment]
html tags are not supported.
