### ISSUE TITLE
[Feature request] Shift + Enter to go to previous search result

### ISSUE THREAD

**Issue by MarcAnt01** [JasonStein/Notepads#630]
**Is your feature request related to a problem? Please describe.**
I like to quick jump among search results using keyboard

**Describe the solution you'd like**
The shortcut I have suggested

**Describe alternatives you've considered**
None

**Additional context**
Not needed

**Comment by soumyamahunt** [comment]
You can use Shift+F3 for going to previous search result, any specific reason you want Shift+Enter??

**Comment by MarcAnt01** [comment]
I think Shift + Enter is more intuitive, Unigram for example has this shortcut

**Comment by ianpan870102** [comment]
> I think Shift + Enter is more intuitive,

I second this idea. Shift + Enter is also supported in many modern browsers (at least in Chrome/Chromium/Brave/Edge etc.) and also most state-of-the-art editors.

**Comment by MarcAnt01** [comment]
I'd add also some IDE like Visual Studio have that

**Comment by ianpan870102** [comment]
Also Visual Studio Code, Sublime Text, Atom, and the whole Jetbrains family.

**Comment by soumyamahunt** [comment]
Imemented in #634
