### ISSUE TITLE
I think it should have auto-save capability

### ISSUE THREAD

**Issue by ProfessorZhang** [JasonStein/Notepads#633]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MikeLabatt** [comment]
If it had not just "auto-save", but also if it could preserve/restore windows and tabs and saved/unsaved/draft file states across reboots (Windows Update) and crashes (loss of power, Blue Screen), it would be _the_ killer app for me. EmEditor can do this very well, but it's a bit overbloated, so I end up using Notepad a lot, and occasionally losing data.

**Comment by soumyamahunt** [comment]
> If it had not just "auto-save", but also if it could preserve/restore windows and tabs and saved/unsaved/draft file states across reboots (Windows Update) and crashes (loss of power, Blue Screen), it would be _the_ killer app for me. EmEditor can do this very well, but it's a bit overbloated, so I end up using Notepad a lot, and occasionally losing data.

It can already do that. You have to enable "Session Snapshot" in advanced settings. Also, only tabs from the first launch window is backed up.

**Comment by JasonStein** [comment]
Closing this thread since "Session snapshot" can fit your same need.
