### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by asharonbaltazar** [JasonStein/Notepads#637]
**Describe the bug**
New Tab tooltip constantly visible. 

**To Reproduce**
I opened an existing file. 

**Expected behavior**
There shouldn't be a tooltip

**Screenshots**
![image](https://user-images.githubusercontent.com/58940073/89133540-4eebe000-d4e2-11ea-9e0b-7a3e75c2d023.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 2004

**Additional context**

**Comment by JasonStein** [comment]
I am pretty sure this tooltip is coming from your browser app (chrome or chromium edge) not notepads.
