### ISSUE TITLE
[Bug] Jumping dot in preview of markdown - ordered list 

### ISSUE THREAD

**Issue by michalsieron** [JasonStein/Notepads#641]
**Describe the bug**
Dot after number in ordered list jumps to next line in preview.

**To Reproduce**
1. Create new markdown document
2. Type `1. ` (one -> dot -> space)
3. Open preview (can open before typing, same result)
4. See bug

**Expected behavior**
Dot should not jump to next line

**Screenshots**
![image](https://user-images.githubusercontent.com/54780569/89402866-c5bdee80-d717-11ea-869b-40c96ed4e251.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 19041.423
 - Version: v1.3.9.0

**Comment by JasonStein** [comment]
Did you enable "word wrap"?

**Comment by michalsieron** [comment]
Yup, seems to be it. When disabled it works as expected

**Comment by michalsieron** [comment]
Because I don't know whether I should close this issue I will ask: 
Is it expected behaviour or is it something that won't be fixed? 
If such, I will close the issue.

**Comment by JasonStein** [comment]
> Because I don't know whether I should close this issue I will ask:
> Is it expected behaviour or is it something that won't be fixed?
> If such, I will close the issue.

I think this is expected and it is a behavior comes with Windows RichEdit.
