### ISSUE TITLE
[Bug] Spanish translation mistake 

### ISSUE THREAD

**Issue by alangadiel** [JasonStein/Notepads#642]
There is a mistake in the spanish translation.
It is found in the alert that appears when you try to close the app with unsaved files.
One of the words in the alert is incorrectly translated.

It says: "Hay errores sin guardar".
It should say: "Hay cambios sin guardar".

Screenshot:
![image](https://user-images.githubusercontent.com/22394742/89465632-d044ac00-d748-11ea-86b2-493003d43bc9.png)

 - OS: Windows 10 Pro 2004 19041.388
 - Version 1.3.9.0

**Comment by JasonStein** [comment]
Fixed: https://github.com/JasonStein/Notepads/commit/253891ab45f10d8df23e47df68b7295f9a47a685
