### ISSUE TITLE
Installation package problem

### ISSUE THREAD

**Issue by Habit-hash** [JasonStein/Notepads#644]
I like this software very much, but I have no way to install it because there is no Microsoft Store in my computer. I hope that more installation methods can be added in the future.

**Comment by soumyamahunt** [comment]
You can get the installer in the releases page. Also, you can use `winget` to install notepads too.

**Comment by JasonStein** [comment]
winget install notepads

**Comment by obeho** [comment]
Hello, could an .exe be provided for installation?

I'm facing an error on downloading `Notepads_1.4.2.0_x86_x64.msixbundle`
`App Installer failed to install package dependencies. Ask the developer for Microsoft.NET.Native.Runtime.2.2 package.`
This probably has got nothing to do with this app.

**Comment by survivor303** [comment]
we need chocolatey support too :/
