### ISSUE TITLE
[Bug]Render Error

### ISSUE THREAD

**Issue by mincoft** [JasonStein/Notepads#646]
**Describe the bug**
The text will have some wrong with line **_12079_**,and won't render text after line **_12079_**.

**To Reproduce**
1.New a file
2.put lot str in a line,and copy this line a lot .
3.Line**_12079_** will start render at half **_12078_**,and llines after **_12079_** won't render

**Expected behavior**
Will render normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/32572293/89711022-3be18000-d9ba-11ea-8be8-6c09a2131fd9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 10.0.18363.9
 - Version v1.3.9.0

**Additional context**
my testing file.
[test.txt](https://github.com/JasonStein/Notepads/files/5045264/test.txt)

**Comment by hackslashX** [comment]
Hi! Notepads has a file size limitation of 1 MiB, hence the rendering errors. Please check the README for more information.

**Comment by JasonStein** [comment]
Known issue for now. It won't be fixed anytime soon but I am keeping an close eye on it already. Btw, we have an existing thread already.
