### ISSUE TITLE
Enable ESC to be a close operation

### ISSUE THREAD

**Issue by timheuer** [JasonStein/Notepads#647]
Give me a config option to enable ESC as a close option.

**Comment by JasonStein** [comment]
"Ctrl + W" is good enough and I don't see a great need of adding one-click ESC to close the tab for general user. Also, it might cause some trouble to our users since the mis-clicking chance is way higher.

**Comment by timheuer** [comment]
Notepad++ has this option and is what I use to quickly navigate off the notepad.  This combined with auto-save makes it faster than two-key shortcuts for keyboard users.
