### ISSUE TITLE
[Feature request]Add "Save all" keyboard shortcut?

### ISSUE THREAD

**Issue by Boshelius** [JasonStein/Notepads#648]
Maybe not a bad idea to add keyboard shortcut for the save all function. That way all the menu functions will be kbd accessed.

**Comment by JasonStein** [comment]
No, the reason I have not added shortcut to save all is that user might accidentally click it while having tons of tabs opened in the meantime, which can be a lot of mess and causing unwanted trouble to users. The need of "save all" is relatively low and you can always open the menu and just click it.
