### ISSUE TITLE
关闭“Always open new window”之后，还是想打开更多的窗口😆[Feature request]

### ISSUE THREAD

**Issue by Fred-Qhin** [JasonStein/Notepads#656]
我关闭 “Always open new window” 之后，但是开了十几个 tab，我想把其中几个放到另一个窗口中，但是我试着拖动没办法创建另一个窗口。

希望可以向浏览器一样，拖动 tab，可以创建一个新的窗口

**Comment by JasonStein** [comment]
你可以先打开一个新的window 然后就可以把现有的tab拖拽过去了。
