### ISSUE TITLE
选择了 Yu Gothic UI 字体后软件崩了[Bug]

### ISSUE THREAD

**Issue by RichardQ12138** [JasonStein/Notepads#657]
**Describe the bug**
选择了 Yu Gothic UI 字体后软件就崩溃了，重启软件之后还能使用，但是再次修改字体时还是会崩溃

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1809 18363.959]
 - Version [e.g. v1.3.9.0]

**Comment by JasonStein** [comment]
有字体文件嘛？这应该是win2d的bug (Windows问题)

**Comment by RichardQ12138** [comment]
卸载重装之后好了😂




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JasonStein/Notepads"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月1日(星期二) 凌晨1:36
收件人:&nbsp;"JasonStein/Notepads"<Notepads@noreply.github.com&gt;;
抄送:&nbsp;"一渊源"<1442884718@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [JasonStein/Notepads] 选择了 Yu Gothic UI 字体后软件崩了[Bug] (#657)





 
有字体文件嘛？这应该是win2d的bug (Windows问题)
