### ISSUE TITLE
[Bug]Files edited with notepads are marked as unsigned or untrusted by Windows

### ISSUE THREAD

**Issue by rekaerst** [JasonStein/Notepads#659]
**Describe the bug**
Any file that was edited with notepads is marked as unsigned or untrusted just like files you downloaded from the internet.
This will prevent the execution of some scripts edited with notepads. 
**To Reproduce**
Edit file with notepads and save it

**Expected behavior**
Files edited with notepads should not be marked as untrusted

**Screenshots**
ps1 file from my local file system 
![image](https://user-images.githubusercontent.com/52642831/90381046-6b297880-e0af-11ea-9d39-f3ee1b9bf503.png)
windows requires unlocking to use this file
![image](https://user-images.githubusercontent.com/52642831/90381170-91e7af00-e0af-11ea-9787-a6ba6cc1905b.png)
**Desktop (please complete the following information):**
 - OS: Windows_NT 10.0.19041.388 amd64
 - Notepads Version 1.3.9.0

**Additional context**
IMO, this could be a common issue with UWP apps but some applications such as Windows Terminal indeed solved it.

**Comment by XamDR** [comment]
AFAIK, Windows Terminal is a classic Win32 application and it uses Xaml Islands to host the UWP's TabView control.

**Comment by JasonStein** [comment]
Unknown issue(security limitation) to all UWP apps.
