### ISSUE TITLE
[Feature request]可以添加鼠标右键打开么？

### ISSUE THREAD

**Issue by asunlight** [JasonStein/Notepads#664]
感觉这样更方便一些

**Comment by Vixb1122** [comment]
你打开方式里面选择该应用，就能双击文件打开了。
![image](https://user-images.githubusercontent.com/17810492/91469584-262eee80-e8c6-11ea-8771-458d519011f1.png)

**Comment by JasonStein** [comment]
Windows 10 v2004或者以上版本都支持选择任意UWP app， 如上图老哥所示。

**Comment by asunlight** [comment]
找到了，谢谢。但有些扩展名的文件，虽然也是文本，但是找不到右键打开。。。
