### ISSUE TITLE
[Bug] Incomplete functionality when highlighting misspelled words

### ISSUE THREAD

**Issue by XamDR** [JasonStein/Notepads#667]
**Describe the bug**
When the option to highlight spell check errors is enabled, it only highlights the misspelled word, but it doesn't give a list of suggestions to fix the error. As an user I find this kind of behavior counter-intuitive because I expect to have the whole highlight and suggest experience, similar to how other programs do like Word or Edge Chromium. Currently, it feels like the mentioned functionality is incomplete.

**To Reproduce**
1. Toggle on the option to highlight misspelled words.

**Expected behavior**
The misspelled words should be underline with the classical red wavy underline and right clicking on it should display a list of suggestions, the option to add to the dictionary or to ignore the word, in the text editor's context menu.

**Screenshots**
For example, while I was redacting this issue, I misspelled a word and this is what Edge did:

![image](https://user-images.githubusercontent.com/35734934/91469225-bb939980-e858-11ea-8a9c-f19bc3f693d4.png)

In contrast, this is what Notepads does:

![image](https://user-images.githubusercontent.com/35734934/91470044-d1558e80-e859-11ea-9ca5-647a94c4330a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1909 18363.1016
 - Version: v1.3.9.0

**Additional context**
I've checked the code of the file `TextEditorContextFlyout.cs` and I found a way to fix the issue described above using the `RichEditBox`'s `ProofingMenuFlyout` property. And if it's necessary, I would like to summit a pull request.

**Comment by soumyamahunt** [comment]
> And if it's necessary, I would like to summit a pull request.

Feel free to do that.

**Comment by XamDR** [comment]
> > And if it's necessary, I would like to summit a pull request.
> 
> Feel free to do that.

Ok thanks. I will do ASAP.
