### ISSUE TITLE
[Feature request] 强烈请求添加语法高亮

### ISSUE THREAD

**Issue by Lujiusi** [JasonStein/Notepads#671]
作者
有准备为这个编辑器添加语法高亮吗.
请为这个python, java, shell ,xml ,yaml,sql 等文件添加语法高亮功能
另外关于文件最大1M的问题
作者给微软发送的反馈有结果了吗,
很喜欢这个软件,如果这两个问题,我就可以卸载notepad++这个反华软件了

**Comment by JasonStein** [comment]
语法加亮可能暂时或者未来一年都不会支持，抱歉哈，并没有这个想法。
