### ISSUE TITLE
[Bug] Wrong copy/cut behaviour when text was selected from right to left

### ISSUE THREAD

**Issue by Namerif** [JasonStein/Notepads#673]
**Describe the bug**
When I select text from left to right, all copy/cut commands work perfectly. But when it is selected from right to left, these commands copy/cut the whole line instead of selected text.

**To Reproduce**
1) Open file with text
2) Select text from right to left
3) Press Ctrl+X

**Expected behavior**
If I select some text and then press Ctrl+C/Ctrl+X, I expect that only selected text will be copied. The whole line must be copied/cut only if no text was selected.

**Desktop (please complete the following information):**
 - OS: Windows 10 1903 18362.1016
 - Version 1.4.0.0

I added video with this bug to attached .zip archive.
[NotepadsTextSelectionBugVideo.zip](https://github.com/JasonStein/Notepads/files/5155424/NotepadsTextSelectionBugVideo.zip)

![изображение](https://user-images.githubusercontent.com/43481731/91835592-45c17080-ec52-11ea-8a3e-17dbbc04735a.png)

**Comment by JasonStein** [comment]
Good catch, this is a bug introduced by the latest version, it will be fixed in the next release.

https://github.com/JasonStein/Notepads/commit/a6a26b594dfc4cdbe3a5f250e155fab67d1fb7f4
