### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by SalimHashisho254** [JasonStein/Notepads#675]
Please add a zooming feature. For example, by swiping in different directions in my touchpad or pressing ctrl and scrolling the wheel, I can zoom in and out. It will also be cool if we can use multiple fonts or sizes in the note.

**Comment by soumyamahunt** [comment]
I don't get the point of this feature request, @SalimHashisho254 all the features you describes are already available.

**Comment by SalimHashisho254** [comment]
> I don't get the point of this feature request, @SalimHashisho254 all the features you described are already available.

Oh I'm sorry I didn't realize that; it just doesn't work for me. I can only zoom by pressing the zoom percentage at the bottom and moving the slider. I can't zoom using my touchpad or mouse.

**Comment by soumyamahunt** [comment]
> Oh I'm sorry I didn't realize that; it just doesn't work for me. I can only zoom by pressing the zoom percentage at the bottom and moving the slider. I can't zoom using my touchpad or mouse.

I can zoom fine with pressing the "Ctrl" key and scrolling, may be you should make a bug report instead of feature request.
