### ISSUE TITLE
[Bug] Copy Paste Formatting

### ISSUE THREAD

**Issue by Dansel** [JasonStein/Notepads#68]
So, this is technically speaking not a bug, but I'm going to classify it as such anyway.

When you Copy text form Notepads you grab formatting too. 

Specifically text color. 

The issue is in this case that if you use Dark Theme you'll have white text, so if you copy paste something into Word or Outlook or any other app that supports text coloring you'll get white-on-white, and that is unreadable.

You can of course change back manually, or paste without formatting, but it's an extra step.

Suggested solution would be to treat the default text color when writing in the Notepads app as black (or unformatted) for copy+paste purposes, and let manually set colors remain.

And possibly add a setting for different copy+paste settings in the app.

**Comment by JasonStein** [comment]
Well, glad you address it. It is actually not intended and I should fix it. It should always be black without formatting.

**Comment by JasonStein** [comment]
Btw, in case you don’t know, you can use Ctrl+Alt+V to paste text into Word and it will give you options to keep formatting or not.

**Comment by JasonStein** [comment]
Fixed here: https://github.com/JasonStein/Notepads/commit/be8b1a25d55fe3d0b8b8f978344538b80a520158
It will be available in v0.9.6.0

**Comment by JasonStein** [comment]
Close this issue since v0.9.6.0 is alive.

**Comment by InvisibleElvis** [comment]
Hi Jason,
I'm still experiencing this issue on 1.0.0.0

**Comment by JasonStein** [comment]
> Hi Jason,
> I'm still experiencing this issue on 1.0.0.0

I have not seen such issue happening again, can you do a repro and paste a screenshot here?

**Comment by InvisibleElvis** [comment]
https://youtu.be/nhXDip07Wc0

Hope this helps. I really love Notepads, the stay on top mode is fantastic.
