### ISSUE TITLE
regex replace ^$ pattern not searching around

### ISSUE THREAD

**Issue by basaran** [JasonStein/Notepads#680]
**Describe the bug**
When doing a regex replace, the line beginnings and line endings are not replaced as multiline and global. Please see the capture.

**To Reproduce**
Please see capture

![regex_replace](https://user-images.githubusercontent.com/30809170/92753348-cb7ea380-f357-11ea-987c-cfd9725082a4.gif)

**Expected behavior**
It should replace all line endings and beginnings.

**Desktop (please complete the following information):**
 - OS: Version	10.0.19041 Build 19041
 - Version 1.4.2.0

**Comment by JensMertelmeyer** [comment]
What happens if you use CRLF instead of LF?

**Comment by basaran** [comment]
same

**Comment by JasonStein** [comment]
@soumyamahunt FYI.

**Comment by soumyamahunt** [comment]
@JasonStein I think this is expected behavior the way replace is implemented. @basaran is clicking "Replace Next" and only the string or regex that occurs next to the cursor is replaced. Currently "Replace Next" doesn't search from the beginning if the specified input doesn't occur after the cursor while "Find Next" does. Do you want me to implement the same behavior of searching of "Find Next"??

**Comment by basaran** [comment]
Hello, I'm not clicking find-next, I'm clicking replace-all. And during the regex search/replace, replace-all is always replacing the last line for $. The situation is more awkward with ^. It won't replace anything unless the cursor is at top ^.

![regex_replace](https://user-images.githubusercontent.com/30809170/93139301-7a034b00-f6ae-11ea-8515-3d8abb211c7f.gif)

**Comment by soumyamahunt** [comment]
> Hello, I'm not clicking find-next, I'm clicking replace-all. And during the regex search/replace, replace-all is always replacing the last line for $. The situation is more awkward with ^. It won't replace anything unless the cursor is at top ^.
> 
> ![regex_replace](https://user-images.githubusercontent.com/30809170/93139301-7a034b00-f6ae-11ea-8515-3d8abb211c7f.gif)
> 

In the gif you attached you seem to be clicking on the left button in the replace bar part which is Replace/Replace Next, the button next to it is Replace All.

![ApplicationFrameHost_mDtS3fxbpD](https://user-images.githubusercontent.com/51203900/93156518-eec59c00-f725-11ea-96ac-92acb07eb513.png)
![ApplicationFrameHost_OdAxDTi7i0](https://user-images.githubusercontent.com/51203900/93156533-f127f600-f725-11ea-88d1-0ff6fde7f73e.png)

Also, I can only produce the issue you showed only when clicking on "Replace", while "Replace All" always works.

![A6LL0NZKGi](https://user-images.githubusercontent.com/51203900/93156718-5380f680-f726-11ea-8f43-dbdbb27055ef.gif)

> This is the expected behavior:
> 
> ![regex_replace](https://user-images.githubusercontent.com/30809170/93155717-b47fde80-f6d4-11ea-93c7-88f27aac6bb7.gif)

The current implementation of regex in Notepads treats the whole document as a string input while Notepad++ matched against the whole line. However, the current implementation can be changed to match with Notepad++.

**Comment by basaran** [comment]
Right, I was apparently clicking the replace button : )

None the less, I think the multiline behavior should be similar to other editors, when using a regex, that's usually the case, to prepend/append something to each line. I would send a pull request but I don't have a cs environment. Thank you for getting back by the way.

**Comment by soumyamahunt** [comment]
> It probably just needs the multiline option:
> 
> ```
> 321         private static bool TryFindAndReplaceAllUsingRegex(string content, SearchContext searchContext, string replaceText, out bool regexError, out string output)
> 322         {
> 323             regexError = false;
> 324             output = string.Empty;
> 325
> 326             try
> 327             {
> 328                 Regex regex = new Regex(searchContext.SearchText, RegexOptions.Compiled | (searchContext.MatchCase ? RegexOptions.None : RegexOptions.IgnoreCase));
> 329
> 330                 if (regex.IsMatch(content))
> 331                 {
> 332                     if (searchContext.UseRegex)
> 333                     {
> 334                         replaceText = ApplyTabAndLineEndingFix(replaceText);
> 335                     }
> 336
> 337                     output = regex.Replace(content, replaceText);
> 338                     return true;
> 339                 }
> 340             }
> 341             catch (Exception)
> 342             {
> 343                 regexError = true;
> 344                 return false;
> 345             }
> 346
> 347             return false;
> 348         }
> ```
> 
> line 328:
> 
> ```
> Regex regex = new Regex(searchContext.SearchText, RegexOptions.Compiled | (searchContext.MatchCase ? RegexOptions.None : RegexOptions.IgnoreCase));
> ```
> 
> https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regexoptions?view=netcore-3.1

Yeah, that should do it, do you want to submit a PR on this??

**Comment by basaran** [comment]
I wanted to and I tried to compile it on my machine but for some reason, I'm getting this:

```
Notepads.Controls\Helpers\ThemeListener.cs(79,35,79,57): error CS0121:  The call is ambiguous.
```

between these two overloads:

```
'DispatcherQueueHelper.ExecuteOnUIThreadAsync(DispatcherQueue, Action, DispatcherQueuePriority)' 
'DispatcherQueueHelper.ExecuteOnUIThreadAsync(DispatcherQueue, Func<Task>, DispatcherQueuePriority)'
```

the call currently in use seems to be:

```
ExecuteOnUIThreadAsync(Action, CoreDispatcherPriority)
```

```
79: await DispatcherQueue.ExecuteOnUIThreadAsync(UpdateProperties, DispatcherQueuePriority.Normal);
```

In short, I didn't want to send a PR without being able to test it myself. This is probably something wrong with my setup as it is my first attempt with VS and C#.

**Comment by soumyamahunt** [comment]
> In short, I didn't want to send a PR without being able to test it myself. This is probably something wrong with my setup as it is my first attempt with VS and C#.

Thanks for trying, I would submit a PR myself.

**Comment by soumyamahunt** [comment]
@basaran does the behavior in #689 is what you want??

**Comment by basaran** [comment]
Yes indeed, thank you very much for your time.
