### ISSUE TITLE
[Feature request] Allow changing multiple settings at once.

### ISSUE THREAD

**Issue by vishnureddys** [JasonStein/Notepads#682]
**Is your feature request related to a problem? Please describe.**
Suppose we have to change multiple settings, and we open setting, we are not able to do so. After changing one of the options, the settings bar disappears. I have to go to options, then choose settings again and then change anything else that I want to change.

**Describe the solution you'd like**
It would be great if we are allowed to change multiple settings like how other text editors have. What I mean by this is that other text editors have a settings place, where we can change multiple setting at the same time, like the theme, colour scheme, font and so on.

**Describe alternatives you've considered**
Another feature would be to have a popup settings bar, this way we could try out whatever we changed and then check if we like the new changes done or we could revert back easily. But the current mode is not very easy to use.

**Comment by XamDR** [comment]
What you describe is not totally accurate. You can change different settings at once, except by the visibility of the status bar. This is because, when you hide or show it, the settings pane changes its size and it closes automatically. Only for that setting happens the behavior described before.

**Comment by vishnureddys** [comment]
Not really. I'll send a video to explain in more detail what I mean.

**Comment by XamDR** [comment]
That would be great because I think I've misunderstood what you mean.

**Comment by vishnureddys** [comment]
I'm so sorry. Turns out that was the only thing I had an issue with. **I was actually changing the visibility of the status bar**. I'm really sorry for wasting your time. Won't happen again.
