### ISSUE TITLE
[Feature request] Make the Exit dialog more consistent with Notepad's.

### ISSUE THREAD

**Issue by flansquatch** [JasonStein/Notepads#69]
![image](https://user-images.githubusercontent.com/43116334/61217834-f7b47b00-a6e6-11e9-8544-8608767bcd9f.png)

I find it weird that the negative option (right one) causes Notepads to cancel the exit request while in Windows' Notepad it's the one you choose to exit and discard. 

I don't know if this was intentional or not, I've just been using this app for a week or so, but I find it mechanically awkward (luckily enough, it hasn't resulted in any data loss in either app, yet).

**Comment by AmionSky** [comment]
Changes that fix this are already in v0.9.5.0

**Comment by JasonStein** [comment]
and v0.9.5.0 is out yesterday on Microsoft Store, please update your app :)

**Comment by Holly-Chan** [comment]
Sorry to hijack your thread OP, but can I suggest @JasonStein to do something about the color change of the buttons?
I don't mind the text change but that strong red and blue seems..off to me, I know this is subjective so may I suggest an option to allow us to choose the color, or at least color the border of  the button like the original Notepad instead of coloring the whole thing.

**Comment by JasonStein** [comment]
@Holly-Chan You are not alone here, I do not like my color approach as well. How about a vote here?

**Comment by JasonStein** [comment]
Option 1:
![Annotation 2019-07-15 191123](https://user-images.githubusercontent.com/1166162/61261018-3709b880-a735-11e9-8584-324c378c44e0.jpg)

**Comment by JasonStein** [comment]
Option 2:
![Annotation 2019-07-15 191251](https://user-images.githubusercontent.com/1166162/61261027-3ec95d00-a735-11e9-8e9f-11b386ba8eb2.jpg)

**Comment by JasonStein** [comment]
Option 3:
![Annotation 2019-07-15 191407](https://user-images.githubusercontent.com/1166162/61261033-4426a780-a735-11e9-9885-ae7f17cad5f3.jpg)

**Comment by JasonStein** [comment]
Option 4:
![Annotation 2019-07-15 191450](https://user-images.githubusercontent.com/1166162/61261038-48eb5b80-a735-11e9-86fa-fb5fe3fa88a8.jpg)

**Comment by Holly-Chan** [comment]
@JasonStein I personally prefer option 4 so I vote for that, but if for some reason you have put color in it I think option 2 is the best of the colored ones. Thanks for your consideration!

**Comment by AmionSky** [comment]
I think the red should be removed but the blue (or accent color?) on the save should stay to bring out more the default button.
![image](https://user-images.githubusercontent.com/13593262/61280280-e1c2bb00-a7b7-11e9-8738-927ad389ddb0.png)
![image](https://user-images.githubusercontent.com/13593262/61280305-edae7d00-a7b7-11e9-92de-f324a09eaa47.png)
But then there is the calendar app
![image](https://user-images.githubusercontent.com/13593262/61280516-4c73f680-a7b8-11e9-9bb4-a0f9a06cebaa.png)

**Comment by entdark** [comment]
Accent colour should be on a positive button "Save All & Exit" background. The rest should stay default themed.
So Option 4 + @AmionSky's 2nd picture.

**Comment by JasonStein** [comment]
I am going with @AmionSky's approach for now:

![image](https://user-images.githubusercontent.com/1166162/61736981-23b1ab00-ad3c-11e9-96d1-6f4fa3ac88d6.png)

**Comment by JasonStein** [comment]
Close this issue since v0.9.6.0 is alive.
