### ISSUE TITLE
bottom Scrollbar is overlapping on last line 

### ISSUE THREAD

**Issue by kamilmirza** [JasonStein/Notepads#7]
as the title 
only when Word Wrap is OFF, with files exceeding 150 columns
here's the preview:

![2019-07-03_19-07-27](https://user-images.githubusercontent.com/6561475/60598345-fa999c80-9dc5-11e9-943c-6c8fdcd85677.png)

**Comment by JasonStein** [comment]
It is intended since it will go away if you move your mouse pointer away from the scrollbar.

**Comment by kamilmirza** [comment]
moving away from the scrollbar does NOT fix this

**Comment by JasonStein** [comment]
I just tried and it works. I tested it with 1500 columns and 5000 lines:

Scroll to the bottom, did some scrolling on bottom scrollwer and move mouse cursor away. It collapse in 2-3 seconds.

**Comment by kamilmirza** [comment]
![2019-07-05_02-08-39](https://user-images.githubusercontent.com/6561475/60687786-3027ae00-9eca-11e9-949a-82bc9be3b101.gif)

not happening here

**Comment by JasonStein** [comment]
OK, I think it has something to do with this: https://www.windowscentral.com/how-keep-scrollbars-always-visible-windows-10-april-2018-update

**Comment by kamilmirza** [comment]
hmm that must be the reason because I have set scrollbar to not hide

**Comment by JasonStein** [comment]
Glad you find the reason, I think I will leave this behaviour for now.
