### ISSUE TITLE
[Bug] Words gets deleted when typing instead of getting pushed

### ISSUE THREAD

**Issue by TsunaXZ** [JasonStein/Notepads#703]
Here's the sample video: https://youtu.be/Vif6sD3mHKw

**Comment by soumyamahunt** [comment]
Can you provide the file you are modifying??

**Comment by TsunaXZ** [comment]
> Can you provide the file you are modifying??

Uh it happens on anything that I write both new and existing .txt file.

**Comment by soumyamahunt** [comment]
> Uh it happens on anything that I write both new and existing .txt file.

I can't seem to reproduce your issue, can you state your windows build version also the version of the app you are using right now??

**Comment by TsunaXZ** [comment]
> > Uh it happens on anything that I write both new and existing .txt file.
> 
> I can't seem to reproduce your issue, can you state your windows build version also the version of the app you are using right now??

It's random so I don't know why it happens as well, sorry.

This is my windows version: 10.0.19041 Build 19041
Notepads version: 1.4.2.0

**Comment by pyed** [comment]
You probably have 'Insert' enabled, find a key on your keyboard with the word 'Insert' click it once and try again.

**Comment by TsunaXZ** [comment]
Ok so, I've found out that this was an issue on Windows 10 not the app itself so I the app is perfectly fine.  Thanks.
