### ISSUE TITLE
控件希望可以添加圆角设计和默认搜索引擎希望添加一个百度选项

### ISSUE THREAD

**Issue by Gaoyifei1011** [JasonStein/Notepads#706]
控件希望可以添加圆角设计和默认搜索引擎希望添加一个百度选项
We hope that the fluent UI could add the rounded design and the default search could add a baidu search

**Comment by JasonStein** [comment]
圆角设计等Windows其他应用做到了，我就会跟进。百度的话就算了，个人不喜欢所以不会加入。
