### ISSUE TITLE
[Feature request] Better experience for multi files by splitting editor or tearable tags

### ISSUE THREAD

**Issue by FlyinCow** [JasonStein/Notepads#708]
**Is your feature request related to a problem? Please describe.**
When you open multi files and try to compare them, it seems I must open two windows. That is inconvenient for an editor with support of tags.
多文件只能打开多个窗口去并列比较，略麻烦，多标签页等于说只能一次看一个标签

**Describe the solution you'd like**
It will be better if I can drag down a tag to start a new window just like Edge, or I can split the editor (horizontally or vertically) like VSCode. It will be even better to support diff, but this may be conflict with your purpose to make this editor simple.
要么可以跟浏览器一样拆一个tab下来变成新窗口，这样就可以直接并列两个窗口
要么就跟VSCode一样支持拆分，就跟写markdown的时候preview一样布局
要是能支持VSCode那种diff也好，但是可能就没那么简洁了，权当建议

**Additional context**
![image](https://user-images.githubusercontent.com/23637371/96707813-f0d8e580-13ca-11eb-8ccc-d451475ce017.png)

**Comment by JasonStein** [comment]
你新建一个空的标签，然后拖动这个空的标签出去可以直接打开一个新的notepads 窗口，然后你可以把第一个窗口里面的任何文件直接拖动过去
