### ISSUE TITLE
关于更完美的建议

### ISSUE THREAD

**Issue by GithubABCDEFG** [JasonStein/Notepads#709]
非常感谢作者的工作，不得不说是个很好看的软件，提出几个小建议：
1. 建议按住Shift或Alt后用滚轮可以调透明度。
2. 快捷键激活到前台。
3. 可以设定新建文件的默认编码。

**Comment by JasonStein** [comment]
1. 透明度设置已经可以改了，快捷键的话不是特别必须而且大部分用户用不上所以暂时不会考虑。
2. UWP app应该是没有全局键盘监听能力的所以做不了。
3. 
![image](https://user-images.githubusercontent.com/1166162/103504852-7afeea80-4e0d-11eb-9e6f-58ba027ed158.png)
