### ISSUE TITLE
[Feature request] Add following by link inside markdown preview to other markdown files

### ISSUE THREAD

**Issue by tochanenko** [JasonStein/Notepads#710]
**Is my feature request related to a problem?**
It's not related to any problem. This feature might make it easier to manage markdown files.

**The solution I'd like**
Markdown preview is opened. Whenever user clicks on link that links to other markdown file on the local machine, the app opens file at the same window or in the current tab with markdown preview opened by default. The current tab option is preferable.

**Alternatives I've considered**
I don't see any alternatives here.

**Additional context**
Currently there is no functionality while clicking on link that links to other markdown file. Links to websites are working correctly.

**Comment by JasonStein** [comment]
Based on the limitation UWP apps have, it can only access the files which user opened. So this is not quite doable in the current state.
