### ISSUE TITLE
[Bug] Icons not showing

### ISSUE THREAD

**Issue by sheeepdev** [JasonStein/Notepads#711]
**Describe the bug**
When I open any type of file, is it a .md or .txt or any file it does not show any icon

**To Reproduce**
Open the app (or open/create) a file in the app.

**Expected behavior**
It should've shown the icons rather than not.

**Screenshots**
If applicable, add screenshots to help explain your problem
![ApplicationFrameHost_fb69zgrWY3](https://user-images.githubusercontent.com/68562536/97309878-dedfc280-1862-11eb-8285-7ac5639fbab3.png)
_(sorry for my handwriting thing)_

**OS Info:**
 - OS: Windows 10 20H2 (19042.608)
 - Notepads Version 1.4.2.0

**Comment by soumyamahunt** [comment]
That is expected behavior, Notepads doesn't show any icon there until you have modified file.

**Comment by sheeepdev** [comment]
#765
