### ISSUE TITLE
[Bug] Resizing compact overlay too much causes note area to stop resizing

### ISSUE THREAD

**Issue by BrandonXLF** [JasonStein/Notepads#719]
**Describe the bug**
When you resize the compact overlay to the point where the tab starts to shrink, the note area doesn't decrease in width anymore.

**To Reproduce**
1. Open Notepads
1. Write a long string
1. Press "Compact Overlay" in the menu (or F12)
1. Resize the overlay to as small as it gets
1. You are not able to view the right side of the note area

Note: If you disable word wrap, the scrollbar will be cut off as well

**Expected behavior**
A) The note area should shrink to the width of the window
B) The overlay should become extra compact and the tab should disappear

**Screenshots**
Compact overlay before the tab starts resizing:
![image](https://user-images.githubusercontent.com/42590338/99140024-fca37a80-260b-11eb-96a1-f808fc2cd1e5.png)

Compact overlay after the tab starts resizing:
![image](https://user-images.githubusercontent.com/42590338/99140096-720f4b00-260c-11eb-9f9a-a994813da67e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 19041.610
 - Version v1.4.2.0

**Additional context**
None.

**Comment by JasonStein** [comment]
There is a min-max width and height set by the system. The compact-overlay is a feature controlled by Windows 10 and it has certain limitation.
