### ISSUE TITLE
[Bug] Copying text from dark mode to clipboard marks the font color as white

### ISSUE THREAD

**Issue by leonardhsin** [JasonStein/Notepads#72]
**Describe the bug**
Tried to Ctrl + C copy some text from Notepads in dark mode and Ctrl + V pasted to Outlook email editor and the text ended up in white color.

**To Reproduce**
See above description.

**Expected behavior**
The text color was expected to be the default color (e.g. black) in the target editor.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 1903
 - Version v0.9.5.0

**Additional context**

**Comment by yaichenbaum** [comment]
Is this the same issue as #68?

**Comment by JasonStein** [comment]
This is the same issue reported in #68 and it has been fixed. It will be available in v0.9.6.0.

**Comment by JasonStein** [comment]
Close this issue since v0.9.6.0 is alive.
