### ISSUE TITLE
[Feature request] Word wrapping keyboard shortcut

### ISSUE THREAD

**Issue by CoreyVidal** [JasonStein/Notepads#720]
**Describe the solution you'd like**
A keyboard shortcut to toggle Text Wrapping

**Additional context**
I bounce back and forth between Visual Studio Code and Notepads all day. I would like a keyboard shortcut to toggle word wrapping. I propose `Alt` + `Z` which is the same shortcut used by default in Visual Studio Code.

**Comment by soumyamahunt** [comment]
> I propose `Alt` + `Z` which is the same shortcut used by default in Visual Studio Code.

It is already available with the same keyboard shortcut.
