### ISSUE TITLE
windows商店和安装包都无法安装，报错如下

### ISSUE THREAD

**Issue by Fengjing95** [JasonStein/Notepads#721]
应用安装失败，错误消息: AppxManifest.xml(164,10): 错误 0x80070005: 无法注册 19282JackieLiu.Notepads-Beta_1.4.2.0_x64__echhpq9pdbte8 程序包，因为在注册 windows.fileTypeAssociation 扩展时遇到以下错误: 拒绝访问。
。请重试，如果问题仍然存在，请联系程序包发布者。 (0x80070005)

**Comment by lxxx59** [comment]
一样的问题，不知道怎么解决。。

**Comment by JasonStein** [comment]
Windows 10版本是多少？商店装其他应用有同样问题吗？

**Comment by Fengjing95** [comment]
> 视窗 10？

win 10 1909; 应用商店安装其他应用没有问题

**Comment by JasonStein** [comment]
你可以尝试把报错信息发给微软客服让他们看一下，这个是属于应用商店的问题。

**Comment by Fengjing95** [comment]
> 你可以尝试把报错信息发给微软客服让他们看一下，这个是属于应用商店的问题。

好的

**Comment by Manukineko** [comment]
I got the same issue ...
Either from the Windows Store or from the Github release .mixbundle package.
It throw an error at 84% of installation with 0x80070005.

**Comment by JasonStein** [comment]
> I got the same issue ...
> Either from the Windows Store or from the Github release .mixbundle package.
> It throw an error at 84% of installation with 0x80070005.

Highly likely a store issue or your MSFT store is having an issue.

**Comment by z1298808165** [comment]
1.以管理员身份运行 PowerShell。
2.在 PowerShell 中输入以下命令并按 Enter 键：Get-AppXPackage -AllUsers | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}。
3.等待命令执行完毕，然后重启计算机。

**Comment by 481652** [comment]
我在安装Windows Media Player时遇到了一样的问题，根据报错信息“在注册 windows.fileTypeAssociation 扩展时遇到以下错误: 拒绝访问”应该是没法注册文件扩展关联，不知道是遇到了权限问题还是什么
