### ISSUE TITLE
[Feature request]Could you add support for offline installation? 可以提供离线安装包/离线安装支持吗？

### ISSUE THREAD

**Issue by wanderseeme** [JasonStein/Notepads#734]
**Is your feature request related to a problem? Please describe.**

我想在内网办公电脑里安装Notepads，在网上找了一些方法：
https://blog.csdn.net/weixin_43839895/article/details/103448841
https://blog.csdn.net/lpwmm/article/details/106117056

通过访问这个网站：
https://store.rg-adguard.net/

网站里搜索这个链接：
https://www.microsoft.com/en-us/p/notepads-app/9nhl4nsc67wm

网站搜索结果里下载以下文件：
19282JackieLiu.Notepads-Beta_1.4.2.0_neutral_~_echhpq9pdbte8.msixbundle
Microsoft.NET.Native.Framework.2.2_2.2.29512.0_x64__8wekyb3d8bbwe.appx
Microsoft.NET.Native.Framework.2.2_2.2.29512.0_x86__8wekyb3d8bbwe.appx
Microsoft.NET.Native.Runtime.2.2_2.2.28604.0_x64__8wekyb3d8bbwe.appx
Microsoft.NET.Native.Runtime.2.2_2.2.28604.0_x86__8wekyb3d8bbwe.appx
Microsoft.VCLibs.140.00_14.0.29231.0_x64__8wekyb3d8bbwe.appx
Microsoft.VCLibs.140.00_14.0.29231.0_x86__8wekyb3d8bbwe.appx

我已经成功安装了！但是打开的时候只显示了Notepads的带Logo加载页面（并没能进入编辑框），并在一段时间后崩溃退出……

**Describe the solution you'd like**

如上描述直接离线安装的.msixbundle好像会崩溃，可以直接在Releases里添加一个.msi或者.exe的离线安装版本吗？

**Describe alternatives you've considered**

或者其实是不是我安装操作有问题导致崩溃？在启动时提供一个报错信息？

**Additional context**

感谢持续开发如此优秀的软件！

**Comment by JasonStein** [comment]
你办公电脑的微软商店是被禁用了吗 还是?

**Comment by SuTanTank** [comment]
相同的问题，我电脑的win10商店安装不了app（同网络下其他电脑可以）。所以就打算安装非商店版本，但是直接从release下载的安装包打开几秒就崩溃了。

**Comment by wanderseeme** [comment]
> 你办公电脑的微软商店是被禁用了吗 还是?

办公电脑是内网，与互联网是隔离的，所以微软商店也无法访问了，所有软件都只能用离线安装包的方式。

**Comment by JasonStein** [comment]
因为Windows 10的UWP应用，有一部分组件，比如日志功能，是需要商店的支持的。如果商店在你电脑上被彻底禁用了的话，我猜测有一部分必要组件也会禁用。所以会导致notepads打开不了。
