### ISSUE TITLE
[Feature request] Language

### ISSUE THREAD

**Issue by xmha97** [JasonStein/Notepads#735]
How I can create a language for the Notepads app?
![Notepads](https://user-images.githubusercontent.com/23485114/102291623-c33a9380-3f58-11eb-9067-72c66f8b61f6.png)

**Comment by KristofKekesi** [comment]
You can contribute to it on GitHub.
You can generate the required files if you know how to use multilingual or make an issue (include your target language) and ask the devs to make it for you.

After the files are generated you can replace the english strings to your language.

**Comment by JasonStein** [comment]
https://github.com/JasonStein/Notepads/blob/master/CONTRIBUTING.md
