### ISSUE TITLE
[Bug] "Save As" action hotkey

### ISSUE THREAD

**Issue by Tarik02** [JasonStein/Notepads#75]
**Describe the bug**
Windows notepad uses `Ctrl+Shift+S` for "Save As" action. While Notepads uses `Ctrl+Alt+S`. This is strange for me.

**To Reproduce**
Open an editor and check main menu.

**Expected behavior**
Click `Ctrl+Shift+S` to open "Save As" dialog.

**Screenshots**
Default Windows notepad:
![image](https://user-images.githubusercontent.com/12175048/61660310-3f806700-acd2-11e9-9651-a6afc122b347.png)

VS Code:
![image](https://user-images.githubusercontent.com/12175048/61660421-73f42300-acd2-11e9-9513-c29ad455a08f.png)

Notepads:
![image](https://user-images.githubusercontent.com/12175048/61660350-5030dd00-acd2-11e9-825e-11344ab72c4f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1903 18362.116
 - Version: [d160ad](https://github.com/JasonStein/Notepads/commit/d160ade2783c997d0c28ca9729636f11ae5a2474)

**Additional context**
Also, other editors (including vscode, jetbrains IDEs) also use `Ctrl+Shift+S` for "Save As" action.

**Comment by JasonStein** [comment]
Notepad++ uses Alt, I changed it from shift to alt because I think it is more likely to randomly hit ctrl+shift at same time comparing to ctrl+alt. But I agree with you. I will change it back in the next release.

**Comment by Tarik02** [comment]
Personally I already clicked ctrl+shift+s expecting to Save As, but nothing happened... maybe this should be an option in settings.

**Comment by JasonStein** [comment]
I changed it back to Ctrl+Shift+S: https://github.com/JasonStein/Notepads/commit/ccc04262432091702ec6bf69711834a6b988632b

It will be available in v0.9.6.0

**Comment by Tarik02** [comment]
Okay, thank you
