### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by robertlee2014** [JasonStein/Notepads#754]
建议添加自动保存功能，现在找了找设置没有找到自动保存的设置。期待作者的回复。
Suggest add the auto-save function. And for now I didn't find the option of auto-save in the setting menu. Wait for your response.

**Comment by XamDR** [comment]
While it's true that there is not an auto-save functionality, you can try the option "Enable session snapshot" in the Advanced option on the settings menu.

**Comment by robertlee2014** [comment]
Thank you
