### ISSUE TITLE
[Bug]这是NotePads的一个影子窗口，快照备份功能和设置已被禁用

### ISSUE THREAD

**Issue by sifenglib** [JasonStein/Notepads#757]
启动NotePads的时候都会提示这个问题：这是NotePads的一个影子窗口，快照备份功能和设置已被禁用
还想请问应该如何解决？目前很多功能都用不了

**Comment by drthrhr** [comment]
我也遇到了这个问题，不过在设置-应用和功能-Notepads-高级选项中重置了应用数据，再打开Notepads就恢复正常了

**Comment by sifenglib** [comment]
确实可以了，感谢分享
