### ISSUE TITLE
[Feature request]Vim Mode

### ISSUE THREAD

**Issue by S-Spektrum-M** [JasonStein/Notepads#759]
**Is your feature request related to a problem? Please describe.**
A problem I have been having is a lack of a vim mode.

**Describe the solution you'd like**
While notepads is excellent and the tab features is simply amazing I still find the omission of vim commands and modes a big drawback.

**Describe alternatives you've considered**

**Comment by JasonStein** [comment]
I don't have a plan to add Vim mode to Notepads. Sorry.

**Comment by S-Spektrum-M** [comment]
Alright then thanks for making an AMAZING editor.
