### ISSUE TITLE
[Bug] It freezes somtimes

### ISSUE THREAD

**Issue by yoshiotobe** [JasonStein/Notepads#762]
**Describe the bug**

It freezes suddenly somtimes and I can't do anything when that happens. If I save the file that I'm editing or click other application such as VSCode or word, it becomes normal again. 

**To Reproduce**

I can't tell exactly when that happens. However, it seems to happen when I edit sentense quickly or multiple lines with multiple tabs.

**Expected behavior**

Not to freeze

**Desktop (please complete the following information):**
 - OS: Windows 10 pro 1909 18363.1316
 - Version v1.4.2.0

**Additional context**

I might be using it too quickly and it burdens Notepads? I think my PC with RAM (16GB) and CPU (Intel i5 3.20GHz) is fast enough though. 

Is there any ways to avoid freezing? I hope Notepads does not freeze and works fine anytime.

**Comment by XamDR** [comment]
Is there any screenshots about the freezing problem that you describe? It's the first time I heard of such issue.

**Comment by yoshiotobe** [comment]
Thank you for your reply. Sorry, I missed to take a screenshot. 
When the problem happens, the display looks like normal with no error messages. I realized that I just can't move a cursol. If I move a mouse, I can select other lines from where the cursol is but I can't move the cursol from where it is. If I click on something like a browser, then it becomes normal again.
I have no clue but have been using a setting of "Highlight current line". So, I disable that function and see what happens...
The problem happens only a few times a day, but it happens pretty much everday.

**Comment by yoshiotobe** [comment]
I tried the function of "Highlight current line" off, but it still freezes.

![notepads](https://user-images.githubusercontent.com/38850403/105939575-d6369c80-609c-11eb-9111-73606cc5dd20.jpg)

As you can see, I can select multiple lines but I can't move the cursor from a current position when it freezes. No error message is displayed. It does not happen when using windows default memo app.

**Comment by XamDR** [comment]
I'm sorry for the crashes, but I have no idea about what could be causing the crash. I'll try to reproduce the bug.

**Comment by yoshiotobe** [comment]
Thank you for your reply. 
It is hard to reproduce the problem because I don't know how and when that happens. Although, it seems to happen when I add a lot of modifications to a file while not saving the file for a while and type them quickly.
Well, it is not a critical bug because it becomes normal again after saving or clicking other app. However, it would be nice if it will be fixed bacause I'm a heavy user. 
This Notepads app helps me a lot. Thank you for developing!
