### ISSUE TITLE
[Feature request]没有办法把文件拖到快捷方式打开(There is no way to drag the file to the shortcut to open)

### ISSUE THREAD

**Issue by bitbangonline** [JasonStein/Notepads#764]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bitbangonline** [comment]
能不能做一个桌面版本(Could you make a desktop version)?

**Comment by JasonStein** [comment]
> 能不能做一个桌面版本(Could you make a desktop version)?

不能，我懒，不过等以后WinUI强大稳点了后，会考虑。

**Comment by bitbangonline** [comment]
谢谢大佬
