### ISSUE TITLE
[Bug] icons not showing

### ISSUE THREAD

**Issue by sheeepdev** [JasonStein/Notepads#765]
**Describe the bug**
When I open any type of file, is it a .md or .txt or any file it does not show any icon

**To Reproduce**
Open the app (or open/create) a file in the app.

**Expected behavior**
It should've shown the icons rather than not.

**Screenshots**
If applicable, add screenshots to help explain your problem
![ApplicationFrameHost_fb69zgrWY3](https://user-images.githubusercontent.com/68562536/97309878-dedfc280-1862-11eb-8285-7ac5639fbab3.png)
_(sorry for my handwriting thing)_

**OS Info:**
 - OS: Windows 10 20H2 (19042.608)
 - Notepads Version 1.4.2.0

also I know this is a duplicate but my last issue didn't get noticed and been got closed by a bot

**Comment by soumyamahunt** [comment]
Why do you think this is a bug? Notepads doesn't show file icons in the location you have shown in the screenshot(the behaviour you described is intended), why do you want to show the icon in the screenshot anyway??

**Comment by sheeepdev** [comment]
umm it does, in all screenshots it does,
![firefox_m5SW7mYUYF](https://user-images.githubusercontent.com/68562536/106245155-50396380-620c-11eb-9968-d1c76ccbf8b5.png)

**Comment by soumyamahunt** [comment]
> umm it does, in all screenshots it does,
> ![firefox_m5SW7mYUYF](https://user-images.githubusercontent.com/68562536/106245155-50396380-620c-11eb-9968-d1c76ccbf8b5.png)

The icon in the screenshots you described used to(now it Notepads shows a different icon) only when you modify a file in Notepads and you haven't saved your changes. Are you saying you can't see this icon if you modify a file? 
@JasonStein may be the screenshots could be updated with latest ui changes.

**Comment by sheeepdev** [comment]
i see a dot if its not saved ¯\_(ツ)_/¯ So it was changed from the file icons to a dot ?

**Comment by soumyamahunt** [comment]
> i see a dot if its not saved ¯_(ツ)_/¯ So it was changed from the file icons to a dot ?

Yes.

**Comment by sheeepdev** [comment]
oh, now i know! thank you! thought that those icons were nice and I couldn't get them but didn't know they were replaced and the screenshots need to be updated, thanks!
