### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by karimk123** [JasonStein/Notepads#766]
**Describe the bug**
The program is running when its closed

**Desktop (please complete the following information):**
 - OS: Windpws 10

I am not sure if this is a bug or if its something suspicious. I found out that Notepads was running in the background and i haven't even opened it once since i opened my laptop. ??

**Comment by soumyamahunt** [comment]
There is nothing suspicious at all. Modern apps  are managed by Windows in the sense that they are pre launched in suspended state before user launches the app, also the app is kept at suspended state even after user closes the app. You can know more [here](https://winaero.com/enable-app-execution-aliases-windows-10/#:~:text=Enable%20App%20Execution%20Aliases%20in%20Windows%2010%20Open,toggle%20switch%20next%20to%20the%20app%27s%20name%20).

**Comment by karimk123** [comment]
Ok that makes more sense thanks.
