### ISSUE TITLE
[Bug]powershell在终端打开会导致powershell卡死

### ISSUE THREAD

**Issue by HydrogenDeuterium** [JasonStein/Notepads#768]
**Describe the bug**
如题，并且软件不能正确切换到前台

**To Reproduce**
在powershell终端中输入`notepads`或`notepads [文件名]`，回车执行指令

**Expected behavior**
打开软件，软件切换到前台，终端返回并且等待下一条指令，如同在cmd中执行的情况相同

**Screenshots**
![image](https://user-images.githubusercontent.com/36532302/106548583-3bc9d380-654a-11eb-8c19-cc25a38ab60e.png)

**Desktop (please complete the following information):**
 - OS: win 10 2004 19041.746
 - Version 1.4.2.0

**Additional context**
使用cmd终端打开时，情况和预期一致，可以正常打开。

**Comment by JasonStein** [comment]
用这个试试： start-process notepads

**Comment by HydrogenDeuterium** [comment]
@JasonStein 通过`start-process notepads`调用打开软件不会导致powershell卡死。
但是软件仍然不能正确切换到前台。

**Comment by HydrogenDeuterium** [comment]
建议替代方案：在$profile 中添加function notepads{start-process notepads.exe $args}，并且设置execution policy 为bypass或者remotesigned等允许执行本地脚本的方案
