### ISSUE TITLE
[Feature request] Settings localization

### ISSUE THREAD

**Issue by Tarik02** [JasonStein/Notepads#77]
**Is your feature request related to a problem? Please describe.**
Localization in settings is missing.

**Describe the solution you'd like**
Translate settings as it is done with other parts of application.

**Additional context**
![image](https://user-images.githubusercontent.com/12175048/61661553-0695c180-acd5-11e9-89f3-3788eb82b882.png)

**Comment by JasonStein** [comment]
I will do it this week, hopefully before Wednesday.

**Comment by JasonStein** [comment]
Settings strings have been moved to Settings.resx:
https://github.com/JasonStein/Notepads/commit/115aab71a6953ae38a30c0546e4cb8a64496d604

**Comment by JasonStein** [comment]
Close this issue since it has been added.
