### ISSUE TITLE
[Bug] Tabs position in RTL locales 

### ISSUE THREAD

**Issue by HasanAlyazidi** [JasonStein/Notepads#773]
Thank you for the awesome notepad.

**Describe the bug**
Tabs are mispositioned in RTL locales 

**To Reproduce**
Change language to the newly added "العربية (اليمن) [#772] , then restart Notepads

**Expected behavior**
Close & Maximize & Minimize buttons should be appear on the left and the tabs on the right ideally

**Screenshots**
![image](https://user-images.githubusercontent.com/7901330/107109358-797b7480-6848-11eb-93a8-a893f087bf6b.png)

Tabs should be beside the Close & Maximize & Minimize box or ideally on the right.

also the controls and texts align should be RTL too
![Settings](https://user-images.githubusercontent.com/7901330/107109411-f0b10880-6848-11eb-8d47-345122778275.png)

**Desktop:**
 - OS: [e.g. Windows 10 20H2 19042.746]
 - Version [e.g. v1.4.2.0]

**Comment by JasonStein** [comment]
ACK.
