### ISSUE TITLE
[Request] Enable Discussions

### ISSUE THREAD

**Issue by aleks-ivanov** [JasonStein/Notepads#780]
I've been a fan of this app for awhile and I use it daily!

By a happy accident, I stumbled upon a [video by an almost-popular gaming streamer and YouTuber](https://youtu.be/tOZ2Ot1xLcw?t=179), in which he shouted out Notepads and I just wanted to share it with the creator and contributors :)

Since I don't think Issues is the place to do that, but Discussions is disabled, I decided to create an issue to combine both the story and a request for Discussions to be enabled, where this kind of post would be more appropriate.

**Comment by soumyamahunt** [comment]
Also some of the pinned issues aren't actually issues and should belong in discussions.

**Comment by kybo15** [comment]
How to change windows notepad to notepads?

**Comment by hello-smile6** [comment]
I agree, the project should use Discussions.

**Comment by JasonStein** [comment]
Agreed, I have enabled Discussions for Notepads repo where you can access here: https://github.com/JasonStein/Notepads/discussions
