### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by zcysxy** [JasonStein/Notepads#788]
I keep getting error installing the app through Microsoft store and Winget. And Winget returned the following info:

```txt
Install failed: AppxManifest.xml(164,10): error 0x80070005: Cannot register the 19282JackieLiu.Notepads-Beta_1.3.8.0_x64__echhpq9pdbte8 package because the following error was encountered while registering the windows.fileTypeAssociation extension: Access is denied.
.  Try again and contact the package publisher if the problem persists.
0x80070005 : Access is denied.
```

I know that it may be the problem of my OS or store. But is there a workaround or a manually installing method?

**Comment by beerisgood** [comment]
Sounds like you're using restricted Windows user Account or something is configured bad.

**Comment by zcysxy** [comment]
Probably, cause I tweaked Windows settings recently. However the problem persists when I use different administer accounts. I am so tired of fighting with Windows permissions 🤕🤕🤕

**Comment by beerisgood** [comment]
You can reset Windows then.
Anyway it's definitely not a Notepads bug.

**Comment by zcysxy** [comment]
The problem is solved
