### ISSUE TITLE
不能打开一个新的窗口，打开两个文件它们只能共用一个窗口

### ISSUE THREAD

**Issue by 15778078047** [JasonStein/Notepads#796]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1809 17763.593]
 - Version [e.g. v0.9.3.0]

**Additional context**

**Comment by JasonStein** [comment]
![image](https://user-images.githubusercontent.com/1166162/111893279-9e185e00-8a3c-11eb-86fe-6bb6ef92dedd.png)
