### ISSUE TITLE
[Feature request]能否加个“关闭最后一个标签直接退出应用”的选项？像Edge浏览器那样。

### ISSUE THREAD

**Issue by o000u** [JasonStein/Notepads#798]
如题。
我习惯于用快捷键ctrl+w关闭标签，像用Edge浏览器那样。
很多时候，当我关闭最后一个标签时，其实已经不需要再用它了，如果能在关闭最后一个标签直接退出应用，就不用在关闭所有标签后，还得再特意关闭一次应用，多一个步骤。
这样是不是会更人性化些？
个人认为Notepads算是Win10里UWP版记事本做得最舒服的了，感谢作者的卓越付出！！
希望Notepads能继续完善，做到最好，没有之一！！
再次感谢！！

**Comment by XamDR** [comment]
Hi. This feature has already been implemented, but it hasn't been merged to master yet. There is an open [pull request](https://github.com/JasonStein/Notepads/pull/601) about it.

**Comment by o000u** [comment]
> Hi. This feature has already been implemented, but it hasn't been merged to master yet. There is an open [pull request](https://github.com/JasonStein/Notepads/pull/601) about it.

WOW!So glad to hear that!! Thank you for telling this good news.
