### ISSUE TITLE
[Bug]滚动条上的光标状态仍为“工”形插入状态，能否切回正常的箭头选择状态？

### ISSUE THREAD

**Issue by o000u** [JasonStein/Notepads#799]
一般来说，如系统自带的记事本那样，光标在文字编辑区域会处于“工”形插入状态，然后光标移到滚动条上时，会变回到默认的箭头选择状态，这样算是一个常规处理。
事实上，这倒也不影响正常操作，所以严格来说这不算是bug，哈哈。
只不过，刚好这个情况就与我所用的另一个叫Panderbar（相当于Win版的Popclip）的软件有冲突，不知作者是否对Panderbar有所了解？它是一个划词工具，当你拖动鼠标选择文字后，会自动弹出包含“复制、搜索”等选项的浮窗，让你可以快速点击进行下一步操作。不管怎样，我想它的工作原理中有一项是检测鼠标的状态，当鼠标状态为“工”形时才激活，所以当我在Notepads上进行滚动条拖动操作时，由于它的光标仍为“工”形，使得Panderbar同时也被激活，最终导致Notepads无法正常实现滚动条的拖动，希望作者能在百忙中抽空看一看？
感谢作者的辛勤付出，致敬！！

**Comment by JasonStein** [comment]
Notepads用的是系统自带的RichEdit控件，就是WinRT的自带文本框，本身bug和问题就比较多，他们也一直没好好去解决，以后如果他们有精力去解决的话 可能会改善。很多问题我也有向他们反馈过。看吧。
