### ISSUE TITLE
[FEATURE REQUEST] ability to save without extension

### ISSUE THREAD

**Issue by kamilmirza** [JasonStein/Notepads#8]
as per title 
i have tried to save a file without extension but it saved with .txt extension

**Comment by JasonStein** [comment]
I will take a look to see if I can fix it.

**Comment by JasonStein** [comment]
Fixed (sort of):  https://github.com/JasonStein/Notepads/commit/c1ff62201dbccdb40ead9514d32fdf334cb2dfcc

Basically, you need to select "Unknow" first, then you can save file without extension:
![nofileextsave](https://user-images.githubusercontent.com/1166162/60704361-1df14400-9eb9-11e9-8a24-dd91e423d73a.png)

**Comment by JasonStein** [comment]
Close this one since it has been fixed in v0.9.3.0 and it is available in Microsoft Store as well.
