### ISSUE TITLE
[Bug]第8456行开始的内容都不显示

### ISSUE THREAD

**Issue by QuantumNingen** [JasonStein/Notepads#803]
如题，这里以异星工厂的配置文件为例，文件455kb并没有超过1mb，搜索某些8456行之后的关键词也可以搜到，但只看见高亮，看不见字。看不见的地方是可以复制出字来的，说明那里是有字的，只是看不见。
用系统记事本打开可以正常显示。

如图所示：
![360截图20210314141108209](https://user-images.githubusercontent.com/52877736/111059262-2b086800-84cf-11eb-8dfb-65b08b55d199.jpg)
记事本打开（右下角8457行）：
![360截图20210314141603502](https://user-images.githubusercontent.com/52877736/111059350-e3cea700-84cf-11eb-956a-a0f5e8c64a35.jpg)

所用文件：
[entities.zip](https://github.com/JasonStein/Notepads/files/6136175/entities.zip)

**Comment by QuantumNingen** [comment]
> 如题，这里以异星工厂的配置文件为例，文件455kb并没有超过1mb，搜索某些8456行之后的关键词也可以搜到，但只看见高亮，看不见字。看不见的地方是可以复制出字来的，说明那里是有字的，只是看不见。
> 用系统记事本打开可以正常显示。
> 
> 如图所示：
> ![360截图20210314141108209](https://user-images.githubusercontent.com/52877736/111059262-2b086800-84cf-11eb-8dfb-65b08b55d199.jpg)
> 记事本打开（右下角8457行）：
> ![360截图20210314141603502](https://user-images.githubusercontent.com/52877736/111059350-e3cea700-84cf-11eb-956a-a0f5e8c64a35.jpg)
> 
> 所用文件：
> [entities.zip](https://github.com/JasonStein/Notepads/files/6136175/entities.zip)

**Comment by JasonStein** [comment]
Notepads用的是windows 系统自带的 RichEdit 控件，本身对大文本的支持就不好，其次就是它内部实现方法里是有对文字渲染画板的尺寸限制，比如你可以试试缩放当前文字，把文字变小一点，就能看到更多行数了。当然这个问题如果Windows文本框team不去解决或者改善的话，暂时没有什么办法。

**Comment by iamqiz** [comment]
我也遇到了, 这个bug 好致命
