### ISSUE TITLE
Vim option for Notepads

### ISSUE THREAD

**Issue by karimk123** [JasonStein/Notepads#805]
It would be pretty nice to have vim support on Notepads because it would be unique and it would make a lot more developers use it for brainstorming or just writing down ideas

I would like a checkbox or something in the settings menu for Vim

It would make me and im sure a lot more people like Notepads even more and would attract more users, thanks!

**Comment by S-Spektrum-M** [comment]
Check out issue #759

**Comment by JasonStein** [comment]
Duplicate: #759
