### ISSUE TITLE
[Feature request] Multi column editing

### ISSUE THREAD

**Issue by jlnprssnr** [JasonStein/Notepads#809]
**Is your feature request related to a problem? Please describe.**
I can't select multiple lines / a whole column in the text file, like in Notepad++

**Describe the solution you'd like**
I think Notepad++ handles it well, hold alt and select multiple columns with the mouse, or shift + alt + arrow keys up/down

**Describe alternatives you've considered**
Manually editing each line, or using Notepad++ instead

**Comment by JasonStein** [comment]
Not supported by current design and implementation since it is depending on Windows 10 built-in RichEdit control which does not support such feature yet.
