### ISSUE TITLE
Fix height max size in pin mode.

### ISSUE THREAD

**Issue by korenevskiy** [JasonStein/Notepads#836]
Please disabled fix hight max size.
Please will be only resize to small window.

**Comment by JasonStein** [comment]
This is controlled by the operating system (Windows 10):
![image](https://user-images.githubusercontent.com/1166162/112773372-6cb91700-9068-11eb-9525-2a274b8aba15.png)
Ref: https://docs.microsoft.com/en-us/uwp/api/windows.ui.viewmanagement.applicationview.setpreferredminsize?view=winrt-19041#Windows_UI_ViewManagement_ApplicationView_SetPreferredMinSize_Windows_Foundation_Size_

**Comment by korenevskiy** [comment]
> This is controlled by the operating system (Windows 10):
> ![image](https://user-images.githubusercontent.com/1166162/112773372-6cb91700-9068-11eb-9525-2a274b8aba15.png)
> Ref: https://docs.microsoft.com/en-us/uwp/api/windows.ui.viewmanagement.applicationview.setpreferredminsize?view=winrt-19041#Windows_UI_ViewManagement_ApplicationView_SetPreferredMinSize_Windows_Foundation_Size_

in WPF, you can set the be on top option yourself. And also set the option select window buttons. There are no such options in UWP?

**Comment by JasonStein** [comment]
> > This is controlled by the operating system (Windows 10):
> > ![image](https://user-images.githubusercontent.com/1166162/112773372-6cb91700-9068-11eb-9525-2a274b8aba15.png)
> > Ref: [docs.microsoft.com/en-us/uwp/api/windows.ui.viewmanagement.applicationview.setpreferredminsize?view=winrt-19041#Windows_UI_ViewManagement_ApplicationView_SetPreferredMinSize_Windows_Foundation_Size](https://docs.microsoft.com/en-us/uwp/api/windows.ui.viewmanagement.applicationview.setpreferredminsize?view=winrt-19041#Windows_UI_ViewManagement_ApplicationView_SetPreferredMinSize_Windows_Foundation_Size)_
> 
> in WPF, you can set the be on top option yourself. And also set the option select window buttons. There are no such options in UWP?

No.
