### ISSUE TITLE
[功能请求]

### ISSUE THREAD

**Issue by kochamcie65535** [JasonStein/Notepads#875]
自动换行的问题，
![image](https://user-images.githubusercontent.com/75479847/116023804-7f326a80-a67f-11eb-8fe2-b43ff9d4c62b.png)
打开自动换行的时候能不能把换行的内容缩进和开头的缩进一样的，这样开起来比较直观；

**Comment by kasusa** [comment]
`+1 `
是看起来很怪。
但是因为你的（2）的内容实际上没有换行，是因为超出宽度被强制折行了。
我想了想感觉如果要像word一样自动缩进，应该是实现起来蛮难的。
