### ISSUE TITLE
[Bug] Ctrl+N and Ctrl+T Perform Same Action

### ISSUE THREAD

**Issue by robmonte** [JasonStein/Notepads#882]
**Describe the bug**
The two keyboard shortcuts Ctrl+T and Ctrl+N perform the same action, which is to open a new editor tab. Typically Ctrl+N would open a new window instance instead.

**To Reproduce**
1. Open Notepads
2. Press Ctrl+N

**Expected behavior**
Ctrl+N should open a new application window instead of a new tab.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
This could also be toggle (or customizable) as some people maybe are already used to this shortcut or might be adjusted to programs that use Shift+Ctrl+N for new windows instead.

**Comment by soumyamahunt** [comment]
@robmonte Notepads mentions in its main flyout that `Ctrl`+`Shift`+`N` is used for new window. How is this bug?? Did you want to make a feature request instead??

**Comment by robmonte** [comment]
I considered duplicated keybinds a bug under the idea that it might have been a mistake. I didn't expect both to be set on purpose.

**Comment by soumyamahunt** [comment]
> I considered duplicated keybinds a bug under the idea that it might have been a mistake. I didn't expect both to be set on purpose.

It is on purpose, some editor use `Ctrl`+`T` for new tab and some use `Ctrl`+`N`, the idea was to keep Notepads familiar with users coming from either background.
