### ISSUE TITLE
[Bug] Two different Notepads versions in winget: Which is genuine, not bug really

### ISSUE THREAD

**Issue by yaamas** [JasonStein/Notepads#897]
**Describe the bug**
Two different Notepads in winget when I run `winget install notepads`.

**To Reproduce**
```powershell
PS C:\test-y> winget install notepads

Multiple packages found matching input criteria. Please refine the input.
Name         Id                    Source
-----------------------------------------
Notepads     Notepads.Notepads     winget
Notepads App JackieLiu.NotepadsApp winget

PS C:\test-y>
```

**Expected behavior**
Just one notepads.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10 Pro 20H2 Build 19042.985
 - Version: 1.4.5.0

**Additional context**

**Comment by yaamas** [comment]
I tried to install both. `Notepads.Notepads` installs from github while `JackieLiu.NotepadsApp` installs from a binary hosted on winget storage or something (idk how that exactly works) ?

**Comment by soumyamahunt** [comment]
> I tried to install both. `Notepads.Notepads` installs from github while `JackieLiu.NotepadsApp` installs from a binary hosted on winget storage or something (idk how that exactly works) ?

Initially winget didn't support installing Windows Store apps, so @JasonStein added Notepads (`Notepads.Notepads`) to winget repo. Now that winget supports installing store apps both winget repo version (`Notepads.Notepads`) and store version (`JackieLiu.NotepadsApp`) are appearing. Use the store version since it is regularly updated.

**Comment by yaamas** [comment]
Oh. I was worried about the store version because the description still says "What's new in v1.3.7.0", but it turned out to be the latest. It also doesn't  actually show which version of an App I am installing, so even more confusion.
