### ISSUE TITLE
[Feature request] formatting for code

### ISSUE THREAD

**Issue by versavius** [JasonStein/Notepads#90]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
In notepad++ code such as php is differentiated in different colours for easy reading, can this be added so your app works like notepad++ for handling code colours

**Comment by yaichenbaum** [comment]
Seems like this issue is discussed with #74 
I would love to have this in Notepads.

**Comment by JasonStein** [comment]
Duplicate: #74
