### ISSUE TITLE
Shortcut for Tab Switching [Feature request]

### ISSUE THREAD

**Issue by shiny-apricot** [JasonStein/Notepads#921]
While using keyboard, moving your hand to your mouse repeatedly to switch between tabs might be disgusting after some time.

To solve this, adding shortcut like _Alt+Right , Alt+Left or Alt+ 1,2,3..._ for switching between tabs might enhance the user experience.

**Comment by soumyamahunt** [comment]
> - Ctrl+(Shift)+Tab to switch between tabs.
> - Ctrl+Num(1-9) to quickly switch to specified tab.

Tab switching shortcuts are documented in home page.

**Comment by shiny-apricot** [comment]
I don't have numpad keyboard and ctrl + tab is bit hard to use. Ctrl + Left,Right might be better for ergonomics.

**Comment by JasonStein** [comment]
> I don't have numpad keyboard and ctrl + tab is bit hard to use. Ctrl + Left,Right might be better for ergonomics.

Ctrl+(Shift)+Tab to switch between tabs.
Ctrl+Num(1-9) to quickly switch to specified tab.

This is basically following the standard used by most of the apps that supports tab switching.
