### ISSUE TITLE
[Bug] Add setting the selected text , and remove the brakes thank you dear colleagues.

### ISSUE THREAD

**Issue by korenevskiy** [JasonStein/Notepads#924]
There is no more strength and urine. It's very hard, I'm very tired.
1. The selected text is almost invisible. Make the selected text brighter. I'm using a dark theme. In a dark theme, the highlighted text is almost invisible, especially when the sky is bright during the day. In the room, the selected text is not visible at all.
2. Copying slows down, the context menu freezes, and the Ctrl+C buttons slow down a lot. Each time pressing the Ctrl + buttonsC The text is NOT copied. You have to click only the context menu of the mouse, but it slows down for 10 seconds.

**Comment by JasonStein** [comment]
Try change accent color.

**Comment by korenevskiy** [comment]
Please add larger contrast for select color
