### ISSUE TITLE
[Not Sure] Notepads respond to white-space characters unless its followed by any other character. 

### ISSUE THREAD

**Issue by MR-Seven-7** [JasonStein/Notepads#927]
Notepads respond to white-space characters unless its followed by any other character.  For example if Word Wrap is ON. And if you reach to the end of the line and then hit space bar it should take the cursor to the next line. Or if Word Wrap is OFF. It should
add a white-space and take the cursor to the end of the line. I'm not sure if it is Bug or a Feature, cause some primitive editors do have such behavior.

**Comment by JasonStein** [comment]
It is a "feature" of WinRT RichEdit I would say and I do not have control over it's behavior here.
