### ISSUE TITLE
[Feature request] Open the last opened file directly upon launch of the application

### ISSUE THREAD

**Issue by iatharva** [JasonStein/Notepads#932]
- Whenever we launch the application it should open the last open file directly in the notepads, just like VS code for reference, or chrome which opens the tab which was lastly opened before closing the application.

- You can add more multiple tab state holding and opening upon launch.
But I am suggesting opening (one) last opened file which a user needs to access frequently or for like notes which I do use.

- I tried opening a file that I need frequently but it takes time to do those actions again on each launch which will get reduced by this feature

- If any user doesn't like it or need it then they can toggle it in the settings.

**Comment by JasonStein** [comment]
![image](https://user-images.githubusercontent.com/1166162/139562539-b16f9690-ceba-4e2a-8f0c-0d2e02ea0752.png)

**Comment by iatharva** [comment]
Oh, Thanks for pointing it out!
