### ISSUE TITLE
[Bug]韩文显示重叠

### ISSUE THREAD

**Issue by oxygen-dioxide** [JasonStein/Notepads#937]
**Describe the bug**
打开一个文件后，第12078行重叠，此后各行缺失

**To Reproduce**
用notepads打开[Korean_2.dict.txt](https://github.com/JasonStein/Notepads/files/6898660/Korean_2.dict.txt)，第12078行重叠，此后各行缺失

**Expected behavior**
像vscode那样，后续各行正常显示

**Screenshots**
![image](https://user-images.githubusercontent.com/54425948/127449394-8561c37a-6046-442e-80d9-c22d7caee435.png)

**Desktop (please complete the following information):**
 - OS: windows 11 22000.100
 - Version 1.4.5.0

**Additional context**

**Comment by JasonStein** [comment]
这是因为WinRT RichEdit的渲染问题，暂时没有解决办法。这也是为什么我限制了文件大小为1MB，我也很无奈。
