### ISSUE TITLE
[Bug]Cannot paste what I have copied after Notepads is closed

### ISSUE THREAD

**Issue by Threonine-Animist** [JasonStein/Notepads#96]
I copy some texts in Notepads. 
When Notepads is running I can paste what I have copied to other places.
But after Notepads is closed it seems that what I copied is lost and cannot paste.
I'm not sure whether it's a bug, a feature or the limit of UWP Applications.

**Comment by JasonStein** [comment]
It is by default and I have tried this: https://github.com/JasonStein/Notepads/commit/62a02338d3619da5acd77ffdc4eb8e408e640f3a
It does not help.

**Comment by JasonStein** [comment]
Actually adding Clipboard.Flush(); after SetContent works. So I guess I fixed your problem here: 
https://github.com/JasonStein/Notepads/commit/98f34c3c2939df27c703c4deb0fa22fb94fdd76a

**Comment by JasonStein** [comment]
Close this issue since v0.9.6.0 is alive.
