### ISSUE TITLE
[Bug]Win11 pinned files on taskbar don't open

### ISSUE THREAD

**Issue by ghastx** [JasonStein/Notepads#964]
**Describe the bug**
when i try to open files pinned in the taskbar quick launch menu i get an error. Worked fine in win10

**To Reproduce**
You must have some files pinned in quicklaunch
1) right click on icon in taskbar
2) click on a pinned file
3) i get an error: "the item you selected is unavalaible, it may have been removed, renamed, ecc.."

EDIT
i found out every file in the right click menu isn't opening.

**Expected behavior**
I expect the file will open

**Screenshots**
![image](https://user-images.githubusercontent.com/92019048/136166877-6fbff397-de2e-4fa8-9c28-dc7a94a69dcb.png)

**Desktop (please complete the following information):**
 - OS: 
Edition	Windows 11 Pro
Version	21H2
Installed on	‎05/‎10/‎2021
OS build	22000.194
Experience	Windows Feature Experience Pack 1000.22000.194.0

 - Version 1.4.5.0

**Additional context**
i found out the the whole quick launch menu is broken, not just pinned items

**Comment by JasonStein** [comment]
This feature needs to be enabled from code behind as well which I have not because of a bug I have seen. The reason you are seeing the recent files here might be a bug of Windows 11. I don't see these on my PC (I am on 22000.282).

**Comment by ghastx** [comment]
with version 1.4.6 quick link menu in the taskbar work perfectly in win11. you can close this issue.
ty
