### ISSUE TITLE
字体设置里没有中文字体[Bug]

### ISSUE THREAD

**Issue by Kevinzgithub** [JasonStein/Notepads#973]
**Describe the bug**
字体设置里看不到中文字体，请问是bug还是别的什么原因呢？谢谢！

 - OS: [e.g. Windows 11
![Snipaste_2021-10-22_13-16-02](https://user-images.githubusercontent.com/84002159/138397296-f7a5bb78-46c8-46cc-9834-fcaf6154bfaf.png)

**Comment by JasonStein** [comment]
有些中文字体是拼音，你仔细找找，然后所有字体都是从系统拿的，如果没有的话就是不支持或者别的原因。单独安装的字体库大部分都能在这里找到。你可以试试找你喜欢的字体单独安装然后重启notepads看看。

**Comment by Kevinzgithub** [comment]
谢谢你

Zhao.

     On Sunday, October 31, 2021, 08:24:03 AM GMT+8, Jiaqi Liu ***@***.***> wrote:  
 
 


有些中文字体是拼音，你仔细找找，然后所有字体都是从系统拿的，如果没有的话就是不支持或者别的原因。单独安装的字体库大部分都能在这里找到。你可以试试找你喜欢的字体单独安装然后重启notepads看看。

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
