### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by star2k** [JasonStein/Notepads#979]
**Describe the bug**
![](http://star2k10.3322.org:888/imgs/2021/11/9f2e8cfd2738cb34.png)
![](http://star2k10.3322.org:888/imgs/2021/11/2385c626f1c07c36.png)

## I don't have the markdown function and history modification function of alt+p in the screenshot. The system is win10. Try to download and install the installation package through the application market and github.
**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1809 17763.593]
 - Version [e.g. v0.9.3.0]

**Additional context**

**Comment by JasonStein** [comment]
The file has to be a markdown file before you can toggle "alt+p" to show the preview. Make sure your file ends with ".md".

Second view is diff-view, you need to have changes to your document and then toggle "alt+d" to show the differences.

**Comment by star2k** [comment]
Originally, I had to save it first, thank you.
