### ISSUE TITLE
Mouse cursor on scrollbar doesn't change from caret

### ISSUE THREAD

**Issue by mdixon4** [JasonStein/Notepads#99]
When moving the mouse cursor over the scrollbar, the mouse cursor remains a caret style cursor, where it should turn to a traditional arrow. It suggests clicking on the scrollbar will somehow change the text entry position, but it doesn't (as hoped).

Minor UI bug, but a bug none the less.

Thank you for this app, it's great!
![caret_cursor](https://user-images.githubusercontent.com/6161289/62095102-b0231700-b2c2-11e9-9dbd-ac8949a64aa2.jpg)

**Comment by JasonStein** [comment]
It can be fixed but I just remember the way to fix it might reduce overall performance (I did not test & verify tho). I can take a look later this week.

**Comment by JasonStein** [comment]
https://github.com/microsoft/microsoft-ui-xaml/issues/1986
![image](https://user-images.githubusercontent.com/1166162/77838878-ca9ce100-712c-11ea-98fc-ad3c33b4a344.png)

**Comment by JasonStein** [comment]
Closing this thread since it is Windows issue.

**Comment by SuhasSrinivasan** [comment]
Hi,
Thank you for making this elegant text editor.
I have raised a query about when UI XAML bug is expected to be fixed.
https://github.com/microsoft/microsoft-ui-xaml/issues/1986#issuecomment-630387817
